export type RoadmapLanguage = "ar" | "en";
export type RoadmapIntent = "informational" | "commercial" | "local" | "transactional";

export type RoadmapFAQ = { q: string; a: string };

export type ArticleRoadmapItem = {
  id: string;
  pairId: string;
  slug: string;
  altSlug: string;
  lang: RoadmapLanguage;
  clusterId: string;
  clusterLabelAr: string;
  clusterLabelEn: string;
  market: string;
  intent: RoadmapIntent;
  primaryKeyword: string;
  supportingKeywords: string[];
  title: string;
  description: string;
  faq: RoadmapFAQ[];
  published: boolean;
};

type ClusterTemplate = {
  id: string;
  labelAr: string;
  labelEn: string;
  market: string;
  intent: RoadmapIntent;
  keywordAr: string;
  keywordEn: string;
  supportingAr: string[];
  supportingEn: string[];
  topics: { ar: string; en: string }[];
};

const clusters: ClusterTemplate[] = [
  {
    id: "seo-foundations",
    labelAr: "أساسيات SEO",
    labelEn: "SEO foundations",
    market: "Global",
    intent: "informational",
    keywordAr: "تعلم SEO",
    keywordEn: "learn SEO",
    supportingAr: ["ما هو السيو", "أساسيات تحسين محركات البحث"],
    supportingEn: ["what is SEO", "SEO basics"],
    topics: [
      { ar: "ما هو السيو وكيف يعمل؟", en: "What is SEO and how does it work?" },
      { ar: "الفرق بين الزحف والفهرسة والترتيب", en: "Crawling vs indexing vs ranking" },
      { ar: "كيف تفهم صفحة نتائج البحث؟", en: "How to read a search results page" },
      { ar: "دورة حياة طلب البحث من السؤال إلى التحويل", en: "The search journey from question to conversion" },
      { ar: "أهم مصطلحات SEO للمبتدئين", en: "The essential SEO vocabulary for beginners" },
      { ar: "كيف تضع هدف SEO قابلًا للقياس؟", en: "How to set a measurable SEO goal" },
      { ar: "كيف تبني خط أساس لأداء الموقع؟", en: "How to build an SEO performance baseline" },
      { ar: "SEO للمواقع الجديدة خطوة بخطوة", en: "SEO for a new website step by step" },
      { ar: "أخطاء المبتدئين في السيو وكيف تتجنبها", en: "Common beginner SEO mistakes and how to avoid them" },
      { ar: "خطة تعلم SEO من البداية حتى الاحتراف", en: "A roadmap to learn SEO from beginner to professional" },
    ],
  },
  {
    id: "technical-seo",
    labelAr: "السيو التقني",
    labelEn: "Technical SEO",
    market: "Global",
    intent: "informational",
    keywordAr: "السيو التقني",
    keywordEn: "Technical SEO",
    supportingAr: ["تحسين سرعة الموقع", "مشاكل SEO التقنية"],
    supportingEn: ["website speed optimization", "technical SEO issues"],
    topics: [
      { ar: "قائمة فحص السيو التقني للمواقع", en: "Technical SEO checklist for websites" },
      { ar: "تحسين سرعة الموقع وتأثيره على التحويل", en: "Website speed optimization and conversion impact" },
      { ar: "Core Web Vitals للمبتدئين", en: "Core Web Vitals for beginners" },
      { ar: "تحسين SEO للموبايل", en: "Mobile SEO optimization" },
      { ar: "كيفية اكتشاف مشاكل JavaScript SEO", en: "How to diagnose JavaScript SEO issues" },
      { ar: "تحسين بنية URLs للسيو", en: "SEO-friendly URL structure" },
      { ar: "الصور وSEO: الضغط وalt text وWebP", en: "Images and SEO: compression, alt text and WebP" },
      { ar: "تحسين تجربة الصفحة بدون تغييرات تجميلية زائدة", en: "Improving page experience without cosmetic over-optimization" },
      { ar: "SEO للمواقع المبنية بـReact وJavaScript", en: "SEO for React and JavaScript websites" },
      { ar: "كيف ترتب إصلاحات الأوديت التقني؟", en: "How to prioritize technical audit fixes" },
    ],
  },
  {
    id: "seo-audit",
    labelAr: "SEO Audit",
    labelEn: "SEO audits",
    market: "Global",
    intent: "commercial",
    keywordAr: "فحص SEO للموقع",
    keywordEn: "SEO audit",
    supportingAr: ["أوديت سيو", "قائمة فحص SEO"],
    supportingEn: ["technical SEO audit", "SEO audit checklist"],
    topics: [
      { ar: "ماذا يشمل SEO Audit احترافي؟", en: "What a professional SEO audit includes" },
      { ar: "أوديت SEO للموقع قبل طلب الخدمة", en: "An SEO audit before hiring a provider" },
      { ar: "أوديت المحتوى والصفحات التي لا تجلب عملاء", en: "Content audit for pages that do not generate leads" },
      { ar: "أوديت الروابط الداخلية للمواقع الكبيرة", en: "Internal link auditing for large websites" },
      { ar: "أوديت الفهرسة وCoverage في Search Console", en: "Indexing and Coverage audit in Search Console" },
      { ar: "أوديت Schema والبيانات المنظمة", en: "Schema and structured data audit" },
      { ar: "أوديت متجر إلكتروني كامل", en: "A complete e-commerce SEO audit" },
      { ar: "أوديت Local SEO لفرع أو نشاط محلي", en: "A Local SEO audit for a local business" },
      { ar: "قائمة أوديت SEO شهرية قابلة للتنفيذ", en: "A monthly SEO audit checklist you can act on" },
      { ar: "كيف تحول الأوديت إلى خطة تنفيذ؟", en: "How to turn an audit into an implementation plan" },
    ],
  },
  {
    id: "on-page-seo",
    labelAr: "On-Page SEO",
    labelEn: "On-page SEO",
    market: "Global",
    intent: "informational",
    keywordAr: "SEO On Page",
    keywordEn: "On-page SEO",
    supportingAr: ["تحسين المحتوى للسيو", "عنوان الصفحة SEO"],
    supportingEn: ["SEO content optimization", "SEO title tag"],
    topics: [
      { ar: "تحسين عنوان الصفحة والوصف التعريفي", en: "Optimizing title tags and meta descriptions" },
      { ar: "H1 وH2: هيكلة الصفحة للمستخدم ومحرك البحث", en: "H1 and H2 headings for users and search engines" },
      { ar: "تحسين صفحة خدمة للسيو والتحويل", en: "Optimizing a service page for SEO and conversion" },
      { ar: "تحسين المقالات القديمة بدل حذفها", en: "Refreshing old articles instead of deleting them" },
      { ar: "استخدام الكلمات المفتاحية بدون حشو", en: "Using keywords without stuffing" },
      { ar: "تحسين الروابط الداخلية داخل المقال", en: "Improving internal links inside an article" },
      { ar: "تحسين الصور والعناصر المرئية للمقال", en: "Optimizing images and visual elements in content" },
      { ar: "قائمة فحص On-Page SEO قبل النشر", en: "An on-page SEO pre-publish checklist" },
      { ar: "تحسين صفحات المقارنة والبدائل", en: "Optimizing comparison and alternatives pages" },
      { ar: "كيف تراجع جودة صفحة مستهدفة؟", en: "How to review the quality of a target page" },
    ],
  },
  {
    id: "keyword-research",
    labelAr: "بحث الكلمات المفتاحية",
    labelEn: "Keyword research",
    market: "Global",
    intent: "informational",
    keywordAr: "بحث الكلمات المفتاحية",
    keywordEn: "Keyword research",
    supportingAr: ["استراتيجية الكلمات", "نية البحث"],
    supportingEn: ["keyword strategy", "search intent"],
    topics: [
      { ar: "طريقة بحث الكلمات المفتاحية خطوة بخطوة", en: "Keyword research step by step" },
      { ar: "كيف تحدد نية البحث لكل كلمة؟", en: "How to identify search intent for every keyword" },
      { ar: "الكلمات التجارية مقابل المعلوماتية", en: "Commercial vs informational keywords" },
      { ar: "بحث كلمات لمتجر إلكتروني", en: "Keyword research for an e-commerce store" },
      { ar: "بحث كلمات لخدمات B2B وSaaS", en: "Keyword research for B2B and SaaS" },
      { ar: "تجميع الكلمات في Topic Clusters", en: "Grouping keywords into topic clusters" },
      { ar: "كيف تقيس قيمة الكلمة بدل حجم البحث فقط؟", en: "How to value a keyword beyond search volume" },
      { ar: "Keyword Mapping بين الكلمات والصفحات", en: "Keyword mapping between queries and pages" },
      { ar: "بحث الكلمات العربية والإنجليزية معًا", en: "Bilingual Arabic and English keyword research" },
      { ar: "أخطاء Keyword Research التي تضيّع الميزانية", en: "Keyword research mistakes that waste budget" },
    ],
  },
  {
    id: "content-seo",
    labelAr: "استراتيجية المحتوى",
    labelEn: "Content strategy",
    market: "Global",
    intent: "informational",
    keywordAr: "كتابة محتوى SEO",
    keywordEn: "SEO content writing",
    supportingAr: ["استراتيجية المحتوى", "مقال متوافق مع السيو"],
    supportingEn: ["content strategy", "SEO-friendly article"],
    topics: [
      { ar: "كيف تكتب مقال SEO مفيدًا فعلًا؟", en: "How to write genuinely useful SEO content" },
      { ar: "Content Brief احترافي قبل الكتابة", en: "A professional content brief before writing" },
      { ar: "بناء Topic Cluster لموقع خدمات", en: "Building a topic cluster for a service website" },
      { ar: "خطة محتوى SEO لمدة 90 يومًا", en: "A 90-day SEO content plan" },
      { ar: "تحديث المحتوى حسب بيانات Search Console", en: "Refreshing content using Search Console data" },
      { ar: "E-E-A-T وتوثيق الخبرة داخل المقال", en: "E-E-A-T and demonstrating experience in content" },
      { ar: "كتابة الأسئلة والأجوبة للمحتوى", en: "Writing useful questions and answers in content" },
      { ar: "استراتيجية المحتوى للمتاجر الإلكترونية", en: "Content strategy for e-commerce stores" },
      { ar: "كيف تقيس جودة المحتوى؟", en: "How to measure content quality" },
      { ar: "تقويم تحريري مرتبط بمراحل العميل", en: "An editorial calendar tied to the customer journey" },
    ],
  },
  {
    id: "aeo-geo",
    labelAr: "AEO وGEO",
    labelEn: "AEO and GEO",
    market: "Global",
    intent: "informational",
    keywordAr: "AEO وGEO",
    keywordEn: "AEO and GEO",
    supportingAr: ["الظهور في إجابات AI", "تحسين البحث التوليدي"],
    supportingEn: ["AI answer visibility", "generative search optimization"],
    topics: [
      { ar: "ما هو AEO وما علاقته بـSEO؟", en: "What is AEO and how does it relate to SEO?" },
      { ar: "ما هو GEO في البحث التوليدي؟", en: "What is GEO in generative search?" },
      { ar: "كيف تكتب إجابة قابلة للاقتباس؟", en: "How to write a citable answer" },
      { ar: "FAQ Schema: متى يفيد ومتى لا تستخدمه؟", en: "FAQ Schema: when it helps and when not to use it" },
      { ar: "Entity SEO وبناء فهم واضح للعلامة", en: "Entity SEO and clearer brand understanding" },
      { ar: "تنظيم المقالات لمحركات الإجابات", en: "Structuring articles for answer engines" },
      { ar: "AEO للمواقع العربية", en: "AEO for Arabic websites" },
      { ar: "كيف تقيس الظهور في إجابات الذكاء الاصطناعي؟", en: "How to measure visibility in AI answers" },
      { ar: "الفرق بين Featured Snippet وAI citation", en: "Featured snippets vs AI citations" },
      { ar: "هل يمكن ضمان الظهور في إجابات AI؟", en: "Can AI answer visibility be guaranteed?" },
    ],
  },
  {
    id: "ai-seo",
    labelAr: "AI SEO",
    labelEn: "AI SEO",
    market: "Global",
    intent: "commercial",
    keywordAr: "AI SEO",
    keywordEn: "AI SEO",
    supportingAr: ["SEO بالذكاء الاصطناعي", "أتمتة المحتوى"],
    supportingEn: ["AI-powered SEO", "content automation"],
    topics: [
      { ar: "كيف تستخدم AI في بحث الكلمات؟", en: "How to use AI for keyword research" },
      { ar: "AI في تحليل المنافسين بدون نسخ المحتوى", en: "Using AI for competitor analysis without copying content" },
      { ar: "برومبتات عملية لخبير SEO", en: "Practical prompts for SEO specialists" },
      { ar: "مراجعة محتوى AI قبل النشر", en: "Reviewing AI-assisted content before publishing" },
      { ar: "AI SEO للمتاجر الإلكترونية", en: "AI SEO for e-commerce stores" },
      { ar: "بناء Content Operations بالذكاء الاصطناعي", en: "Building AI-assisted content operations" },
      { ar: "مخاطر المحتوى الآلي على جودة الموقع", en: "The risks of automated content to site quality" },
      { ar: "استخدام AI في تحليل Search Console", en: "Using AI to analyze Search Console" },
      { ar: "هل AI يقتل SEO؟ تحليل عملي", en: "Will AI kill SEO? A practical analysis" },
      { ar: "سياسة استخدام AI داخل فريق المحتوى", en: "An AI usage policy for content teams" },
    ],
  },
  {
    id: "local-egypt",
    labelAr: "Local SEO في مصر",
    labelEn: "Local SEO in Egypt",
    market: "Egypt",
    intent: "local",
    keywordAr: "سيو محلي مصر",
    keywordEn: "Local SEO Egypt",
    supportingAr: ["خبير SEO مصر", "SEO القاهرة"],
    supportingEn: ["SEO expert Egypt", "SEO Cairo"],
    topics: [
      { ar: "كيف تظهر أمام عملاء القاهرة؟", en: "How to reach customers in Cairo" },
      { ar: "Google Business Profile للشركات المصرية", en: "Google Business Profile for Egyptian businesses" },
      { ar: "Local SEO للمطاعم والعيادات في مصر", en: "Local SEO for restaurants and clinics in Egypt" },
      { ar: "اختيار كلمات البحث المحلية باللهجة والفصحى", en: "Choosing local queries in Egyptian Arabic and MSA" },
      { ar: "SEO للشركات التي تخدم أكثر من محافظة", en: "SEO for businesses serving multiple Egyptian governorates" },
      { ar: "مراجعات العملاء وأثرها على الظهور المحلي", en: "Customer reviews and local visibility" },
      { ar: "صفحة خدمة محلية لمشروع في القاهرة", en: "A local service page for a Cairo business" },
      { ar: "SEO للمتاجر التي تشحن داخل مصر", en: "SEO for stores shipping across Egypt" },
      { ar: "أخطاء Local SEO الشائعة في مصر", en: "Common Local SEO mistakes in Egypt" },
      { ar: "اختيار شريك SEO في مصر بمعايير شفافة", en: "Choosing an SEO partner in Egypt transparently" },
    ],
  },
  {
    id: "seo-services-egypt",
    labelAr: "خدمات SEO في مصر",
    labelEn: "SEO services in Egypt",
    market: "Egypt",
    intent: "commercial",
    keywordAr: "خدمات سيو مصر",
    keywordEn: "SEO Services in Egypt",
    supportingAr: ["شركة SEO مصر", "SEO Consultant Egypt"],
    supportingEn: ["SEO Company in Egypt", "SEO Consultant Egypt"],
    topics: [
      { ar: "ماذا تشمل خدمات SEO في مصر؟", en: "What SEO services in Egypt include" },
      { ar: "اختيار شركة SEO في مصر للمشاريع الصغيرة", en: "Choosing an SEO company in Egypt for small businesses" },
      { ar: "استشاري SEO مصر أم وكالة؟", en: "SEO consultant Egypt vs agency" },
      { ar: "SEO للتجارة الإلكترونية في السوق المصري", en: "E-commerce SEO for the Egyptian market" },
      { ar: "Technical SEO للمواقع المصرية", en: "Technical SEO for Egyptian websites" },
      { ar: "Content SEO باللهجة المصرية والفصحى", en: "Content SEO in Egyptian Arabic and MSA" },
      { ar: "تكلفة SEO في مصر وما الذي يحددها؟", en: "SEO cost in Egypt and what determines it" },
      { ar: "خطة SEO للشركات الناشئة في القاهرة", en: "An SEO plan for Cairo startups" },
      { ar: "تقرير SEO الذي يجب أن تستلمه من مقدم الخدمة", en: "The SEO report you should receive from a provider" },
      { ar: "كيف تطلب عرض خدمة SEO مناسب؟", en: "How to request a suitable SEO proposal" },
    ],
  },
  {
    id: "local-saudi",
    labelAr: "SEO في السعودية",
    labelEn: "SEO in Saudi Arabia",
    market: "Saudi Arabia",
    intent: "local",
    keywordAr: "خبير سيو السعودية",
    keywordEn: "SEO Expert Saudi Arabia",
    supportingAr: ["SEO الرياض", "SEO جدة"],
    supportingEn: ["SEO Riyadh", "SEO Jeddah"],
    topics: [
      { ar: "كيف تختار خبير SEO في السعودية؟", en: "How to choose an SEO expert in Saudi Arabia" },
      { ar: "خدمات SEO للشركات السعودية", en: "SEO services for Saudi businesses" },
      { ar: "SEO للمتاجر في السوق السعودي", en: "E-commerce SEO for the Saudi market" },
      { ar: "بحث الكلمات السعودية بالعربي والإنجليزي", en: "Arabic and English keyword research for Saudi Arabia" },
      { ar: "Local SEO للفروع داخل المملكة", en: "Local SEO for branches across Saudi Arabia" },
      { ar: "SEO للمنتجات والخدمات الموسمية في السعودية", en: "SEO for seasonal products and services in Saudi Arabia" },
      { ar: "SEO Consultant Saudi Arabia: أسئلة قبل التعاقد", en: "SEO Consultant Saudi Arabia: questions before hiring" },
      { ar: "شركة SEO السعودية: كيف تقارن العروض؟", en: "SEO Agency Saudi Arabia: how to compare proposals" },
      { ar: "تسعير SEO في السعودية بدون وعود ثابتة", en: "SEO pricing in Saudi Arabia without fixed promises" },
      { ar: "قياس العملاء القادمين من SEO في السعودية", en: "Measuring SEO leads in Saudi Arabia" },
    ],
  },
  {
    id: "seo-riyadh",
    labelAr: "SEO في الرياض",
    labelEn: "SEO in Riyadh",
    market: "Riyadh",
    intent: "local",
    keywordAr: "خبير SEO الرياض",
    keywordEn: "SEO Services Riyadh",
    supportingAr: ["خدمات سيو الرياض", "شركة SEO الرياض"],
    supportingEn: ["SEO Agency Riyadh", "SEO Consultant Riyadh"],
    topics: [
      { ar: "خدمات SEO في الرياض للشركات والمتاجر", en: "SEO services in Riyadh for businesses and stores" },
      { ar: "اختيار SEO Consultant Riyadh", en: "Choosing an SEO Consultant in Riyadh" },
      { ar: "Local SEO لفروع الشركات في الرياض", en: "Local SEO for business branches in Riyadh" },
      { ar: "SEO للقطاع العقاري في الرياض", en: "SEO for real estate in Riyadh" },
      { ar: "SEO للعيادات والخدمات الطبية في الرياض", en: "SEO for clinics and healthcare in Riyadh" },
      { ar: "SEO لمتاجر التجزئة في الرياض", en: "SEO for retail stores in Riyadh" },
      { ar: "Landing pages محلية للسوق في الرياض", en: "Local landing pages for the Riyadh market" },
      { ar: "كيف تقيس نتائج SEO في الرياض؟", en: "How to measure SEO results in Riyadh" },
      { ar: "أسئلة مهمة قبل اختيار وكالة SEO بالرياض", en: "Questions before choosing an SEO agency in Riyadh" },
      { ar: "خطة محتوى SEO تستهدف الباحثين في الرياض", en: "An SEO content plan for Riyadh searchers" },
    ],
  },
  {
    id: "seo-jeddah",
    labelAr: "SEO في جدة",
    labelEn: "SEO in Jeddah",
    market: "Jeddah",
    intent: "local",
    keywordAr: "خبير سيو جدة",
    keywordEn: "SEO Expert in Jeddah",
    supportingAr: ["خدمات SEO جدة", "سيو محلي جدة"],
    supportingEn: ["SEO services Jeddah", "Local SEO Jeddah"],
    topics: [
      { ar: "كيف تختار خبير SEO جدة؟", en: "How to choose an SEO expert in Jeddah" },
      { ar: "خدمات السيو المناسبة لشركات جدة", en: "SEO services for Jeddah businesses" },
      { ar: "Local SEO للمطاعم والفنادق في جدة", en: "Local SEO for restaurants and hotels in Jeddah" },
      { ar: "SEO لمتجر إلكتروني يخدم جدة", en: "SEO for an e-commerce store serving Jeddah" },
      { ar: "محتوى SEO للجمهور في جدة", en: "SEO content for audiences in Jeddah" },
      { ar: "تحسين Google Business Profile في جدة", en: "Optimizing Google Business Profile in Jeddah" },
      { ar: "صفحات المدن: متى تكون مفيدة ومتى تصبح ضعيفة؟", en: "City pages: when they help and when they become thin" },
      { ar: "SEO Consultant Jeddah: معايير الشفافية", en: "SEO Consultant Jeddah: transparency criteria" },
      { ar: "قياس المكالمات والطلبات من SEO في جدة", en: "Measuring calls and enquiries from SEO in Jeddah" },
      { ar: "مقارنة عروض SEO لشركات جدة", en: "Comparing SEO proposals for Jeddah businesses" },
    ],
  },
  {
    id: "seo-uae-dubai",
    labelAr: "SEO في الإمارات ودبي",
    labelEn: "SEO in the UAE and Dubai",
    market: "UAE / Dubai",
    intent: "local",
    keywordAr: "خدمات SEO في الإمارات",
    keywordEn: "SEO Services in the UAE",
    supportingAr: ["خبير SEO دبي", "SEO دبي"],
    supportingEn: ["SEO Expert in Dubai", "SEO Dubai"],
    topics: [
      { ar: "خدمات SEO في الإمارات لسوق متعدد اللغات", en: "SEO services in the UAE for a multilingual market" },
      { ar: "كيف تختار خبير SEO دبي؟", en: "How to choose an SEO expert in Dubai" },
      { ar: "SEO للشركات الناشئة في دبي", en: "SEO for startups in Dubai" },
      { ar: "SEO للمتاجر الإلكترونية في الإمارات", en: "E-commerce SEO in the UAE" },
      { ar: "Local SEO للفروع في دبي وأبوظبي", en: "Local SEO for branches in Dubai and Abu Dhabi" },
      { ar: "SEO بالعربي والإنجليزي في الإمارات", en: "Arabic and English SEO in the UAE" },
      { ar: "محتوى SEO للضيافة والسياحة في دبي", en: "SEO content for hospitality and tourism in Dubai" },
      { ar: "SEO Consultant Dubai: ماذا تسأل قبل التعاقد؟", en: "SEO Consultant Dubai: what to ask before hiring" },
      { ar: "تسعير SEO في دبي حسب النطاق والمنافسة", en: "SEO pricing in Dubai by scope and competition" },
      { ar: "كيف تقارن وكالة SEO في الإمارات؟", en: "How to compare an SEO agency in the UAE" },
    ],
  },
  {
    id: "seo-kuwait",
    labelAr: "SEO في الكويت",
    labelEn: "SEO in Kuwait",
    market: "Kuwait",
    intent: "local",
    keywordAr: "خدمات SEO في الكويت",
    keywordEn: "SEO Services in Kuwait",
    supportingAr: ["SEO الكويت", "سيو المتاجر الكويت"],
    supportingEn: ["SEO Kuwait", "e-commerce SEO Kuwait"],
    topics: [
      { ar: "خطة SEO للشركات والمتاجر في الكويت", en: "An SEO plan for Kuwait businesses and stores" },
      { ar: "بحث الكلمات العربية والإنجليزية في الكويت", en: "Arabic and English keyword research in Kuwait" },
      { ar: "Local SEO للأنشطة داخل الكويت", en: "Local SEO for businesses in Kuwait" },
      { ar: "SEO للمتاجر التي تشحن داخل الكويت", en: "SEO for stores shipping across Kuwait" },
      { ar: "اختيار شركة SEO في الكويت", en: "Choosing an SEO company in Kuwait" },
      { ar: "SEO للقطاع الطبي في الكويت", en: "SEO for healthcare in Kuwait" },
      { ar: "محتوى SEO باللهجة والسياق الكويتي", en: "SEO content for the Kuwaiti context" },
      { ar: "Technical SEO لمواقع الخدمات في الكويت", en: "Technical SEO for Kuwait service websites" },
      { ar: "قياس العملاء والتحويلات من SEO في الكويت", en: "Measuring SEO leads and conversions in Kuwait" },
      { ar: "أسئلة قبل طلب خدمات سيو في الكويت", en: "Questions before buying SEO services in Kuwait" },
    ],
  },
  {
    id: "seo-qatar",
    labelAr: "SEO في قطر",
    labelEn: "SEO in Qatar",
    market: "Qatar",
    intent: "local",
    keywordAr: "خدمات SEO في قطر",
    keywordEn: "SEO Services in Qatar",
    supportingAr: ["SEO قطر", "سيو محلي قطر"],
    supportingEn: ["SEO Qatar", "Local SEO Qatar"],
    topics: [
      { ar: "كيف تبني ظهورًا عضويًا في قطر؟", en: "How to build organic visibility in Qatar" },
      { ar: "SEO للشركات المحلية في الدوحة", en: "SEO for local businesses in Doha" },
      { ar: "SEO للمتاجر الإلكترونية في قطر", en: "E-commerce SEO in Qatar" },
      { ar: "الكلمات العربية والإنجليزية في السوق القطري", en: "Arabic and English keywords in Qatar" },
      { ar: "اختيار مقدم خدمات SEO في قطر", en: "Choosing an SEO provider in Qatar" },
      { ar: "Google Business Profile للأنشطة في قطر", en: "Google Business Profile for Qatar businesses" },
      { ar: "SEO للضيافة والخدمات في قطر", en: "SEO for hospitality and services in Qatar" },
      { ar: "فحص SEO التقني لموقع قطري", en: "A technical SEO audit for a Qatar website" },
      { ar: "قياس جودة العملاء من SEO في قطر", en: "Measuring lead quality from SEO in Qatar" },
      { ar: "تكلفة SEO في قطر وما يغير النطاق", en: "SEO cost in Qatar and what changes scope" },
    ],
  },
  {
    id: "ecommerce-seo",
    labelAr: "SEO للمتاجر الإلكترونية",
    labelEn: "E-commerce SEO",
    market: "Global / MENA",
    intent: "transactional",
    keywordAr: "سيو متجر إلكتروني",
    keywordEn: "E-commerce SEO",
    supportingAr: ["SEO المنتجات", "تحسين صفحات الفئات"],
    supportingEn: ["product SEO", "category page optimization"],
    topics: [
      { ar: "خطة SEO كاملة للمتجر الإلكتروني", en: "A complete SEO plan for an e-commerce store" },
      { ar: "تحسين صفحات الفئات والمنتجات", en: "Optimizing category and product pages" },
      { ar: "Product SEO: عناوين ووصف المنتجات", en: "Product SEO: titles and product descriptions" },
      { ar: "SEO للفلاتر والصفحات المكررة", en: "SEO for faceted navigation and duplicate pages" },
      { ar: "Schema للمنتجات والمراجعات والأسعار", en: "Product, review and price schema" },
      { ar: "SEO لمتجر Shopify", en: "SEO for a Shopify store" },
      { ar: "SEO لمتجر WooCommerce", en: "SEO for a WooCommerce store" },
      { ar: "سيو المتاجر العربية متعددة العملات", en: "SEO for Arabic multi-currency stores" },
      { ar: "تحسين التحويل من الزيارات العضوية", en: "Improving conversion from organic traffic" },
      { ar: "أوديت SEO للمتجر قبل التوسع", en: "An e-commerce SEO audit before scaling" },
    ],
  },
  {
    id: "international-seo",
    labelAr: "International SEO",
    labelEn: "International SEO",
    market: "Global / MENA",
    intent: "commercial",
    keywordAr: "السيو الدولي",
    keywordEn: "International SEO",
    supportingAr: ["hreflang", "SEO متعدد اللغات"],
    supportingEn: ["hreflang", "multilingual SEO"],
    topics: [
      { ar: "Hreflang خطوة بخطوة", en: "Hreflang step by step" },
      { ar: "اختيار هيكل الدومين للسيو الدولي", en: "Choosing a domain structure for international SEO" },
      { ar: "ترجمة المحتوى أم Localization؟", en: "Content translation vs localization" },
      { ar: "SEO عربي وإنجليزي للموقع نفسه", en: "Arabic and English SEO for one website" },
      { ar: "تجنب تكرار صفحات الدول", en: "Avoiding duplicate country pages" },
      { ar: "بحث الكلمات عبر أسواق الخليج", en: "Keyword research across Gulf markets" },
      { ar: "تقارير SEO متعددة الأسواق", en: "SEO reporting across multiple markets" },
      { ar: "International SEO للمتاجر", en: "International SEO for e-commerce" },
      { ar: "أخطاء hreflang الشائعة", en: "Common hreflang mistakes" },
      { ar: "خطة توسع SEO من مصر إلى الخليج", en: "An SEO expansion plan from Egypt to the Gulf" },
    ],
  },
  {
    id: "programmatic-seo",
    labelAr: "Programmatic SEO",
    labelEn: "Programmatic SEO",
    market: "Global / MENA",
    intent: "informational",
    keywordAr: "Programmatic SEO",
    keywordEn: "Programmatic SEO",
    supportingAr: ["صفحات قابلة للتوسع", "SEO بالقوالب"],
    supportingEn: ["scalable landing pages", "template SEO"],
    topics: [
      { ar: "متى تستخدم Programmatic SEO؟", en: "When to use programmatic SEO" },
      { ar: "بناء صفحات قابلة للتوسع بدون محتوى ضعيف", en: "Building scalable pages without thin content" },
      { ar: "قواعد جودة صفحات القوالب", en: "Quality rules for template-driven pages" },
      { ar: "Programmatic SEO للمتاجر", en: "Programmatic SEO for e-commerce" },
      { ar: "صفحات المدن والخدمات: قيمة أم Doorway؟", en: "City and service pages: value or doorway pages?" },
      { ar: "ربط البيانات بالمحتوى القابل للتوسع", en: "Connecting data to scalable content" },
      { ar: "فهرسة الصفحات المولدة برمجيًا", en: "Indexing programmatically generated pages" },
      { ar: "مراقبة التكرار في صفحات القوالب", en: "Monitoring duplication in template pages" },
      { ar: "Programmatic SEO متعدد اللغات", en: "Multilingual programmatic SEO" },
      { ar: "متى توقف أو تحذف مجموعة صفحات؟", en: "When to pause or prune a page set" },
    ],
  },
  {
    id: "link-building-pr",
    labelAr: "Link Building وDigital PR",
    labelEn: "Link building and Digital PR",
    market: "Global / MENA",
    intent: "commercial",
    keywordAr: "بناء الروابط",
    keywordEn: "Link building",
    supportingAr: ["Backlinks", "Digital PR"],
    supportingEn: ["backlinks", "digital PR"],
    topics: [
      { ar: "بناء روابط آمنة للمواقع", en: "Safe link building for websites" },
      { ar: "كيف تقيم جودة الباك لينك؟", en: "How to evaluate backlink quality" },
      { ar: "Digital PR للسيو", en: "Digital PR for SEO" },
      { ar: "التواصل مع المواقع بدون رسائل مزعجة", en: "Outreach without spammy messages" },
      { ar: "بناء روابط لمتجر إلكتروني", en: "Link building for an e-commerce store" },
      { ar: "دراسة المنافسين بدون نسخ روابطهم", en: "Competitor link analysis without copying blindly" },
      { ar: "متى تحتاج Disavow؟", en: "When do you need disavow?" },
      { ar: "قياس أثر الروابط على النمو", en: "Measuring link impact on growth" },
      { ar: "استراتيجية روابط للمحتوى المحلي", en: "Link strategy for local content" },
      { ar: "أخطاء شراء الروابط التي تضر الموقع", en: "Link buying mistakes that can hurt a site" },
    ],
  },
  {
    id: "analytics-reporting",
    labelAr: "Analytics وSearch Console",
    labelEn: "Analytics and reporting",
    market: "Global",
    intent: "informational",
    keywordAr: "تحليلات SEO",
    keywordEn: "SEO analytics",
    supportingAr: ["Google Search Console", "GA4 SEO"],
    supportingEn: ["Google Search Console", "GA4 SEO"],
    topics: [
      { ar: "قراءة Search Console للمبتدئين", en: "Reading Search Console for beginners" },
      { ar: "ربط GA4 بأهداف SEO", en: "Connecting GA4 to SEO goals" },
      { ar: "CTR والانطباعات والنقرات: كيف تفسرها؟", en: "CTR, impressions and clicks: how to interpret them" },
      { ar: "تقرير SEO شهري يفهمه صاحب المشروع", en: "A monthly SEO report stakeholders understand" },
      { ar: "Looker Studio لتقارير السيو", en: "Looker Studio for SEO reporting" },
      { ar: "تحليل الصفحات التي فقدت الزيارات", en: "Analyzing pages that lost traffic" },
      { ar: "قياس التحويلات من البحث العضوي", en: "Measuring organic search conversions" },
      { ar: "تحليل Queries في Search Console", en: "Analyzing queries in Search Console" },
      { ar: "كيف تفرق بين مشكلة ترتيب ومشكلة تحويل؟", en: "Ranking problem vs conversion problem" },
      { ar: "لوحة مؤشرات SEO لفريق صغير", en: "An SEO dashboard for a small team" },
    ],
  },
  {
    id: "cro-growth",
    labelAr: "CRO ونمو الأعمال",
    labelEn: "CRO and growth",
    market: "Global / MENA",
    intent: "commercial",
    keywordAr: "تحسين التحويل من SEO",
    keywordEn: "SEO conversion optimization",
    supportingAr: ["زيادة العملاء من السيو", "تحسين صفحات الهبوط"],
    supportingEn: ["SEO lead generation", "landing page optimization"],
    topics: [
      { ar: "كيف تحول زيارات SEO إلى عملاء؟", en: "How to turn SEO traffic into leads" },
      { ar: "تحسين CTA في صفحات الخدمات", en: "Improving CTAs on service pages" },
      { ar: "رسالة الصفحة وعلاقتها بنية البحث", en: "Page messaging and search intent" },
      { ar: "تحسين صفحة المنتج للشراء", en: "Optimizing a product page for purchase" },
      { ar: "اختبار العناوين بدون الإضرار بالسيو", en: "Testing headlines without hurting SEO" },
      { ar: "Lead quality مقابل عدد الزيارات", en: "Lead quality vs traffic volume" },
      { ar: "SEO Funnel من الوعي إلى الطلب", en: "The SEO funnel from awareness to enquiry" },
      { ar: "تحسين نماذج التواصل", en: "Improving contact forms" },
      { ar: "ربط SEO بالـCRM", en: "Connecting SEO to the CRM" },
      { ar: "حساب قيمة العميل القادم من البحث", en: "Calculating the value of an organic customer" },
    ],
  },
  {
    id: "marketing-automation",
    labelAr: "Marketing Automation وn8n",
    labelEn: "Marketing automation and n8n",
    market: "Global / MENA",
    intent: "commercial",
    keywordAr: "أتمتة التسويق",
    keywordEn: "marketing automation",
    supportingAr: ["n8n للتسويق", "أتمتة تقارير SEO"],
    supportingEn: ["n8n marketing workflows", "SEO reporting automation"],
    topics: [
      { ar: "أتمتة تقارير SEO باستخدام n8n", en: "Automating SEO reports with n8n" },
      { ar: "جمع بيانات Search Console تلقائيًا", en: "Automating Search Console data collection" },
      { ar: "تنبيهات انخفاض الزيارات العضوية", en: "Alerts for organic traffic drops" },
      { ar: "أتمتة مراجعة Content Brief", en: "Automating content brief review" },
      { ar: "ربط SEO بالـCRM والبريد الإلكتروني", en: "Connecting SEO to CRM and email" },
      { ar: "حواجز أمان تمنع نشر محتوى ضعيف", en: "Guardrails that prevent thin content publishing" },
      { ar: "Workflow لفرز فرص الكلمات المفتاحية", en: "A workflow to triage keyword opportunities" },
      { ar: "أتمتة متابعة العملاء المحتملين", en: "Automating lead follow-up" },
      { ar: "لوحات متابعة SEO للفريق", en: "SEO monitoring boards for teams" },
      { ar: "أخطاء أتمتة التسويق وكيف تتجنبها", en: "Marketing automation mistakes and how to avoid them" },
    ],
  },
  {
    id: "digital-marketing-growth",
    labelAr: "التسويق الرقمي والنمو",
    labelEn: "Digital marketing and growth",
    market: "Global / MENA",
    intent: "commercial",
    keywordAr: "التسويق الرقمي",
    keywordEn: "digital marketing",
    supportingAr: ["استراتيجية التسويق الرقمي", "نمو العملاء"],
    supportingEn: ["digital marketing strategy", "customer acquisition"],
    topics: [
      { ar: "بناء استراتيجية تسويق رقمي متكاملة", en: "Building an integrated digital marketing strategy" },
      { ar: "SEO مقابل القنوات المدفوعة", en: "SEO vs paid channels" },
      { ar: "ربط المحتوى بالطلب التجاري", en: "Connecting content to commercial demand" },
      { ar: "استراتيجية Email Marketing للعملاء المحتملين", en: "Email marketing for qualified leads" },
      { ar: "Digital Marketing للمتاجر الإلكترونية", en: "Digital marketing for e-commerce stores" },
      { ar: "تقسيم الجمهور حسب نية البحث", en: "Segmenting audiences by search intent" },
      { ar: "كيف تبني رسائل تسويقية واضحة؟", en: "How to build clear marketing messages" },
      { ar: "قياس CAC وLTV مع SEO", en: "Measuring CAC and LTV with SEO" },
      { ar: "خطة نمو لمنتج SaaS", en: "A growth plan for a SaaS product" },
      { ar: "تسويق رقمي عملي للشركات الصغيرة", en: "Practical digital marketing for small businesses" },
    ],
  },
  {
    id: "seo-pricing-consulting",
    labelAr: "أسعار واستشارات SEO",
    labelEn: "SEO pricing and consulting",
    market: "Egypt / MENA",
    intent: "transactional",
    keywordAr: "أسعار خدمات السيو",
    keywordEn: "SEO services cost",
    supportingAr: ["تكلفة SEO", "استشارة SEO"],
    supportingEn: ["SEO pricing", "SEO consultation"],
    topics: [
      { ar: "ما الذي يحدد تكلفة خدمات SEO؟", en: "What determines the cost of SEO services?" },
      { ar: "تسعير SEO الشهري مقابل المشروع", en: "Monthly SEO retainers vs project pricing" },
      { ar: "كيف تقارن عروض خدمات SEO؟", en: "How to compare SEO service proposals" },
      { ar: "ماذا تسأل في استشارة SEO الأولى؟", en: "What to ask in a first SEO consultation" },
      { ar: "مخرجات أوديت SEO الاحترافي", en: "Deliverables of a professional SEO audit" },
      { ar: "هل التسعير حسب الأداء مناسب؟", en: "Is performance-based SEO pricing suitable?" },
      { ar: "ميزانية SEO لمتجر ناشئ", en: "An SEO budget for a new store" },
      { ar: "متى تحتاج خبيرًا مستقلًا ومتى تحتاج فريقًا؟", en: "When to hire a consultant vs a team" },
      { ar: "كيف تتجنب وعود الترتيب المبالغ فيها؟", en: "How to avoid exaggerated ranking promises" },
      { ar: "استشارة SEO عن بعد من القاهرة", en: "Remote SEO consulting from Cairo" },
    ],
  },
  {
    id: "professional-seo-delivery",
    labelAr: "التنفيذ الاحترافي",
    labelEn: "Professional SEO delivery",
    market: "Global / MENA",
    intent: "commercial",
    keywordAr: "استراتيجية SEO",
    keywordEn: "SEO strategy",
    supportingAr: ["خطة SEO", "إدارة مشاريع SEO"],
    supportingEn: ["SEO plan", "SEO project management"],
    topics: [
      { ar: "كيف تبني استراتيجية SEO كاملة؟", en: "How to build a complete SEO strategy" },
      { ar: "خطة 30-60-90 يومًا للسيو", en: "A 30-60-90 day SEO plan" },
      { ar: "تحديد الأولويات حسب الأثر والجهد", en: "Prioritizing by impact and effort" },
      { ar: "التعاون بين SEO والمحتوى والتطوير", en: "Aligning SEO, content and development" },
      { ar: "إدارة مشروع SEO مع عميل", en: "Managing an SEO project with a client" },
      { ar: "بناء SOPs لفريق SEO", en: "Building SEO team SOPs" },
      { ar: "مراجعة الجودة قبل نشر تغييرات SEO", en: "Quality review before shipping SEO changes" },
      { ar: "التوثيق والتسليم في مشاريع SEO", en: "Documentation and handover in SEO projects" },
      { ar: "كيف تقدم تقريرًا استشاريًا مقنعًا؟", en: "How to present a persuasive consulting report" },
      { ar: "بناء بورتفوليو SEO بدون مبالغة", en: "Building an SEO portfolio without overclaiming" },
    ],
  },
  {
    id: "seo-tools-process",
    labelAr: "أدوات وعمليات SEO",
    labelEn: "SEO tools and workflows",
    market: "Global",
    intent: "informational",
    keywordAr: "أدوات SEO",
    keywordEn: "SEO tools",
    supportingAr: ["Ahrefs", "SEMrush", "Screaming Frog"],
    supportingEn: ["Ahrefs", "SEMrush", "Screaming Frog"],
    topics: [
      { ar: "اختيار أدوات SEO المناسبة للميزانية", en: "Choosing SEO tools for your budget" },
      { ar: "Ahrefs للمبتدئين", en: "Ahrefs for beginners" },
      { ar: "SEMrush في بحث الكلمات والمنافسين", en: "SEMrush for keyword and competitor research" },
      { ar: "Screaming Frog لأوديت المواقع", en: "Screaming Frog for website audits" },
      { ar: "Search Console أم أدوات الطرف الثالث؟", en: "Search Console vs third-party tools" },
      { ar: "قالب عمل SEO أسبوعي", en: "A weekly SEO workflow template" },
      { ar: "تنظيم Keywords وContent Calendar", en: "Organizing keywords and a content calendar" },
      { ar: "بناء قائمة فحص SEO قابلة لإعادة الاستخدام", en: "Building a reusable SEO checklist" },
      { ar: "توثيق التغييرات ومراقبة النتائج", en: "Documenting changes and monitoring results" },
      { ar: "كيف تمنع الأدوات من قيادة الاستراتيجية؟", en: "How to stop tools from driving strategy" },
    ],
  },
  {
    id: "seo-industry-playbooks",
    labelAr: "أدلة SEO حسب القطاع",
    labelEn: "Industry SEO playbooks",
    market: "Egypt / MENA",
    intent: "commercial",
    keywordAr: "SEO للشركات",
    keywordEn: "SEO for businesses",
    supportingAr: ["SEO للشركات الناشئة", "SEO للقطاعات المختلفة"],
    supportingEn: ["SEO for startups", "industry SEO"],
    topics: [
      { ar: "SEO للشركات الناشئة", en: "SEO for startups" },
      { ar: "SEO لشركات SaaS", en: "SEO for SaaS companies" },
      { ar: "SEO للمنتجات الرقمية", en: "SEO for digital products" },
      { ar: "SEO للعيادات والخدمات الطبية", en: "SEO for clinics and healthcare" },
      { ar: "SEO للعقارات", en: "SEO for real estate" },
      { ar: "SEO للمطاعم والضيافة", en: "SEO for restaurants and hospitality" },
      { ar: "SEO للتعليم والمنصات التعليمية", en: "SEO for education platforms" },
      { ar: "SEO لشركات B2B", en: "SEO for B2B companies" },
      { ar: "SEO للمحامين والخدمات المهنية", en: "SEO for lawyers and professional services" },
      { ar: "اختيار استراتيجية SEO حسب نموذج العمل", en: "Choosing SEO by business model" },
    ],
  },
  {
    id: "seo-migration-recovery",
    labelAr: "هجرة المواقع واستعادة الزيارات",
    labelEn: "Migrations and recovery",
    market: "Global / MENA",
    intent: "commercial",
    keywordAr: "حل مشاكل SEO",
    keywordEn: "SEO recovery",
    supportingAr: ["هجرة الموقع", "انخفاض الزيارات"],
    supportingEn: ["website migration SEO", "traffic drop recovery"],
    topics: [
      { ar: "SEO عند تغيير الدومين", en: "SEO when changing domains" },
      { ar: "خطة هجرة الموقع بدون فقدان الترتيب", en: "A migration plan that protects visibility" },
      { ar: "حل انخفاض الزيارات العضوية", en: "How to diagnose an organic traffic drop" },
      { ar: "استعادة صفحات اختفت من Google", en: "Recovering pages that disappeared from Google" },
      { ar: "Redirects الصحيحة بعد تغيير URL", en: "Correct redirects after URL changes" },
      { ar: "SEO بعد إعادة تصميم الموقع", en: "SEO after a website redesign" },
      { ar: "مراجعة العقوبات والإجراءات اليدوية", en: "Reviewing penalties and manual actions" },
      { ar: "حل مشاكل Duplicate Content", en: "Solving duplicate content issues" },
      { ar: "خطة إنقاذ متجر فقد مبيعاته العضوية", en: "A recovery plan for a store that lost organic sales" },
      { ar: "كيف تفرق بين تحديث Google ومشكلة تقنية؟", en: "Google update vs technical issue" },
    ],
  },
  {
    id: "seo-faq-library",
    labelAr: "أسئلة SEO الشائعة",
    labelEn: "SEO FAQ library",
    market: "Global / MENA",
    intent: "informational",
    keywordAr: "أسئلة السيو الشائعة",
    keywordEn: "SEO FAQ",
    supportingAr: ["أسئلة وأجوبة SEO", "نصائح السيو"],
    supportingEn: ["SEO questions and answers", "SEO advice"],
    topics: [
      { ar: "هل SEO أفضل من Google Ads؟", en: "Is SEO better than Google Ads?" },
      { ar: "كم يحتاج SEO من وقت؟", en: "How long does SEO take?" },
      { ar: "هل يمكن ضمان المركز الأول؟", en: "Can anyone guarantee position one?" },
      { ar: "هل عدد الكلمات مهم في المقال؟", en: "Does word count matter in an article?" },
      { ar: "هل الروابط الخلفية ما زالت مهمة؟", en: "Do backlinks still matter?" },
      { ar: "هل AI مناسب لكتابة مقالات SEO؟", en: "Is AI suitable for writing SEO articles?" },
      { ar: "ما الفرق بين SEO وSEM؟", en: "What is the difference between SEO and SEM?" },
      { ar: "هل كل موقع يحتاج مدونة؟", en: "Does every website need a blog?" },
      { ar: "هل Local SEO مناسب لكل نشاط؟", en: "Is Local SEO right for every business?" },
      { ar: "متى أطلب SEO Audit؟", en: "When should I request an SEO audit?" },
    ],
  },
  {
    id: "seo-case-study-method",
    labelAr: "دراسات حالة ومنهج القياس",
    labelEn: "Case studies and measurement",
    market: "Global / MENA",
    intent: "commercial",
    keywordAr: "نتائج SEO",
    keywordEn: "SEO case studies",
    supportingAr: ["زيادة الزيارات العضوية", "نمو مبيعات المتجر"],
    supportingEn: ["organic traffic growth", "e-commerce sales growth"],
    topics: [
      { ar: "كيف تقرأ دراسة حالة SEO؟", en: "How to read an SEO case study" },
      { ar: "قياس زيادة الزيارات العضوية بصدق", en: "Measuring organic traffic growth honestly" },
      { ar: "ربط ترتيب الكلمات بالإيرادات", en: "Connecting rankings to revenue" },
      { ar: "دراسة حالة SEO لمتجر فاشون", en: "An SEO case study for a fashion store" },
      { ar: "دراسة حالة SEO لموقع SaaS", en: "An SEO case study for a SaaS website" },
      { ar: "دراسة حالة Local SEO لمطعم", en: "A Local SEO case study for a restaurant" },
      { ar: "ما الذي يجعل نتيجة SEO قابلة للتكرار؟", en: "What makes an SEO result repeatable?" },
      { ar: "الفصل بين أثر SEO وأثر القنوات الأخرى", en: "Separating SEO impact from other channels" },
      { ar: "كتابة Case Study بدون ادعاءات مضللة", en: "Writing a case study without misleading claims" },
      { ar: "منهجية عرض الأرقام قبل وبعد", en: "A before-and-after measurement method" },
    ],
  },
];

function makeFaq(cluster: ClusterTemplate, topic: { ar: string; en: string }, lang: RoadmapLanguage): RoadmapFAQ[] {
  if (lang === "ar") {
    return [
      { q: `ما المقصود بموضوع «${topic.ar}»؟`, a: `شرح عملي لموضوع ${topic.ar} ضمن عنقود ${cluster.labelAr}، مع ربطه بنية البحث والهدف التجاري أو التعليمي.` },
      { q: `كيف أطبق ${cluster.keywordAr} على موقعي؟`, a: `ابدأ بخط أساس واضح، ثم راجع الصفحات والجمهور والإشارات المرتبطة بالموضوع قبل ترتيب الأولويات والتنفيذ.` },
      { q: "ما الخطأ الشائع في هذا الموضوع؟", a: "الخطأ الأكثر شيوعًا هو تطبيق تكتيك منفصل عن نية المستخدم أو نشر صفحة مكررة بلا قيمة مستقلة." },
    ];
  }
  return [
    { q: `What does “${topic.en}” mean?`, a: `A practical explanation of ${topic.en} within the ${cluster.labelEn} cluster, connected to search intent and a measurable business or learning goal.` },
    { q: `How do I apply ${cluster.keywordEn} to my website?`, a: "Start with a clear baseline, review the affected pages, audience and signals, then prioritize implementation by impact and effort." },
    { q: "What is the common mistake here?", a: "The common mistake is applying an isolated tactic to the wrong intent or publishing a repetitive page without independent value." },
  ];
}

// The roadmap is exactly 500 bilingual articles: the first 21 priority clusters receive 10 topics each, and the remaining specialist clusters receive 4 topics each. Every cluster remains represented so no keyword family disappears from the plan.
const generatedRoadmap = clusters.flatMap((cluster, clusterIndex) =>
  cluster.topics.slice(0, clusterIndex < 21 ? 10 : 4).flatMap((topic, index) => {
    const n = String(index + 1).padStart(2, "0");
    const pairId = `${cluster.id}-${n}`;
    const arSlug = `${cluster.id}-${n}-ar`;
    const enSlug = `${cluster.id}-${n}-en`;
    const ar: ArticleRoadmapItem = {
      id: `${pairId}-ar`,
      pairId,
      slug: arSlug,
      altSlug: enSlug,
      lang: "ar",
      clusterId: cluster.id,
      clusterLabelAr: cluster.labelAr,
      clusterLabelEn: cluster.labelEn,
      market: cluster.market,
      intent: cluster.intent,
      primaryKeyword: cluster.keywordAr,
      supportingKeywords: [...cluster.supportingAr],
      title: `${cluster.keywordAr}: ${topic.ar}`,
      description: `دليل عملي عن ${topic.ar} ضمن ${cluster.labelAr}، يشرح النية والخطوات والأخطاء وطريقة قياس القيمة بدون حشو كلمات مفتاحية.`,
      faq: makeFaq(cluster, topic, "ar"),
      published: false,
    };
    const en: ArticleRoadmapItem = {
      id: `${pairId}-en`,
      pairId,
      slug: enSlug,
      altSlug: arSlug,
      lang: "en",
      clusterId: cluster.id,
      clusterLabelAr: cluster.labelAr,
      clusterLabelEn: cluster.labelEn,
      market: cluster.market,
      intent: cluster.intent,
      primaryKeyword: cluster.keywordEn,
      supportingKeywords: [...cluster.supportingEn],
      title: `${cluster.keywordEn}: ${topic.en}`,
      description: `A practical guide to ${topic.en} within ${cluster.labelEn}, covering intent, workflow, mistakes and how to measure value without keyword stuffing.`,
      faq: makeFaq(cluster, topic, "en"),
      published: false,
    };
    return [ar, en];
  }),
);

export const articleRoadmap = generatedRoadmap;
export const ARTICLE_ROADMAP_SIZE = articleRoadmap.length;
export const ARTICLE_ROADMAP_PAIRS = articleRoadmap.filter((item) => item.lang === "ar").length;
export const ARTICLE_ROADMAP_CLUSTERS = clusters.map(({ id, labelAr, labelEn, market, intent }) => ({ id, labelAr, labelEn, market, intent }));

export function getRoadmapArticle(slug: string) {
  return articleRoadmap.find((article) => article.slug === slug);
}

export function getRoadmapClusterCount(clusterId: string) {
  return articleRoadmap.filter((article) => article.clusterId === clusterId).length;
}
