export type InternationalPlanItem = {
  id: string;
  cluster: string;
  market: "US + Europe" | "US" | "Europe";
  intent: "Informational" | "Commercial investigation" | "Transactional";
  primaryKeyword: string;
  title: string;
  supportingKeywords: string[];
  faqs: string[];
  internalLinks: string[];
};

const commonLinks = ["/international-seo", "/seo-services", "/seo-expert", "/keyword-research", "/content-seo"];
const technicalLinks = [...commonLinks, "/international-seo", "/blog/technical-seo-audit-en"];
const contentLinks = [...commonLinks, "/blog/seo-content-brief-en", "/content-seo"];

const topics: Omit<InternationalPlanItem, "id">[] = [
  // International foundations
  { cluster: "International SEO foundations", market: "US + Europe", intent: "Informational", primaryKeyword: "international SEO", title: "International SEO: How to Build a Search Strategy Across the US and Europe", supportingKeywords: ["global SEO strategy", "international search visibility", "multiregional SEO"], faqs: ["What is international SEO?", "Can one English page target the US and Europe?"], internalLinks: commonLinks },
  { cluster: "International SEO foundations", market: "US + Europe", intent: "Commercial investigation", primaryKeyword: "international SEO consultant", title: "What to Look for in an International SEO Consultant", supportingKeywords: ["international SEO services", "global SEO consultant", "multilingual SEO partner"], faqs: ["What should an international SEO consultant audit first?", "Do you need separate country pages?"], internalLinks: commonLinks },
  { cluster: "International SEO foundations", market: "US + Europe", intent: "Informational", primaryKeyword: "multilingual SEO", title: "Multilingual SEO Without Losing the Meaning of Your Offer", supportingKeywords: ["multilingual website SEO", "SEO translation", "localized content"], faqs: ["Is translation enough for multilingual SEO?", "How should language versions link to one another?"], internalLinks: technicalLinks },
  { cluster: "International SEO foundations", market: "US + Europe", intent: "Informational", primaryKeyword: "international keyword research", title: "International Keyword Research: Comparing Search Intent Across Markets", supportingKeywords: ["global keyword research", "country keyword research", "search intent by market"], faqs: ["Should the same keyword be translated for every country?", "How do you compare SERPs across markets?"], internalLinks: ["/international-seo", "/keyword-research", "/content-seo", "/blog/seo-keyword-mapping-en"] },
  { cluster: "International SEO foundations", market: "US + Europe", intent: "Informational", primaryKeyword: "SEO localization", title: "SEO Localization: What Changes Beyond the Translation", supportingKeywords: ["website localization SEO", "localized keyword research", "market localization"], faqs: ["What elements should be localized?", "When is a localized page worth creating?"], internalLinks: contentLinks },
  { cluster: "International SEO foundations", market: "US + Europe", intent: "Informational", primaryKeyword: "international SEO strategy", title: "A Practical International SEO Strategy for a Remote-First Business", supportingKeywords: ["global SEO roadmap", "international content strategy", "remote SEO services"], faqs: ["Which market should a small business start with?", "How long should an international SEO test run?"], internalLinks: commonLinks },
  { cluster: "International SEO foundations", market: "US + Europe", intent: "Commercial investigation", primaryKeyword: "international SEO services", title: "International SEO Services: Scope, Process and Decision Points", supportingKeywords: ["global SEO services", "multiregional SEO services", "international SEO agency"], faqs: ["What does an international SEO engagement include?", "How is progress measured by market?"], internalLinks: commonLinks },
  { cluster: "International SEO foundations", market: "US + Europe", intent: "Informational", primaryKeyword: "country targeting SEO", title: "Country Targeting in SEO: When a Market Needs Its Own Page", supportingKeywords: ["country-specific SEO", "regional SEO pages", "market targeting"], faqs: ["Should every country have a separate URL?", "What makes a country page genuinely useful?"], internalLinks: technicalLinks },
  { cluster: "International SEO foundations", market: "US + Europe", intent: "Informational", primaryKeyword: "US vs UK SEO", title: "US vs UK SEO: Search Language, Intent and Content Differences", supportingKeywords: ["American vs British search terms", "UK SEO strategy", "English market SEO"], faqs: ["Are US and UK keywords always different?", "Should a brand use US or UK spelling?"], internalLinks: ["/international-seo", "/keyword-research", "/content-seo", "/blog/seo-content-brief-en"] },
  { cluster: "International SEO foundations", market: "US + Europe", intent: "Informational", primaryKeyword: "European SEO strategy", title: "European SEO Strategy: Planning for Multiple Languages and Markets", supportingKeywords: ["SEO in Europe", "European search marketing", "multilingual Europe SEO"], faqs: ["Does Europe require a page for every country?", "How should language and country targeting be separated?"], internalLinks: technicalLinks },

  // US market
  { cluster: "US market playbooks", market: "US", intent: "Commercial investigation", primaryKeyword: "SEO strategy for US businesses", title: "SEO Strategy for US Businesses: From Search Demand to Qualified Leads", supportingKeywords: ["US business SEO", "American market SEO", "lead generation SEO US"], faqs: ["What makes a US SEO strategy different?", "How do you qualify US search demand?"], internalLinks: commonLinks },
  { cluster: "US market playbooks", market: "US", intent: "Transactional", primaryKeyword: "US SEO consultant", title: "Choosing a US SEO Consultant for a Service or B2B Company", supportingKeywords: ["SEO consultant USA", "US SEO expert", "remote SEO consultant"], faqs: ["Can a remote consultant support a US company?", "What should a consultant report each month?"], internalLinks: ["/international-seo", "/seo-expert", "/seo-company", "/seo-services"] },
  { cluster: "US market playbooks", market: "US", intent: "Commercial investigation", primaryKeyword: "B2B SEO strategy US", title: "B2B SEO in the US: Building Demand Beyond High-Volume Keywords", supportingKeywords: ["US B2B SEO", "enterprise lead generation SEO", "B2B content strategy"], faqs: ["How long is a US B2B buying cycle?", "Which pages support B2B pipeline?"], internalLinks: ["/international-seo", "/seo-services", "/content-seo", "/growth-marketing"] },
  { cluster: "US market playbooks", market: "US", intent: "Commercial investigation", primaryKeyword: "SaaS SEO strategy US", title: "SaaS SEO for the US Market: Product, Problem and Comparison Pages", supportingKeywords: ["US SaaS SEO", "software SEO strategy", "SaaS content marketing"], faqs: ["Which SaaS pages should rank first?", "How do you connect SEO to product-qualified leads?"], internalLinks: ["/international-seo", "/content-seo", "/keyword-research", "/growth-marketing"] },
  { cluster: "US market playbooks", market: "US", intent: "Commercial investigation", primaryKeyword: "ecommerce SEO USA", title: "E-commerce SEO for the US: Category Architecture, Content and Conversion", supportingKeywords: ["US ecommerce SEO", "product page SEO USA", "online store SEO"], faqs: ["How should US category pages be structured?", "Which e-commerce SEO metrics matter beyond traffic?"], internalLinks: ["/international-seo", "/seo-services", "/content-seo", "/blog/schema-markup-seo-en"] },
  { cluster: "US market playbooks", market: "US", intent: "Informational", primaryKeyword: "US keyword research", title: "US Keyword Research: Finding Commercial Intent in American Search Results", supportingKeywords: ["keyword research USA", "US search intent", "American keyword analysis"], faqs: ["How do you validate a keyword for the US?", "Should volume decide the target keyword?"], internalLinks: ["/international-seo", "/keyword-research", "/blog/seo-keyword-mapping-en"] },
  { cluster: "US market playbooks", market: "US", intent: "Informational", primaryKeyword: "SEO content for US audience", title: "Writing SEO Content for a US Audience Without Sounding Generic", supportingKeywords: ["US audience content", "American English SEO writing", "content localization USA"], faqs: ["What makes content feel relevant to US readers?", "Should a remote team use American spelling?"], internalLinks: contentLinks },
  { cluster: "US market playbooks", market: "US", intent: "Commercial investigation", primaryKeyword: "US local SEO strategy", title: "US Local SEO Strategy for Businesses That Serve More Than One City", supportingKeywords: ["multi-location local SEO USA", "US service area SEO", "local landing pages"], faqs: ["When should a business create city pages?", "How do service-area businesses avoid thin local pages?"], internalLinks: ["/international-seo", "/seo-services", "/international-seo"] },
  { cluster: "US market playbooks", market: "US", intent: "Informational", primaryKeyword: "US SEO audit", title: "A US SEO Audit Checklist for Service, B2B and SaaS Websites", supportingKeywords: ["SEO audit USA", "technical SEO audit US", "content audit checklist"], faqs: ["What should a US SEO audit include?", "How do you prioritize audit findings?"], internalLinks: ["/international-seo", "/blog/technical-seo-audit-en", "/seo-services"] },
  { cluster: "US market playbooks", market: "US", intent: "Informational", primaryKeyword: "SEO for US startups", title: "SEO for US Startups: A Lean Roadmap from Positioning to Organic Demand", supportingKeywords: ["startup SEO USA", "early-stage SEO", "startup content strategy"], faqs: ["When should a startup invest in SEO?", "Which pages matter before publishing a blog?"], internalLinks: ["/international-seo", "/keyword-research", "/content-seo", "/growth-marketing"] },
  { cluster: "US market playbooks", market: "US", intent: "Commercial investigation", primaryKeyword: "SEO for US professional services", title: "SEO for US Professional Services: Turning Expertise into Searchable Offers", supportingKeywords: ["professional services SEO USA", "law firm SEO strategy", "consulting SEO"], faqs: ["How can professional services prove expertise?", "Which service pages deserve priority?"], internalLinks: ["/international-seo", "/seo-services", "/content-seo", "/seo-expert"] },
  { cluster: "US market playbooks", market: "US", intent: "Informational", primaryKeyword: "US SEO reporting", title: "US SEO Reporting: How to Separate Visibility from Revenue", supportingKeywords: ["SEO reporting USA", "organic leads reporting", "Search Console by country"], faqs: ["Which US SEO metrics belong in a report?", "How do you connect rankings to qualified leads?"], internalLinks: ["/international-seo", "/seo-services", "/seo-services"] },

  // Europe and UK
  { cluster: "European market playbooks", market: "Europe", intent: "Commercial investigation", primaryKeyword: "SEO services Europe", title: "SEO Services for European Markets: A Practical Multilingual Framework", supportingKeywords: ["European SEO services", "SEO agency Europe", "multilingual SEO services"], faqs: ["How do European SEO projects handle multiple languages?", "Can one team manage several markets?"], internalLinks: commonLinks },
  { cluster: "European market playbooks", market: "Europe", intent: "Informational", primaryKeyword: "UK SEO strategy", title: "UK SEO Strategy: Search Intent, Content and Technical Priorities", supportingKeywords: ["SEO UK", "British SEO strategy", "UK keyword research"], faqs: ["What differs between UK and US SEO?", "How should British terminology be researched?"], internalLinks: ["/international-seo", "/keyword-research", "/content-seo", "/blog/seo-content-brief-en"] },
  { cluster: "European market playbooks", market: "Europe", intent: "Commercial investigation", primaryKeyword: "UK SEO consultant", title: "What a UK SEO Consultant Should Explain Before the First Campaign", supportingKeywords: ["SEO consultant UK", "UK SEO expert", "remote SEO services UK"], faqs: ["What questions should a UK buyer ask?", "How should monthly SEO work be documented?"], internalLinks: ["/international-seo", "/seo-expert", "/seo-services", "/seo-company"] },
  { cluster: "European market playbooks", market: "Europe", intent: "Informational", primaryKeyword: "Ireland SEO strategy", title: "Ireland SEO Strategy: Serving a Local Market with International Ambition", supportingKeywords: ["Irish SEO", "Ireland keyword research", "SEO for Irish businesses"], faqs: ["Should Irish businesses target the UK too?", "What local signals should be reviewed?"], internalLinks: ["/international-seo", "/keyword-research", "/content-seo"] },
  { cluster: "European market playbooks", market: "Europe", intent: "Informational", primaryKeyword: "SEO for European SaaS", title: "SEO for European SaaS: From English Foundation to Market Localization", supportingKeywords: ["European SaaS SEO", "multilingual SaaS marketing", "SaaS SEO Europe"], faqs: ["Which language should a European SaaS launch first?", "How should product pages be localized?"], internalLinks: ["/international-seo", "/content-seo", "/keyword-research", "/growth-marketing"] },
  { cluster: "European market playbooks", market: "Europe", intent: "Commercial investigation", primaryKeyword: "European ecommerce SEO", title: "European E-commerce SEO: Managing Languages, Markets and Product Demand", supportingKeywords: ["ecommerce SEO Europe", "multilingual product SEO", "European category pages"], faqs: ["How should product feeds and content differ by market?", "When is a country-specific store needed?"], internalLinks: ["/international-seo", "/seo-services", "/content-seo", "/blog/schema-markup-seo-en"] },
  { cluster: "European market playbooks", market: "Europe", intent: "Informational", primaryKeyword: "SEO in Germany for English websites", title: "SEO in Germany for English Websites: When Translation and Localization Are Needed", supportingKeywords: ["Germany SEO strategy", "English website Germany", "German market SEO"], faqs: ["Can an English page rank in Germany?", "When should German content be commissioned?"], internalLinks: ["/international-seo", "/keyword-research", "/content-seo"] },
  { cluster: "European market playbooks", market: "Europe", intent: "Informational", primaryKeyword: "SEO in France for international brands", title: "SEO in France for International Brands: A Localization Decision Guide", supportingKeywords: ["France SEO strategy", "French SEO localization", "international SEO France"], faqs: ["Is French translation enough for SEO?", "How can a brand validate French search intent?"], internalLinks: ["/international-seo", "/keyword-research", "/content-seo"] },

  // Technical international SEO
  { cluster: "International technical SEO", market: "US + Europe", intent: "Informational", primaryKeyword: "hreflang SEO guide", title: "Hreflang SEO: A Clear Implementation Guide for Language and Region Variants", supportingKeywords: ["hreflang tags", "language targeting SEO", "regional SEO signals"], faqs: ["Should a page reference itself in hreflang?", "What is x-default used for?"], internalLinks: technicalLinks },
  { cluster: "International technical SEO", market: "US + Europe", intent: "Informational", primaryKeyword: "hreflang errors", title: "Common Hreflang Errors and How to Diagnose Them", supportingKeywords: ["hreflang troubleshooting", "missing return tags", "invalid language codes"], faqs: ["Why are hreflang tags ignored?", "How can return tags be checked?"], internalLinks: technicalLinks },
  { cluster: "International technical SEO", market: "US + Europe", intent: "Informational", primaryKeyword: "international URL structure", title: "International URL Structure: Subfolders, Subdomains or Country Domains?", supportingKeywords: ["multilingual URL structure", "ccTLD vs subfolder", "global website architecture"], faqs: ["Which URL structure is easiest to maintain?", "Does a country domain guarantee local rankings?"], internalLinks: technicalLinks },
  { cluster: "International technical SEO", market: "US + Europe", intent: "Informational", primaryKeyword: "multilingual website architecture", title: "Multilingual Website Architecture That Keeps Content and Signals Organized", supportingKeywords: ["international site architecture", "language folders SEO", "multilingual navigation"], faqs: ["How should language folders be named?", "Should language selectors be crawlable?"], internalLinks: technicalLinks },
  { cluster: "International technical SEO", market: "US + Europe", intent: "Informational", primaryKeyword: "international SEO duplicate content", title: "International SEO and Duplicate Content: What Is Actually a Problem?", supportingKeywords: ["localized duplicate content", "canonical international SEO", "similar country pages"], faqs: ["Are translated pages duplicates?", "Can similar English pages compete with each other?"], internalLinks: technicalLinks },
  { cluster: "International technical SEO", market: "US + Europe", intent: "Informational", primaryKeyword: "international SEO canonical tags", title: "Canonical Tags for International SEO: Avoiding the Wrong Consolidation", supportingKeywords: ["canonical multilingual pages", "regional canonical SEO", "SEO duplicate signals"], faqs: ["Should every language page canonicalize to English?", "How do canonical and hreflang work together?"], internalLinks: technicalLinks },
  { cluster: "International technical SEO", market: "US + Europe", intent: "Informational", primaryKeyword: "international SEO sitemap", title: "International SEO Sitemaps: Organizing URLs for Language and Market Variants", supportingKeywords: ["hreflang sitemap", "multilingual XML sitemap", "international indexing"], faqs: ["Can hreflang live in a sitemap?", "Should every locale URL be included?"], internalLinks: technicalLinks },
  { cluster: "International technical SEO", market: "US + Europe", intent: "Informational", primaryKeyword: "international SEO redirects", title: "International SEO Redirects: Why Automatic Country Redirection Can Go Wrong", supportingKeywords: ["geo redirects SEO", "language redirect issues", "international crawlability"], faqs: ["Should users be redirected by IP?", "How can country suggestions remain user controlled?"], internalLinks: technicalLinks },
  { cluster: "International technical SEO", market: "US + Europe", intent: "Commercial investigation", primaryKeyword: "international SEO audit checklist", title: "International SEO Audit Checklist for US and European Expansion", supportingKeywords: ["multilingual SEO audit", "global technical SEO audit", "international indexing audit"], faqs: ["What is checked in an international SEO audit?", "Which issues should be fixed before localization?"], internalLinks: ["/international-seo", "/blog/technical-seo-audit-en", "/seo-services", "/keyword-research"] },
  { cluster: "International technical SEO", market: "US + Europe", intent: "Informational", primaryKeyword: "country and language SEO targeting", title: "Language vs Country Targeting in SEO: A Decision Framework", supportingKeywords: ["language targeting", "country targeting", "locale SEO"], faqs: ["Is en-US different from en-GB in every project?", "When is a generic English page enough?"], internalLinks: technicalLinks },

  // Content, AEO and demand
  { cluster: "International content and demand", market: "US + Europe", intent: "Commercial investigation", primaryKeyword: "international content strategy", title: "International Content Strategy: Building One System for Multiple Markets", supportingKeywords: ["global content strategy", "multilingual content planning", "market content clusters"], faqs: ["Which content should be global?", "How do you prevent duplicate editorial calendars?"], internalLinks: contentLinks },
  { cluster: "International content and demand", market: "US + Europe", intent: "Informational", primaryKeyword: "content localization SEO", title: "Content Localization for SEO: Briefs, Examples and Editorial QA", supportingKeywords: ["localized SEO content", "SEO translation workflow", "editorial localization"], faqs: ["Who should review localized content?", "What belongs in a localization brief?"], internalLinks: contentLinks },
  { cluster: "International content and demand", market: "US + Europe", intent: "Informational", primaryKeyword: "international topic clusters", title: "International Topic Clusters: Connecting Global Themes to Local Intent", supportingKeywords: ["global topic clusters", "multilingual content hubs", "international content architecture"], faqs: ["Can one pillar page support multiple markets?", "How should local articles link to the pillar?"], internalLinks: contentLinks },
  { cluster: "International content and demand", market: "US + Europe", intent: "Informational", primaryKeyword: "AEO for international brands", title: "AEO for International Brands: Making Answers Clear Across Markets", supportingKeywords: ["answer engine optimization global", "international FAQ SEO", "multilingual AEO"], faqs: ["Should FAQs be translated or rewritten?", "How can answer content reflect local terminology?"], internalLinks: ["/international-seo", "/content-seo", "/seo-geo-eli5", "/keyword-research"] },
  { cluster: "International content and demand", market: "US + Europe", intent: "Informational", primaryKeyword: "GEO for global SEO", title: "GEO and International SEO: Helping AI Systems Understand Market Context", supportingKeywords: ["generative engine optimization global", "AI search international", "entity context SEO"], faqs: ["What market context should a page make clear?", "Does GEO replace technical SEO?"], internalLinks: ["/international-seo", "/seo-geo-eli5", "/content-seo", "/seo-services"] },
  { cluster: "International content and demand", market: "US + Europe", intent: "Commercial investigation", primaryKeyword: "international SEO content writing", title: "International SEO Content Writing: A Brief That Protects Meaning and Intent", supportingKeywords: ["global SEO copywriting", "multilingual SEO writing", "market-specific content"], faqs: ["Can one writer create every market version?", "How should content quality be reviewed?"], internalLinks: contentLinks },
  { cluster: "International content and demand", market: "US + Europe", intent: "Informational", primaryKeyword: "US and Europe search intent", title: "US and European Search Intent: How to Read the SERP Before Writing", supportingKeywords: ["SERP analysis by country", "international search intent", "market intent research"], faqs: ["What should be compared in two SERPs?", "Can the same query have different commercial intent?"], internalLinks: ["/international-seo", "/keyword-research", "/content-seo", "/blog/seo-keyword-mapping-en"] },
  { cluster: "International content and demand", market: "US + Europe", intent: "Informational", primaryKeyword: "international SEO internal linking", title: "Internal Linking for International SEO: Connecting Markets Without Confusion", supportingKeywords: ["multilingual internal links", "international site navigation", "hreflang internal linking"], faqs: ["Should English pages link to every language?", "How can anchors stay natural across locales?"], internalLinks: ["/international-seo", "/keyword-research", "/content-seo", "/blog/internal-linking-seo-en"] },
  { cluster: "International content and demand", market: "US + Europe", intent: "Commercial investigation", primaryKeyword: "international SEO for B2B", title: "International B2B SEO: Mapping Long Buying Cycles Across the US and Europe", supportingKeywords: ["global B2B SEO", "international demand generation", "B2B localization"], faqs: ["How should B2B pages reflect market differences?", "Which international leads are worth measuring?"], internalLinks: ["/international-seo", "/growth-marketing", "/seo-services", "/content-seo"] },
  { cluster: "International content and demand", market: "US + Europe", intent: "Commercial investigation", primaryKeyword: "international SEO for service businesses", title: "International SEO for Service Businesses: Proving Relevance Without Local Offices", supportingKeywords: ["global service business SEO", "remote SEO services", "service area international SEO"], faqs: ["Can a service business target another country remotely?", "How should trust be communicated without local presence?"], internalLinks: ["/international-seo", "/seo-expert", "/seo-services", "/content-seo"] },
  { cluster: "International content and demand", market: "US + Europe", intent: "Informational", primaryKeyword: "international SEO measurement", title: "Measuring International SEO: A Dashboard for Markets, Pages and Leads", supportingKeywords: ["global SEO KPIs", "country SEO reporting", "international organic conversions"], faqs: ["Which metrics should be separated by country?", "How do you avoid mixing markets in one report?"], internalLinks: ["/international-seo", "/seo-services", "/seo-services"] },
  { cluster: "International content and demand", market: "US + Europe", intent: "Commercial investigation", primaryKeyword: "international SEO roadmap", title: "A 90-Day International SEO Roadmap for a US or European Expansion", supportingKeywords: ["global SEO roadmap", "international SEO plan", "market expansion SEO"], faqs: ["What can be completed in the first 90 days?", "When should a second market be added?"], internalLinks: commonLinks },
  { cluster: "International content and demand", market: "US + Europe", intent: "Informational", primaryKeyword: "SEO for global brands", title: "SEO for Global Brands: Governance, Local Relevance and Consistent Quality", supportingKeywords: ["enterprise international SEO", "global website governance", "international SEO workflow"], faqs: ["Who owns global and local SEO decisions?", "How can quality stay consistent across markets?"], internalLinks: ["/international-seo", "/seo-company", "/seo-services", "/content-seo"] },

  // Trust, conversion and operations
  { cluster: "International growth operations", market: "US + Europe", intent: "Commercial investigation", primaryKeyword: "international SEO case study framework", title: "How to Present an International SEO Case Study Without Overclaiming", supportingKeywords: ["SEO case study structure", "international SEO proof", "transparent SEO reporting"], faqs: ["Which details make a case study credible?", "How should different properties and periods be separated?"], internalLinks: ["/international-seo", "/content-seo", "/seo-services"] },
  { cluster: "International growth operations", market: "US + Europe", intent: "Informational", primaryKeyword: "international SEO conversion optimization", title: "International SEO and Conversion Paths: Adapting the Next Step by Market", supportingKeywords: ["global CRO SEO", "localized CTAs", "international lead generation"], faqs: ["Should CTAs differ between the US and Europe?", "How can a remote offer build trust?"], internalLinks: ["/international-seo", "/growth-marketing", "/content-seo", "/seo-services"] },
  { cluster: "International growth operations", market: "US + Europe", intent: "Informational", primaryKeyword: "international SEO trust signals", title: "Trust Signals for International SEO: What to Show When You Work Remotely", supportingKeywords: ["global website trust", "remote service credibility", "international E-E-A-T"], faqs: ["How can a remote provider explain its experience?", "Which claims should never be made without evidence?"], internalLinks: ["/international-seo", "/seo-expert", "/seo-company", "/blog/seo-for-service-businesses-en"] },
  { cluster: "International growth operations", market: "US + Europe", intent: "Informational", primaryKeyword: "international SEO content calendar", title: "International SEO Content Calendar: Sequencing Shared and Local Topics", supportingKeywords: ["global editorial calendar", "US Europe content plan", "localized publishing"], faqs: ["Which articles should be published first?", "How do you avoid translating a weak topic?"], internalLinks: contentLinks },
  { cluster: "International growth operations", market: "US + Europe", intent: "Informational", primaryKeyword: "international SEO team workflow", title: "International SEO Workflow: Research, Writing, Technical QA and Reporting", supportingKeywords: ["global SEO operations", "international content workflow", "SEO localization process"], faqs: ["Who reviews technical and language quality?", "How should tasks be handed between specialists?"], internalLinks: ["/international-seo", "/keyword-research", "/content-seo", "/seo-services"] },
  { cluster: "International growth operations", market: "US + Europe", intent: "Commercial investigation", primaryKeyword: "international SEO for digital products", title: "International SEO for Digital Products: Matching Product Language to Market Demand", supportingKeywords: ["global digital product SEO", "SaaS localization SEO", "product-led SEO global"], faqs: ["How do product-led pages differ by market?", "Which market should a digital product validate first?"], internalLinks: ["/international-seo", "/keyword-research", "/content-seo", "/growth-marketing"] },
  { cluster: "International growth operations", market: "US + Europe", intent: "Informational", primaryKeyword: "international SEO migration checklist", title: "International SEO Migration Checklist for Adding Languages or Markets", supportingKeywords: ["multilingual site migration", "international URL migration", "hreflang migration"], faqs: ["What should be tested before launch?", "How can traffic loss be diagnosed after migration?"], internalLinks: ["/international-seo", "/blog/technical-seo-audit-en", "/seo-services"] },
  { cluster: "International growth operations", market: "US + Europe", intent: "Informational", primaryKeyword: "international SEO competitor analysis", title: "International SEO Competitor Analysis: Compare the Right Pages and Markets", supportingKeywords: ["global SEO competitors", "country SERP competitors", "international content gap"], faqs: ["Should competitors be compared by country?", "What can a competitor gap reveal?"], internalLinks: ["/international-seo", "/keyword-research", "/seo-services"] },
  { cluster: "International growth operations", market: "US + Europe", intent: "Commercial investigation", primaryKeyword: "international SEO pricing", title: "International SEO Pricing: What Changes When More Markets Are Included", supportingKeywords: ["global SEO cost", "multilingual SEO pricing", "international SEO retainer"], faqs: ["What affects international SEO cost?", "Is adding a language the same as adding a country?"], internalLinks: ["/international-seo", "/seo-services", "/seo-company"] },
  { cluster: "International growth operations", market: "US + Europe", intent: "Transactional", primaryKeyword: "international SEO audit service", title: "International SEO Audit Service for US and European Expansion", supportingKeywords: ["multilingual SEO audit service", "global SEO technical audit", "international SEO consultant"], faqs: ["What will the audit deliver?", "Can an audit recommend not creating country pages?"], internalLinks: ["/international-seo", "/seo-services", "/seo-expert", "/blog/technical-seo-audit-en"] },
  { cluster: "International growth operations", market: "US + Europe", intent: "Transactional", primaryKeyword: "international SEO strategy service", title: "International SEO Strategy Service for Remote-First Brands", supportingKeywords: ["global SEO strategy service", "US Europe SEO consultant", "multilingual growth strategy"], faqs: ["What is needed to start a strategy?", "How will the first market be selected?"], internalLinks: commonLinks },
];

export const INTERNATIONAL_ARTICLE_PLAN: InternationalPlanItem[] = topics.map((topic, index) => ({
  ...topic,
  id: `international-seo-${String(index + 1).padStart(2, "0")}`,
}));

export const INTERNATIONAL_ARTICLE_PLAN_SIZE = INTERNATIONAL_ARTICLE_PLAN.length;
export const INTERNATIONAL_ARTICLE_PLAN_CLUSTERS = [...new Set(INTERNATIONAL_ARTICLE_PLAN.map((item) => item.cluster))];
