import type { Check } from "./seo-audit.server";
export type Lang = "ar" | "en";
type D = Check["data"];
type Entry = { group: "index" | "content" | "links" | "tech" | "speed" | "data" | "trust"; t: string; why: string; pass: (d: D) => string; warn?: (d: D) => string; fail?: (d: D) => string };

const en: Record<string, Entry> = {
  https: { group: "tech", t: "HTTPS", why: "Browsers flag non-secure stores and Google prefers secure pages.", pass: () => "The page is served over HTTPS.", fail: () => "The page does not end up on HTTPS. Redirect all traffic to the HTTPS version." },
  status: { group: "index", t: "Page response", why: "Pages that do not return 200 cannot rank.", pass: () => "The page returns HTTP 200.", warn: (d) => `The page returns HTTP ${d.code}.`, fail: (d) => `The page returns HTTP ${d.code}, so search engines will not index it.` },
  redirects: { group: "speed", t: "Redirect chain", why: "Each redirect adds delay and can dilute link value.", pass: (d) => `${d.hops} redirect before the final page.`, warn: (d) => `${d.hops} redirects before the final page. Point links straight to the final URL.`, fail: (d) => `${d.hops} redirects in a row. Shorten the chain to one hop.` },
  title: { group: "content", t: "Title tag", why: "The title is the strongest on-page signal and the headline in search results.", pass: (d) => `Present, ${d.length} characters: "${d.value}"`, warn: (d) => `Present but ${d.length} characters (${Number(d.length) < 25 ? "too short to describe the page" : "likely truncated in results"}): "${d.value}"`, fail: () => "No title tag found. Add a unique title with the main keyword and brand." },
  description: { group: "content", t: "Meta description", why: "It controls the snippet shoppers read before clicking.", pass: (d) => `Present, ${d.length} characters.`, warn: (d) => `Present but ${d.length} characters. Aim for roughly 70 to 160.`, fail: () => "No meta description found. Search engines will pick random page text instead." },
  h1: { group: "content", t: "Main heading (H1)", why: "A single clear H1 tells search engines what the page is about.", pass: (d) => `One H1: "${d.value}"`, warn: (d) => `${d.count} H1 tags found. Keep one main heading per page.`, fail: () => "No H1 found in the page HTML." },
  h2: { group: "content", t: "Subheadings (H2)", why: "Subheadings structure the page for readers and crawlers.", pass: (d) => `${d.count} H2 headings found.`, warn: () => "No H2 headings found. Break the content into sections." },
  indexable: { group: "index", t: "Indexing directives we could read", why: "A noindex directive or a robots.txt block can keep a page out of Google. This is limited to the directives visible to this tool, not a full indexing verdict: only Google Search Console can confirm whether a page is indexed.", pass: (d) => d.robotsState === "ok" ? "No noindex directive and no robots.txt block for this URL were found." : "No noindex directive was found. robots.txt could not be read, so crawl rules are unconfirmed.", warn: () => "No noindex directive was found, but robots.txt could not be fetched reliably (server error), so crawl rules are unconfirmed.", fail: (d) => d.noindex ? "A noindex (or none) directive was found in the meta tags or headers, which asks search engines to keep this page out of results." : "robots.txt disallows this URL for Googlebot or all crawlers." },
  canonical: { group: "index", t: "Canonical URL", why: "Canonical tags prevent duplicate-content problems from filters and parameters.", pass: () => "A canonical URL is declared.", warn: (d) => d.other ? "The canonical points to a different domain. Confirm that is intended." : "No canonical tag found. Add one to avoid duplicate versions of the page." },
  viewport: { group: "tech", t: "Mobile viewport", why: "Most store traffic is mobile and Google indexes the mobile version first.", pass: () => "A responsive viewport tag is present.", fail: () => "No width=device-width viewport tag. The page may render as a zoomed-out desktop page on phones." },
  htmlLang: { group: "tech", t: "Language attribute", why: "The lang attribute helps search engines serve the page to the right audience.", pass: () => "The html lang attribute is set.", warn: () => "No lang attribute on the html tag." },
  robots: { group: "index", t: "robots.txt", why: "robots.txt guides crawlers and should point to your sitemap.", pass: () => "robots.txt exists and lists a sitemap.", warn: (d) => d.found ? "robots.txt exists but does not list your sitemap." : "No robots.txt found at the site root." },
  sitemap: { group: "index", t: "XML sitemap", why: "A sitemap helps Google find every product and collection page.", pass: (d) => `Sitemap found with ${d.entries} entries listed.`, warn: () => "No readable XML sitemap found at /sitemap.xml or in robots.txt." },
  speed: { group: "speed", t: "Server response time", why: "Slow responses hurt rankings and sales. This is the time our server needed to receive the page HTML, not a full browser load test.", pass: (d) => `The HTML arrived in ${d.ms} ms.`, warn: (d) => `The HTML took ${d.ms} ms to arrive.`, fail: (d) => `The HTML took ${d.ms} ms to arrive, which is slow.` },
  compression: { group: "speed", t: "Compression", why: "Compressed responses load faster on mobile networks.", pass: (d) => `Responses use ${d.encoding} compression.`, warn: () => "The HTML is served without gzip or Brotli compression." },
  htmlSize: { group: "speed", t: "HTML size", why: "Very large pages are slower to download and parse.", pass: (d) => `The HTML is about ${d.kb} KB.`, warn: (d) => `The HTML is about ${d.kb} KB, which is heavy.`, fail: (d) => `The HTML is ${d.truncated ? "over" : "about"} ${d.kb} KB, which is very heavy.` },
  scripts: { group: "speed", t: "External scripts", why: "Many third-party scripts slow rendering and hurt Core Web Vitals.", pass: (d) => `${d.count} external script files in the page.`, warn: (d) => `${d.count} external script files. Remove unused apps and trackers.`, fail: (d) => `${d.count} external script files, which is a lot. Audit and remove what you do not use.` },
  imageAlt: { group: "content", t: "Image alt text", why: "Alt text feeds image search and accessibility.", pass: (d) => `All ${d.total} images have alt text.`, warn: (d) => `${d.missing} of ${d.total} images have no alt text.`, fail: (d) => `${d.missing} of ${d.total} images have no alt text.` },
  schema: { group: "data", t: "Structured data (JSON-LD)", why: "Structured data makes you eligible for rich results.", pass: (d) => `Found: ${d.types}.`, warn: () => "No JSON-LD structured data found on this page." },
  productSchema: { group: "data", t: "Product markup", why: "Per Google's product structured data documentation, Product markup with name, image, price and currency can make a product page eligible for product and merchant listing results. Recommended extras: availability, brand, sku/gtin, ratings.", pass: (d) => d.recommended ? `Product markup found with the core fields. Recommended extras missing: ${d.recommended}.` : "Product markup found with the core fields and recommended extras.", warn: (d) => d.missing === "Product" ? "This URL looks like a product page but no Product markup was found." : `Product markup found. Recommended extras missing: ${d.recommended}.`, fail: (d) => `Product markup found but required fields are missing: ${d.missing}.` },
  orgSchema: { group: "data", t: "Organization / site markup", why: "Helps Google understand who runs the store.", pass: () => "Organization, Store or WebSite markup found.", warn: () => "No Organization or WebSite markup found." },
  openGraph: { group: "data", t: "Social sharing tags", why: "Open Graph tags control how links look when shared.", pass: () => "og:title, og:description and og:image are set.", warn: (d) => `Missing: ${d.missing}.`, fail: () => "No Open Graph tags found." },
  content: { group: "content", t: "Visible text", why: "Editorial prompt, not a ranking rule: Google asks for helpful, people-first content, and there is no minimum word count. A very low count can also mean the content loads through JavaScript, which this tool does not run.", pass: (d) => `About ${d.words} words of text in the page HTML.`, warn: (d) => `About ${d.words} words of text in the page HTML. Consider whether the page answers a shopper's questions.` },
  internalLinks: { group: "content", t: "Internal links", why: "Internal links spread authority and help crawlers discover pages.", pass: (d) => `${d.count} internal links found.`, warn: (d) => `Only ${d.count} internal links found.` },
};

const ar: Record<string, Entry> = {
  https: { group: "tech", t: "HTTPS", why: "المتصفحات تحذّر من المتاجر غير الآمنة وجوجل يفضّل الصفحات الآمنة.", pass: () => "الصفحة تعمل عبر HTTPS.", fail: () => "الصفحة لا تنتهي على HTTPS. حوّل كل الزيارات إلى نسخة HTTPS." },
  status: { group: "index", t: "استجابة الصفحة", why: "الصفحات التي لا ترجع 200 لا يمكنها الظهور في النتائج.", pass: () => "الصفحة ترجع كود 200.", warn: (d) => `الصفحة ترجع كود ${d.code}.`, fail: (d) => `الصفحة ترجع كود ${d.code}، وبالتالي لن تُؤرشف في جوجل.` },
  redirects: { group: "speed", t: "سلسلة التحويلات", why: "كل تحويل يضيف تأخيرًا وقد يُضعف قيمة الروابط.", pass: (d) => `${d.hops} تحويل قبل الصفحة النهائية.`, warn: (d) => `${d.hops} تحويلات قبل الصفحة النهائية. اربط مباشرة بالرابط النهائي.`, fail: (d) => `${d.hops} تحويلات متتالية. اختصر السلسلة إلى تحويل واحد.` },
  title: { group: "content", t: "عنوان الصفحة (Title)", why: "العنوان أقوى إشارة داخل الصفحة وهو العنوان الذي يظهر في نتائج البحث.", pass: (d) => `موجود، ${d.length} حرفًا: «${d.value}»`, warn: (d) => `موجود لكن طوله ${d.length} حرفًا (${Number(d.length) < 25 ? "قصير ولا يصف الصفحة" : "غالبًا سيُقتطع في النتائج"}): «${d.value}»`, fail: () => "لا يوجد وسم title. أضف عنوانًا فريدًا يحتوي الكلمة الرئيسية واسم المتجر." },
  description: { group: "content", t: "الوصف التعريفي (Meta Description)", why: "هو النص الذي يقرؤه المتسوّق قبل أن يضغط على نتيجتك.", pass: (d) => `موجود، ${d.length} حرفًا.`, warn: (d) => `موجود لكن طوله ${d.length} حرفًا. المناسب تقريبًا من 70 إلى 160.`, fail: () => "لا يوجد وصف تعريفي. سيختار جوجل نصًا عشوائيًا من الصفحة بدلًا منه." },
  h1: { group: "content", t: "العنوان الرئيسي (H1)", why: "وجود H1 واحد واضح يخبر محركات البحث عن موضوع الصفحة.", pass: (d) => `H1 واحد: «${d.value}»`, warn: (d) => `${d.count} وسوم H1. اجعل للصفحة عنوانًا رئيسيًا واحدًا.`, fail: () => "لا يوجد H1 في كود الصفحة." },
  h2: { group: "content", t: "العناوين الفرعية (H2)", why: "العناوين الفرعية تنظّم الصفحة للقارئ ولزواحف البحث.", pass: (d) => `${d.count} عناوين H2.`, warn: () => "لا توجد عناوين H2. قسّم المحتوى إلى أقسام." },
  indexable: { group: "index", t: "توجيهات الأرشفة التي استطعنا قراءتها", why: "توجيه noindex أو حظر في robots.txt قد يُبقي الصفحة خارج جوجل. هذا محدود بما تراه الأداة من توجيهات وليس حكمًا نهائيًا على الأرشفة؛ وحده Google Search Console يؤكد هل الصفحة مؤرشفة.", pass: (d) => d.robotsState === "ok" ? "لم نجد توجيه noindex ولا حظرًا في robots.txt لهذا الرابط." : "لم نجد توجيه noindex. تعذرت قراءة robots.txt فقواعد الزحف غير مؤكدة.", warn: () => "لم نجد noindex لكن تعذر جلب robots.txt بشكل موثوق (خطأ سيرفر) فقواعد الزحف غير مؤكدة.", fail: (d) => d.noindex ? "وُجد توجيه noindex (أو none) في وسوم الصفحة أو الهيدر، وهو يطلب من محركات البحث إبقاء الصفحة خارج النتائج." : "ملف robots.txt يمنع زاحف جوجل أو كل الزواحف من هذا الرابط." },
  canonical: { group: "index", t: "الرابط الأساسي (Canonical)", why: "يمنع مشاكل المحتوى المكرر الناتجة عن الفلاتر والمعاملات.", pass: () => "تم تحديد رابط canonical.", warn: (d) => d.other ? "رابط canonical يشير إلى نطاق مختلف. تأكد أن هذا مقصود." : "لا يوجد وسم canonical. أضفه لتجنب النسخ المكررة من الصفحة." },
  viewport: { group: "tech", t: "عرض الجوال (Viewport)", why: "أغلب زيارات المتاجر من الجوال وجوجل يؤرشف نسخة الجوال أولًا.", pass: () => "وسم viewport المتجاوب موجود.", fail: () => "لا يوجد وسم viewport بقيمة width=device-width. قد تظهر الصفحة على الجوال كصفحة سطح مكتب مصغّرة." },
  htmlLang: { group: "tech", t: "لغة الصفحة", why: "خاصية lang تساعد محركات البحث على عرض الصفحة للجمهور المناسب.", pass: () => "خاصية lang محددة في وسم html.", warn: () => "لا توجد خاصية lang في وسم html." },
  robots: { group: "index", t: "ملف robots.txt", why: "يوجّه الزواحف ويجب أن يشير إلى خريطة الموقع.", pass: () => "ملف robots.txt موجود ويذكر خريطة الموقع.", warn: (d) => d.found ? "ملف robots.txt موجود لكنه لا يذكر خريطة الموقع." : "لا يوجد ملف robots.txt في جذر الموقع." },
  sitemap: { group: "index", t: "خريطة الموقع (Sitemap)", why: "تساعد جوجل على اكتشاف كل صفحات المنتجات والأقسام.", pass: (d) => `تم العثور على خريطة موقع بها ${d.entries} رابطًا.`, warn: () => "لم يتم العثور على خريطة موقع XML قابلة للقراءة في /sitemap.xml أو داخل robots.txt." },
  speed: { group: "speed", t: "زمن استجابة السيرفر", why: "البطء يضر بالترتيب والمبيعات. هذا هو الوقت الذي احتاجه خادمنا لاستلام كود الصفحة، وليس اختبار تحميل كامل في المتصفح.", pass: (d) => `وصل كود الصفحة خلال ${d.ms} ملّي ثانية.`, warn: (d) => `استغرق وصول كود الصفحة ${d.ms} ملّي ثانية.`, fail: (d) => `استغرق وصول كود الصفحة ${d.ms} ملّي ثانية وهذا بطيء.` },
  compression: { group: "speed", t: "الضغط", why: "الاستجابات المضغوطة أسرع على شبكات الجوال.", pass: (d) => `الاستجابة مضغوطة بـ ${d.encoding}.`, warn: () => "كود الصفحة يُقدَّم بدون ضغط gzip أو Brotli." },
  htmlSize: { group: "speed", t: "حجم كود الصفحة", why: "الصفحات الكبيرة جدًا أبطأ في التحميل والمعالجة.", pass: (d) => `حجم الكود حوالي ${d.kb} كيلوبايت.`, warn: (d) => `حجم الكود حوالي ${d.kb} كيلوبايت وهذا ثقيل.`, fail: (d) => `حجم الكود ${d.truncated ? "أكثر من" : "حوالي"} ${d.kb} كيلوبايت وهذا ثقيل جدًا.` },
  scripts: { group: "speed", t: "ملفات السكربت الخارجية", why: "كثرة سكربتات الأطراف الخارجية تبطئ العرض وتضر مؤشرات Core Web Vitals.", pass: (d) => `${d.count} ملف سكربت خارجي في الصفحة.`, warn: (d) => `${d.count} ملف سكربت خارجي. احذف التطبيقات وأدوات التتبع غير المستخدمة.`, fail: (d) => `${d.count} ملف سكربت خارجي وهذا كثير. راجع واحذف ما لا تستخدمه.` },
  imageAlt: { group: "content", t: "النص البديل للصور (Alt)", why: "النص البديل يغذّي البحث بالصور وإمكانية الوصول.", pass: (d) => `كل الصور (${d.total}) لها نص بديل.`, warn: (d) => `${d.missing} من ${d.total} صورة بدون نص بديل.`, fail: (d) => `${d.missing} من ${d.total} صورة بدون نص بديل.` },
  schema: { group: "data", t: "البيانات المنظمة (JSON-LD)", why: "البيانات المنظمة تؤهلك للنتائج المميزة في جوجل.", pass: (d) => `تم العثور على: ${d.types}.`, warn: () => "لا توجد بيانات منظمة JSON-LD في هذه الصفحة." },
  productSchema: { group: "data", t: "ترميز المنتج (Product Schema)", why: "وفق توثيق جوجل للبيانات المنظمة للمنتجات، ترميز Product بالاسم والصورة والسعر والعملة قد يؤهل صفحة المنتج لنتائج المنتجات. الإضافات الموصى بها: التوفر والعلامة وsku/gtin والتقييمات.", pass: (d) => d.recommended ? `ترميز Product موجود بالحقول الأساسية. الإضافات الموصى بها الناقصة: ${d.recommended}.` : "ترميز Product موجود بالحقول الأساسية والإضافات الموصى بها.", warn: (d) => d.missing === "Product" ? "هذا الرابط يبدو صفحة منتج لكن لم نجد ترميز Product." : `ترميز Product موجود. الإضافات الموصى بها الناقصة: ${d.recommended}.`, fail: (d) => `ترميز Product موجود لكن الحقول المطلوبة ناقصة: ${d.missing}.` },
  orgSchema: { group: "data", t: "ترميز المتجر / الموقع", why: "يساعد جوجل على فهم من يدير المتجر.", pass: () => "تم العثور على ترميز Organization أو Store أو WebSite.", warn: () => "لا يوجد ترميز Organization أو WebSite." },
  openGraph: { group: "data", t: "وسوم المشاركة الاجتماعية", why: "وسوم Open Graph تتحكم في شكل الرابط عند مشاركته.", pass: () => "og:title وog:description وog:image موجودة.", warn: (d) => `الناقص: ${d.missing}.`, fail: () => "لا توجد وسوم Open Graph." },
  content: { group: "content", t: "النص الظاهر", why: "تنبيه تحريري وليس قاعدة ترتيب: جوجل يطلب محتوى مفيدًا موجّهًا للناس وليس هناك حد أدنى للكلمات. العدد المنخفض جدًا قد يعني أيضًا أن المحتوى يُحمَّل عبر JavaScript وهذه الأداة لا تشغّله.", pass: (d) => `حوالي ${d.words} كلمة نصية في كود الصفحة.`, warn: (d) => `حوالي ${d.words} كلمة نصية في كود الصفحة. راجع هل تجيب الصفحة عن أسئلة المتسوق.` },
  internalLinks: { group: "content", t: "الروابط الداخلية", why: "الروابط الداخلية توزّع القوة وتساعد الزواحف على اكتشاف الصفحات.", pass: (d) => `${d.count} رابط داخلي.`, warn: (d) => `${d.count} روابط داخلية فقط.` },
};


const extraEn: Record<string, Entry> = {
  softFourOhFour: { group: "index", t: "Missing-page handling", why: "Pages that do not exist should return 404 or 410. A 200 response (soft 404) wastes crawl budget and confuses indexing.", pass: (d) => `A random non-existent URL returns ${d.code}, as expected.`, warn: () => "A random non-existent URL returns 200 instead of 404 (soft 404)." },
  urlStructure: { group: "index", t: "URL structure", why: "Guideline: short, lowercase, hyphenated URLs without many parameters are easier to crawl and share.", pass: () => "The URL is short and clean.", warn: (d) => `The URL has ${d.issues} structure flag(s) (length ${d.length}, uppercase, underscores or many parameters).` },
  httpToHttps: { group: "tech", t: "HTTP to HTTPS redirect", why: "The insecure address should permanently redirect to the secure one.", pass: () => "The http:// version redirects to https://.", warn: (d) => `The http:// version returned ${d.code} instead of redirecting to https://.` },
  hsts: { group: "tech", t: "HSTS header", why: "Tells browsers to always use HTTPS for your domain.", pass: () => "The Strict-Transport-Security header is set.", warn: () => "No Strict-Transport-Security header found." },
  mixedContent: { group: "tech", t: "Mixed content", why: "Insecure resources on a secure page can be blocked by browsers and weaken trust.", pass: () => "No http:// images, scripts or frames found on the page.", fail: (d) => `${d.count} resource(s) load over insecure http:// on this HTTPS page.` },
  charset: { group: "tech", t: "Character encoding", why: "A declared charset prevents garbled text, which matters for Arabic content.", pass: () => "A character encoding is declared.", warn: () => "No charset declaration found." },
  duplicateTags: { group: "content", t: "Duplicate title or description tags", why: "Multiple tags give search engines conflicting signals.", pass: () => "", warn: (d) => `${d.titles} title tags and ${d.descriptions} meta descriptions found. Keep one of each.` },
  hreflang: { group: "tech", t: "Language alternates (hreflang)", why: "Valid hreflang with a self-reference helps serve the right language version.", pass: (d) => `${d.count} hreflang links found, valid codes, self-reference present.`, warn: (d) => `${d.count} hreflang links found. ${Number(d.badCode) > 0 ? "Some language codes look invalid. " : ""}${d.selfRef ? "" : "No self-referencing entry for this page."}` },
  brokenLinks: { group: "links", t: "Broken internal links (sample)", why: "Broken links waste crawl budget and frustrate shoppers. We test a sample of links from this page, not the whole site.", pass: (d) => `${d.sampled} internal links tested, none broken.`, warn: (d) => `${d.sampled} internal links tested; ${d.redirected} redirect before reaching the page. Link directly to final URLs.`, fail: (d) => `${d.broken} of ${d.sampled} sampled internal links return an error status.` },
  anchorText: { group: "links", t: "Link text quality", why: "Google recommends descriptive anchor text. Empty or generic text (\"click here\") tells nothing about the target.", pass: () => "No empty or generic internal link text found.", warn: (d) => `${d.empty} internal links with no text or label and ${d.generic} with generic text.` },
  crawlableLinks: { group: "links", t: "Crawlable links", why: "Google follows links written as <a href=\"URL\">. Items that use href=\"#\" or javascript: may not be followed. Menu toggles often use these on purpose.", pass: () => "No links using href=\"#\" or javascript: found.", warn: (d) => `${d.count} links use href="#" or javascript:. Check that real navigation links have real URLs.` },
  nofollowInternal: { group: "links", t: "Nofollow on internal links", why: "Nofollow on your own pages stops authority from flowing to them.", pass: () => "", warn: (d) => `${d.count} internal links carry rel="nofollow".` },
  renderBlocking: { group: "speed", t: "Render-blocking scripts", why: "Scripts in the head without async or defer delay first paint. A proxy for load speed; real Core Web Vitals need lab or field data.", pass: () => "No render-blocking scripts found in the head.", warn: (d) => `${d.count} script(s) in the head load without async or defer.` },
  imageDimensions: { group: "speed", t: "Image dimensions", why: "Width and height attributes reserve space and help avoid layout shift (the CLS metric).", pass: (d) => `All ${d.total} images declare dimensions.`, warn: (d) => `${d.missing} of ${d.total} images have no width and height attributes.` },
  lazyImages: { group: "speed", t: "Lazy loading", why: "Native lazy loading defers off-screen images.", pass: (d) => `${d.lazy} of ${d.total} images use loading="lazy".`, warn: (d) => `None of ${d.total} images use loading="lazy".` },
  imageFormats: { group: "speed", t: "Modern image formats", why: "WebP and AVIF are usually smaller than JPEG and PNG.", pass: (d) => `${d.modern} of ${d.total} images use WebP or AVIF.`, warn: (d) => `None of ${d.total} images use WebP or AVIF.` },
  breadcrumb: { group: "data", t: "Breadcrumb markup", why: "BreadcrumbList markup can show your page path in results.", pass: () => "BreadcrumbList markup found.", warn: () => "No BreadcrumbList markup found on this inner page." },
  favicon: { group: "data", t: "Favicon", why: "Shown next to your result on mobile search.", pass: () => "A favicon link is declared.", warn: () => "No favicon link found." },
  trustPages: { group: "trust", t: "Trust pages linked", why: "Google has no single E-E-A-T score, but its helpful-content guidance asks who is behind a site and whether it can be trusted. Linked about, contact, privacy and policy pages are visible trust signals.", pass: (d) => `${d.count} of 4 trust page types linked (about, contact, privacy, policies).`, warn: (d) => `${d.count} of 4 trust page types linked. Missing: ${[d.about ? "" : "about", d.contact ? "" : "contact", d.privacy ? "" : "privacy", d.policies ? "" : "shipping/returns/terms"].filter(Boolean).join(", ")}.` },
  contactInfo: { group: "trust", t: "Contact details on page", why: "Easy ways to reach the business support shopper trust.", pass: () => "A phone, email or WhatsApp link was found.", warn: () => "No phone, email or WhatsApp link found in the page HTML." },
};
Object.assign(en, extraEn);

const extraAr: Record<string, Entry> = {
  softFourOhFour: { group: "index", t: "التعامل مع الصفحات غير الموجودة", why: "الصفحات غير الموجودة يجب أن ترجع 404 أو 410. رجوع 200 (soft 404) يهدر ميزانية الزحف ويربك الأرشفة.", pass: (d) => `رابط عشوائي غير موجود يرجع ${d.code} كما هو متوقع.`, warn: () => "رابط عشوائي غير موجود يرجع 200 بدل 404 (soft 404)." },
  urlStructure: { group: "index", t: "بنية الرابط", why: "إرشاد عام: الروابط القصيرة بحروف صغيرة وشرطات وبدون معاملات كثيرة أسهل في الزحف والمشاركة.", pass: () => "الرابط قصير ونظيف.", warn: (d) => `في بنية الرابط ${d.issues} ملاحظة (الطول ${d.length} أو أحرف كبيرة أو شرطات سفلية أو معاملات كثيرة).` },
  httpToHttps: { group: "tech", t: "تحويل HTTP إلى HTTPS", why: "العنوان غير الآمن يجب أن يحوَّل دائمًا إلى العنوان الآمن.", pass: () => "نسخة http:// تحوَّل إلى https://.", warn: (d) => `نسخة http:// رجعت ${d.code} بدل التحويل إلى https://.` },
  hsts: { group: "tech", t: "ترويسة HSTS", why: "تخبر المتصفحات أن تستخدم HTTPS دائمًا لنطاقك.", pass: () => "ترويسة Strict-Transport-Security مضبوطة.", warn: () => "لا توجد ترويسة Strict-Transport-Security." },
  mixedContent: { group: "tech", t: "المحتوى المختلط", why: "الموارد غير الآمنة داخل صفحة آمنة قد تحجبها المتصفحات وتضعف الثقة.", pass: () => "لا توجد صور أو سكربتات أو إطارات عبر http:// في الصفحة.", fail: (d) => `${d.count} مورد يُحمَّل عبر http:// غير آمن داخل صفحة HTTPS.` },
  charset: { group: "tech", t: "ترميز الحروف", why: "تحديد الترميز يمنع ظهور نص مشوّه، وهذا مهم للمحتوى العربي.", pass: () => "ترميز الحروف محدد.", warn: () => "لا يوجد تحديد لترميز الحروف (charset)." },
  duplicateTags: { group: "content", t: "تكرار وسوم العنوان أو الوصف", why: "تكرار الوسوم يعطي محركات البحث إشارات متعارضة.", pass: () => "", warn: (d) => `وُجد ${d.titles} وسم title و${d.descriptions} وصف تعريفي. اترك واحدًا من كل نوع.` },
  hreflang: { group: "tech", t: "بدائل اللغة (hreflang)", why: "hreflang صحيح مع إشارة ذاتية يساعد على عرض نسخة اللغة المناسبة.", pass: (d) => `${d.count} روابط hreflang بأكواد صحيحة ومع إشارة ذاتية.`, warn: (d) => `${d.count} روابط hreflang. ${Number(d.badCode) > 0 ? "بعض أكواد اللغة تبدو غير صحيحة. " : ""}${d.selfRef ? "" : "لا يوجد إدخال يشير إلى هذه الصفحة نفسها."}` },
  brokenLinks: { group: "links", t: "الروابط الداخلية المكسورة (عيّنة)", why: "الروابط المكسورة تهدر ميزانية الزحف وتزعج المتسوقين. نختبر عيّنة من روابط هذه الصفحة وليس الموقع كله.", pass: (d) => `تم اختبار ${d.sampled} رابطًا داخليًا ولا يوجد مكسور.`, warn: (d) => `تم اختبار ${d.sampled} رابطًا داخليًا؛ ${d.redirected} منها يحوَّل قبل الوصول. اربط مباشرة بالروابط النهائية.`, fail: (d) => `${d.broken} من ${d.sampled} رابطًا داخليًا في العيّنة يرجع حالة خطأ.` },
  anchorText: { group: "links", t: "جودة نص الروابط", why: "توصي جوجل بنص رابط وصفي. النص الفارغ أو العام («اضغط هنا») لا يخبر عن الوجهة.", pass: () => "لا توجد روابط داخلية بنص فارغ أو عام.", warn: (d) => `${d.empty} رابطًا داخليًا بلا نص أو وصف و${d.generic} بنص عام.` },
  crawlableLinks: { group: "links", t: "قابلية الزحف للروابط", why: "جوجل يتبع الروابط المكتوبة بصيغة <a href=\"URL\">. العناصر التي تستخدم href=\"#\" أو javascript: قد لا تُتبع. القوائم المنسدلة تستخدمها أحيانًا عن قصد.", pass: () => "لا توجد روابط تستخدم href=\"#\" أو javascript:.", warn: (d) => `${d.count} رابطًا يستخدم href="#" أو javascript:. تأكد أن روابط التنقل الفعلية لها عناوين حقيقية.` },
  nofollowInternal: { group: "links", t: "Nofollow على الروابط الداخلية", why: "وسم nofollow على صفحاتك يمنع انتقال القوة إليها.", pass: () => "", warn: (d) => `${d.count} رابطًا داخليًا يحمل rel="nofollow".` },
  renderBlocking: { group: "speed", t: "سكربتات تعطّل العرض", why: "السكربتات في الهيد بدون async أو defer تؤخر ظهور الصفحة. هذا مؤشر تقريبي للسرعة؛ مؤشرات Core Web Vitals الفعلية تحتاج بيانات مختبرية أو ميدانية.", pass: () => "لا توجد سكربتات معطِّلة للعرض في الهيد.", warn: (d) => `${d.count} سكربت في الهيد يُحمَّل بدون async أو defer.` },
  imageDimensions: { group: "speed", t: "أبعاد الصور", why: "خاصيتا width وheight تحجزان المساحة وتقللان اهتزاز التخطيط (مؤشر CLS).", pass: (d) => `كل الصور (${d.total}) تحدد أبعادها.`, warn: (d) => `${d.missing} من ${d.total} صورة بدون width وheight.` },
  lazyImages: { group: "speed", t: "التحميل الكسول", why: "التحميل الكسول المدمج يؤجل الصور خارج الشاشة.", pass: (d) => `${d.lazy} من ${d.total} صورة تستخدم loading="lazy".`, warn: (d) => `لا توجد صورة من ${d.total} تستخدم loading="lazy".` },
  imageFormats: { group: "speed", t: "صيغ الصور الحديثة", why: "WebP وAVIF عادةً أصغر من JPEG وPNG.", pass: (d) => `${d.modern} من ${d.total} صورة بصيغة WebP أو AVIF.`, warn: (d) => `لا توجد صورة من ${d.total} بصيغة WebP أو AVIF.` },
  breadcrumb: { group: "data", t: "ترميز مسار التنقل", why: "ترميز BreadcrumbList قد يعرض مسار صفحتك في النتائج.", pass: () => "ترميز BreadcrumbList موجود.", warn: () => "لا يوجد ترميز BreadcrumbList في هذه الصفحة الداخلية." },
  favicon: { group: "data", t: "أيقونة الموقع (Favicon)", why: "تظهر بجانب نتيجتك في بحث الجوال.", pass: () => "رابط favicon موجود.", warn: () => "لا يوجد رابط favicon." },
  trustPages: { group: "trust", t: "صفحات الثقة المرتبطة", why: "جوجل لا يستخدم درجة E-E-A-T واحدة، لكن إرشادات المحتوى المفيد تسأل من يقف خلف الموقع وهل يمكن الوثوق به. ظهور روابط من نحن والتواصل والخصوصية والسياسات إشارات ثقة مرئية.", pass: (d) => `${d.count} من 4 أنواع من صفحات الثقة مرتبطة (من نحن، التواصل، الخصوصية، السياسات).`, warn: (d) => `${d.count} من 4 أنواع من صفحات الثقة مرتبطة. الناقص: ${[d.about ? "" : "من نحن", d.contact ? "" : "التواصل", d.privacy ? "" : "الخصوصية", d.policies ? "" : "الشحن/الاسترجاع/الشروط"].filter(Boolean).join("، ")}.` },
  contactInfo: { group: "trust", t: "بيانات التواصل في الصفحة", why: "سهولة التواصل مع النشاط تدعم ثقة المتسوق.", pass: () => "تم العثور على رابط هاتف أو بريد أو واتساب.", warn: () => "لا يوجد رابط هاتف أو بريد أو واتساب في كود الصفحة." },
};
Object.assign(ar, extraAr);

export const checkCopy = { en, ar };
export function describe(lang: Lang, c: Check): { t: string; why: string; msg: string; group: Entry["group"] } {
  const e = checkCopy[lang][c.id];
  if (!e) return { t: c.id, why: "", msg: "", group: "tech" };
  const f = c.status === "pass" ? e.pass : c.status === "warn" ? e.warn ?? e.pass : e.fail ?? e.warn ?? e.pass;
  return { t: e.t, why: e.why, msg: f(c.data), group: e.group };
}
