export type ServiceLanguage = "en" | "ar";

type Localized = { en: string; ar: string };
export type ServiceDetail = {
  slug: string;
  schemaType: "ProfessionalService" | "ConsultingService";
  category: Localized;
  evidence: { metric: string; label: Localized; note: Localized };
  en: {
    title: string;
    shortLabel: string;
    description: string;
    answer: string;
    pillars: { title: string; body: string }[];
    process: { title: string; body: string }[];
    faq: { q: string; a: string }[];
  };
  ar: {
    title: string;
    shortLabel: string;
    description: string;
    answer: string;
    pillars: { title: string; body: string }[];
    process: { title: string; body: string }[];
    faq: { q: string; a: string }[];
  };
};

const evidence = (metric: string, labelEn: string, labelAr: string, noteEn: string, noteAr: string) => ({
  metric,
  label: { en: labelEn, ar: labelAr },
  note: { en: noteEn, ar: noteAr },
});

export const SERVICE_DETAILS: ServiceDetail[] = [
  {
    slug: "seo-strategy-consulting",
    schemaType: "ConsultingService",
    category: { en: "SEO strategy", ar: "استراتيجية SEO" },
    evidence: evidence("7 years", "SEO and digital growth experience", "خبرة في SEO والنمو الرقمي", "Profile-level experience across SEO, digital products and growth engagements; not a promise of a fixed result.", "رقم على مستوى الخبرة في SEO والمنتجات الرقمية والنمو، وليس وعدًا بنتيجة ثابتة."),
    en: { title: "SEO Strategy & Consulting", shortLabel: "Strategy", description: "A practical SEO strategy for businesses that need clearer priorities, stronger pages and a measurable path from search demand to revenue.", answer: "SEO strategy and consulting connect technical health, keyword intent, content, authority and conversion into one operating plan. The work begins with the business goal and current constraint, not a generic checklist.", pillars: [{ title: "Commercial diagnosis", body: "Clarify the offer, buyer, market and conversion event before choosing keywords or publishing more pages." }, { title: "Prioritized roadmap", body: "Turn audits and research into a sequence of fixes, pages and experiments that a real team can execute." }, { title: "Measurement", body: "Separate visibility, qualified visits, enquiries and revenue so decisions are based on business evidence." }], process: [{ title: "Brief the business", body: "Understand the offer, audience, market, buying cycle and existing acquisition mix." }, { title: "Audit and map", body: "Review the technical foundation, current pages, search demand and competitive gaps." }, { title: "Plan and execute", body: "Choose a focused roadmap, assign priority pages and define the measurement loop." }, { title: "Review the signal", body: "Use Search Console, analytics and lead quality to refine the next decision." }], faq: [{ q: "Is SEO strategy useful before content production?", a: "Yes. A strategy prevents content from being published without a target page, intent or conversion role." }, { q: "Do you guarantee rankings?", a: "No. The strategy improves the factors a team can control and uses evidence to adapt; no responsible provider can guarantee a fixed position." }, { q: "Can the strategy support US and European expansion?", a: "Yes. International SEO, language architecture and market-specific intent can be added when the offer and evidence justify expansion." }] },
    ar: { title: "استراتيجية واستشارات SEO", shortLabel: "استراتيجية", description: "استراتيجية SEO عملية للشركات التي تحتاج أولويات أوضح، وصفحات أقوى، وطريقًا قابلًا للقياس من الطلب في البحث إلى الإيرادات.", answer: "تجمع استشارات SEO بين الصحة التقنية، نية الكلمات، المحتوى، السلطة والتحويل في خطة تشغيل واحدة. البداية من هدف المشروع وعنق الزجاجة الحالي، وليس قائمة عامة.", pillars: [{ title: "تشخيص تجاري", body: "نفهم العرض والعميل والسوق والتحويل قبل اختيار الكلمات أو نشر صفحات جديدة." }, { title: "خارطة أولويات", body: "نحوّل الأوديت والبحث إلى إصلاحات وصفحات وتجارب يمكن لفريق حقيقي تنفيذها." }, { title: "قياس واضح", body: "نفصل بين الظهور والزيارات المؤهلة والاستفسارات والإيرادات حتى تكون القرارات مبنية على دليل." }], process: [{ title: "نفهم المشروع", body: "نحدد العرض والجمهور والسوق ودورة الشراء وقنوات الاكتساب الحالية." }, { title: "نفحص ونرسم الخريطة", body: "نراجع الأساس التقني والصفحات والطلب في البحث والفجوات أمام المنافسين." }, { title: "نرتب وننفذ", body: "نختار خارطة مركزة ونحدد الصفحات ذات الأولوية وطريقة القياس." }, { title: "نراجع الإشارة", body: "نستخدم Search Console والتحليلات وجودة العملاء لتحديد الخطوة التالية." }], faq: [{ q: "هل أحتاج استراتيجية قبل كتابة المحتوى؟", a: "نعم غالبًا، لأنها تمنع نشر محتوى بلا صفحة هدف أو نية بحث أو دور في التحويل." }, { q: "هل تضمن الاستراتيجية ترتيبًا معينًا؟", a: "لا. نعمل على العوامل القابلة للتحكم ونعدل الأولويات حسب البيانات، ولا يمكن ضمان مركز ثابت بمسؤولية." }, { q: "هل تدعم الاستراتيجية التوسع لأمريكا وأوروبا؟", a: "نعم عندما يكون العرض قابلًا للتقديم هناك، مع إضافة بنية دولية ونية بحث خاصة بالسوق عند الحاجة." }] },
  },
  {
    slug: "keyword-research-strategy",
    schemaType: "ProfessionalService",
    category: { en: "Search demand", ar: "طلب البحث" },
    evidence: evidence("50+", "SEO and e-commerce projects where research informed the work", "مشروع SEO وتجارة إلكترونية دعمتها الأبحاث", "A profile-level project count; it does not mean every project had the same keyword outcome.", "عدد مشاريع على مستوى الملف المهني، ولا يعني أن كل مشروع حقق نفس نتيجة الكلمات."),
    en: { title: "Keyword Research & Strategy", shortLabel: "Research", description: "Keyword research that turns vague demand into a page map, content priorities and commercial opportunities for services, B2B, SaaS and e-commerce.", answer: "Good keyword research is not a list of high-volume phrases. It explains who is searching, what they expect to see, which page should answer them and how the opportunity supports the business.", pillars: [{ title: "Intent before volume", body: "Classify informational, commercial and transactional searches by the action they can support." }, { title: "Mapping and clustering", body: "Assign one clear job to each page and group related terms without forcing one URL to rank for everything." }, { title: "Market comparison", body: "Compare language, SERPs and competitors when targeting the US, Europe, Arabic markets or multiple locales." }], process: [{ title: "Collect the demand", body: "Combine seed terms, competitors, Search Console evidence and customer language." }, { title: "Read the SERP", body: "Study the pages and formats that satisfy the query in the market being targeted." }, { title: "Map the URLs", body: "Connect primary terms and supporting questions to existing or planned pages." }, { title: "Prioritize the backlog", body: "Score opportunities by business fit, intent, difficulty and realistic execution capacity." }], faq: [{ q: "Do you target every keyword on a separate page?", a: "No. Related phrases with the same intent usually belong together; separate pages need a real difference in purpose." }, { q: "Can keyword research cover US and Europe?", a: "Yes. Research should compare actual language and results by market instead of translating a list mechanically." }, { q: "What do I receive?", a: "A structured keyword map with intent, page recommendations, supporting questions and a prioritized content backlog." }] },
    ar: { title: "بحث الكلمات المفتاحية والاستراتيجية", shortLabel: "بحث", description: "بحث كلمات يحوّل الطلب الغامض إلى خريطة صفحات وأولويات محتوى وفرص تجارية للخدمات وB2B وSaaS والتجارة الإلكترونية.", answer: "بحث الكلمات الجيد ليس قائمة عبارات ذات حجم بحث كبير. هو يشرح من يبحث، وما الذي يتوقعه، وأي صفحة تجيبه، وكيف يخدم هذا الطلب هدف المشروع.", pillars: [{ title: "النية قبل الحجم", body: "نصنف البحث التعليمي والتجاري والشرائي حسب الإجراء الذي يمكن أن يدعمه." }, { title: "Mapping وClustering", body: "نعطي كل صفحة وظيفة واضحة ونجمع الكلمات المتقاربة دون إجبار URL واحد على الإجابة عن كل شيء." }, { title: "مقارنة الأسواق", body: "نقارن اللغة ونتائج البحث والمنافسين عند استهداف أمريكا وأوروبا أو الأسواق العربية." }], process: [{ title: "نجمع الطلب", body: "نمزج الكلمات الأولية والمنافسين وبيانات Search Console ولغة العملاء." }, { title: "نقرأ النتائج", body: "ندرس الصفحات والأشكال التي تحقق نية البحث في السوق المستهدف." }, { title: "نربط الكلمات بالصفحات", body: "نحدد الكلمة الأساسية والأسئلة المساندة لكل صفحة موجودة أو مخططة." }, { title: "نرتب الفرص", body: "نقيّم ملاءمة النشاط والنية والصعوبة والقدرة الواقعية على التنفيذ." }], faq: [{ q: "هل كل كلمة تحتاج صفحة منفصلة؟", a: "لا. الكلمات ذات النية نفسها غالبًا تجتمع في صفحة واحدة، ولا نُنشئ صفحة جديدة إلا مع اختلاف حقيقي في الهدف." }, { q: "هل يصلح البحث لأمريكا وأوروبا؟", a: "نعم، بشرط مقارنة اللغة والنتائج الفعلية لكل سوق بدل ترجمة القائمة حرفيًا." }, { q: "ماذا أستلم؟", a: "خريطة كلمات منظمة بالنية والصفحة والأسئلة المساندة وقائمة محتوى مرتبة حسب الأولوية." }] },
  },
  {
    slug: "technical-seo-audits",
    schemaType: "ProfessionalService",
    category: { en: "Technical SEO", ar: "SEO التقني" },
    evidence: evidence("+50%", "traffic signal from a structured-data and mobile SEO project", "إشارة نمو في الترافيك من مشروع بيانات منظمة وMobile SEO", "Documented in the existing showcase for a sports e-commerce platform; property and period are kept separate from other cases.", "موثق في النتائج الحالية لمنصة تجارة رياضية؛ الموقع والفترة منفصلان عن باقي الحالات."),
    en: { title: "Technical SEO & Audits", shortLabel: "Technical", description: "Technical SEO audits that find the issues blocking crawling, indexing, performance, page quality and reliable measurement.", answer: "A technical audit should end with decisions, not a long export of warnings. The work connects crawlability, rendering, Core Web Vitals, internal links, schema, canonicals and migrations to pages that matter.", pillars: [{ title: "Crawl and index control", body: "Review robots, sitemaps, canonicals, status codes, coverage and discoverability." }, { title: "Performance and rendering", body: "Inspect Core Web Vitals, mobile behavior, JavaScript rendering and the experience behind the URL." }, { title: "Implementation backlog", body: "Translate findings into severity, owners, dependencies and a sequence the team can ship." }], process: [{ title: "Scope the audit", body: "Agree on property, templates, markets, platform and the business pages that need protection." }, { title: "Diagnose the system", body: "Crawl and inspect representative URLs, templates and search signals." }, { title: "Prioritize fixes", body: "Separate blockers from improvements and define acceptance criteria." }, { title: "Verify the release", body: "Re-crawl, test key URLs and check Search Console signals after implementation." }], faq: [{ q: "Does a technical audit guarantee recovery?", a: "No. It identifies and prioritizes technical opportunities; outcomes depend on implementation, competition and the rest of the SEO system." }, { q: "Can you audit JavaScript websites?", a: "Yes. Rendering, HTML output, internal links and discoverability are part of the review." }, { q: "Do you audit international sites?", a: "Yes. Language URLs, hreflang, canonicals, redirects and sitemap organization can be included." }] },
    ar: { title: "الأوديت التقني وTechnical SEO", shortLabel: "تقني", description: "أوديت تقني يحدد المشاكل التي تعطل الزحف والفهرسة والأداء وجودة الصفحات والقياس الموثوق.", answer: "الأوديت التقني المفيد ينتهي بقرارات، وليس ملف تحذيرات طويل. نربط الزحف وCore Web Vitals والـJavaScript والروابط الداخلية والـSchema والـcanonical وعمليات النقل بالصفحات المهمة.", pillars: [{ title: "التحكم في الزحف والفهرسة", body: "نراجع robots وsitemap وcanonical وstatus codes وCoverage واكتشاف الصفحات." }, { title: "الأداء والـRendering", body: "نفحص Core Web Vitals وسلوك الموبايل وJavaScript وتجربة الصفحة الفعلية." }, { title: "Backlog قابل للتنفيذ", body: "نحوّل النتائج إلى درجة خطورة ومسؤوليات وتبعيات وترتيب يمكن للفريق إطلاقه." }], process: [{ title: "نحدد النطاق", body: "نتفق على الموقع والقوالب والمنصات والأسواق والصفحات التجارية المهمة." }, { title: "نشخّص النظام", body: "نفحص URLs وقوالب وإشارات بحث ممثلة للموقع." }, { title: "نرتب الإصلاحات", body: "نفصل العوائق عن التحسينات ونحدد معيار قبول لكل إصلاح." }, { title: "نتحقق بعد الإطلاق", body: "نعيد الفحص ونختبر الصفحات المهمة ونراجع Search Console." }], faq: [{ q: "هل الأوديت يضمن استعادة الترتيب؟", a: "لا. هو يحدد الفرص والمشاكل التقنية، بينما النتيجة تعتمد على التنفيذ والمنافسة وباقي منظومة SEO." }, { q: "هل تفحص مواقع JavaScript؟", a: "نعم، نفحص الـRendering والـHTML والروابط الداخلية وقابلية الاكتشاف." }, { q: "هل يشمل المواقع الدولية؟", a: "نعم، يمكن تضمين language URLs وhreflang وcanonical والتحويلات والـsitemap." }] },
  },
  {
    slug: "content-seo-copywriting",
    schemaType: "ProfessionalService",
    category: { en: "Content SEO", ar: "محتوى SEO" },
    evidence: evidence("+40%", "documented organic traffic signal in an A2M project context", "إشارة موثقة لزيادة الترافيك العضوي في سياق مشروع A2M", "Shown as cross-project evidence with content and SEO work; it is not presented as a content-only causal claim.", "معروضة كدليل من مشاريع شملت المحتوى وSEO، وليست ادعاءً بأن المحتوى وحده سبب النتيجة."),
    en: { title: "Content SEO & SEO Copywriting", shortLabel: "Content", description: "Search-led content that answers the real question, demonstrates expertise and moves a qualified reader toward the next step.", answer: "Content SEO combines search intent, useful writing, information architecture and conversion paths. The goal is not to make a page longer; it is to make the page more complete, clearer and more useful than the alternatives.", pillars: [{ title: "Intent-led briefs", body: "Define the reader, query, promise, evidence, structure and conversion role before drafting." }, { title: "Human editorial quality", body: "Use precise language, original examples, clear explanations and meaningful experience instead of filler." }, { title: "Content that connects", body: "Link articles to services, supporting guides and the next decision in the customer journey." }], process: [{ title: "Build the brief", body: "Combine keyword intent, SERP patterns, customer questions and business expertise." }, { title: "Draft the useful answer", body: "Lead with clarity, then add depth, examples, boundaries and implementation guidance." }, { title: "Optimize and connect", body: "Improve headings, entities, links, media, structured data and conversion paths." }, { title: "Refresh with evidence", body: "Use performance and reader signals to update the page instead of publishing duplicates." }], faq: [{ q: "Do you write AI-generated articles?", a: "The standard is human editorial quality: original structure, useful examples, fact review and editing. AI may support operations, but it is not a substitute for judgment." }, { q: "Can Content SEO support international markets?", a: "Yes. The brief can separate US, UK and European intent where terminology and context genuinely differ." }, { q: "How is content success measured?", a: "By a mix of qualified visibility, engagement, assisted journeys, enquiries and business fit—not word count alone." }] },
    ar: { title: "Content SEO وكتابة محتوى متوافق مع البحث", shortLabel: "محتوى", description: "محتوى يبدأ من سؤال القارئ الحقيقي، يثبت الخبرة، ويدفع الزائر المؤهل للخطوة التالية.", answer: "يجمع Content SEO بين نية البحث والكتابة المفيدة وهيكل المعلومات ومسار التحويل. الهدف ليس جعل الصفحة أطول، بل جعلها أوضح وأكمل وأكثر فائدة من البدائل.", pillars: [{ title: "Brief مبني على النية", body: "نحدد القارئ والكلمة والوعد والدليل والبنية ودور التحويل قبل الكتابة." }, { title: "جودة تحرير بشرية", body: "لغة دقيقة وأمثلة أصلية وشرح واضح بدون حشو أو فقرات عامة." }, { title: "محتوى متصل", body: "نربط المقالات بالخدمات والأدلة التالية وقرار العميل بدل تركها منفصلة." }], process: [{ title: "نبني الـBrief", body: "نمزج نية الكلمة وأنماط النتائج وأسئلة العملاء وخبرة المشروع." }, { title: "نكتب الإجابة المفيدة", body: "نبدأ بالوضوح ثم نضيف العمق والأمثلة والحدود والخطوات." }, { title: "نحسن ونربط", body: "نراجع العناوين والكيانات والروابط والوسائط والـSchema ومسارات التحويل." }, { title: "نحدّث بالدليل", body: "نستخدم الأداء وإشارات القارئ لتحديث الصفحة بدل نشر نسخ مكررة." }], faq: [{ q: "هل تكتب المقالات بالذكاء الاصطناعي؟", a: "المعيار هو جودة تحرير بشرية: هيكل أصلي وأمثلة مفيدة ومراجعة للحقائق وتحرير. قد يساعد AI في العمليات، لكنه لا يستبدل الحكم التحريري." }, { q: "هل Content SEO مناسب للأسواق الدولية؟", a: "نعم، يمكن فصل نية أمريكا وبريطانيا وأوروبا عندما تختلف المصطلحات والسياق فعلًا." }, { q: "كيف نقيس نجاح المحتوى؟", a: "بمزيج من الظهور المؤهل والتفاعل والرحلات المساعدة والاستفسارات وملاءمة العميل، وليس عدد الكلمات فقط." }] },
  },
  {
    slug: "international-multilingual-seo",
    schemaType: "ProfessionalService",
    category: { en: "International SEO", ar: "SEO دولي" },
    evidence: evidence("10+", "international client engagements in the documented profile", "تعاونات مع عملاء دوليين في الملف المهني", "A profile-level experience signal; it is not a country-specific ranking result.", "إشارة خبرة على مستوى الملف المهني، وليست نتيجة ترتيب مرتبطة بدولة بعينها."),
    en: { title: "International & Multilingual SEO", shortLabel: "International", description: "A market-aware SEO framework for brands expanding across the US, Europe and multiple languages without creating thin country pages.", answer: "International SEO starts by deciding which markets deserve attention, then aligns keyword research, localization, URL architecture, hreflang, content and reporting. It does not mean replacing one country name with another.", pillars: [{ title: "Market selection", body: "Prioritize markets by offer fit, demand, competition, capacity and the quality of the next step." }, { title: "Localization", body: "Adapt terminology, examples, trust signals and calls to action when the market changes the answer." }, { title: "Technical clarity", body: "Keep language and regional signals consistent across URLs, canonicals, hreflang, links and sitemaps." }], process: [{ title: "Choose the market", body: "Compare search demand, SERPs, competitors and commercial readiness." }, { title: "Design the locale model", body: "Choose language and country URL rules only when the content and offer justify them." }, { title: "Localize the experience", body: "Create briefs, content, internal links and conversion paths for the selected market." }, { title: "Report by market", body: "Separate pages, countries, languages and leads so one market does not hide another." }], faq: [{ q: "Do you create a page for every European country?", a: "Only when there is a real difference in intent, language, offer, evidence or customer context. Otherwise a strong English international page is safer." }, { q: "Do you operate local offices in the US or Europe?", a: "No local office claim is made. The service is remote-first and the page explains what can be delivered honestly." }, { q: "Is hreflang enough for international SEO?", a: "No. It is one technical signal inside a broader system of useful localized content, architecture and market fit." }] },
    ar: { title: "International وMultilingual SEO", shortLabel: "دولي", description: "إطار SEO واعٍ بالسوق للتوسع في أمريكا وأوروبا واللغات المتعددة دون إنشاء صفحات دول ضعيفة أو متشابهة.", answer: "يبدأ SEO الدولي بتحديد الأسواق التي تستحق التركيز، ثم ربط بحث الكلمات والتوطين وبنية الـURL وhreflang والمحتوى والتقارير. لا يعني استبدال اسم دولة باسم دولة.", pillars: [{ title: "اختيار السوق", body: "نرتب الأسواق حسب ملاءمة العرض والطلب والمنافسة والقدرة وجودة الخطوة التالية." }, { title: "Localization حقيقي", body: "نعدّل المصطلحات والأمثلة وإشارات الثقة والدعوات عندما يغير السوق الإجابة." }, { title: "وضوح تقني", body: "نحافظ على اتساق اللغة والمنطقة في الـURLs والـcanonical وhreflang والروابط والـsitemap." }], process: [{ title: "نختار السوق", body: "نقارن الطلب ونتائج البحث والمنافسين والاستعداد التجاري." }, { title: "نصمم نموذج اللغات", body: "نختار قواعد URL للغة والدولة فقط عندما يبررها المحتوى والعرض." }, { title: "نوطن التجربة", body: "نبني Brief ومحتوى وروابط داخلية ومسارات تحويل للسوق المختار." }, { title: "نقيس حسب السوق", body: "نفصل الصفحات والدول واللغات والعملاء حتى لا تخفي دولة أداء أخرى." }], faq: [{ q: "هل تنشئون صفحة لكل دولة أوروبية؟", a: "فقط عند وجود اختلاف حقيقي في النية أو اللغة أو العرض أو الدليل أو سياق العميل. غير ذلك يستفيد من صفحة إنجليزية دولية قوية." }, { q: "هل لديكم مكاتب محلية في أمريكا وأوروبا؟", a: "لا يوجد ادعاء بمكاتب محلية. الخدمة Remote-first ويتم شرح ما يمكن تقديمه بصدق." }, { q: "هل hreflang كافٍ؟", a: "لا. هو إشارة تقنية ضمن منظومة أكبر من المحتوى المفيد والبنية وملاءمة السوق." }] },
  },
  {
    slug: "ai-seo-aeo-geo",
    schemaType: "ProfessionalService",
    category: { en: "AI search", ar: "بحث الذكاء الاصطناعي" },
    evidence: evidence("50+", "projects across e-commerce, SaaS and digital products", "مشروعًا في التجارة الإلكترونية وSaaS والمنتجات الرقمية", "A documented profile-level delivery count; AI visibility is evaluated per property and query set, not inferred from the total.", "عدد موثق على مستوى الملف المهني؛ ظهور AI يُقيّم لكل موقع ومجموعة استعلامات، ولا يُستنتج من الإجمالي."),
    en: { title: "AI SEO, AEO & GEO", shortLabel: "AI search", description: "Make important pages clearer to search engines, answer engines and generative systems while keeping the underlying content useful to people.", answer: "AI search optimization is not a shortcut around SEO. It combines strong information architecture, direct answers, evidence, entities, structured data and a clear point of view so systems can understand the page and users can trust it.", pillars: [{ title: "Answer-ready structure", body: "Organize pages around direct answers, definitions, steps, comparisons and visible questions." }, { title: "Entity and evidence clarity", body: "Make the subject, author, experience, sources and boundaries understandable without inflated claims." }, { title: "Measurement and iteration", body: "Track query classes, citations, qualified visits and conversions instead of chasing a single AI screenshot." }], process: [{ title: "Map the answer space", body: "Identify questions, entities and pages that should represent the business." }, { title: "Improve the source", body: "Rewrite structure, evidence, internal links and schema where clarity is weak." }, { title: "Test retrieval", body: "Review how important questions are answered across search and generative surfaces." }, { title: "Keep the source fresh", body: "Update facts, examples and FAQs as the offer and market change." }], faq: [{ q: "Does GEO replace traditional SEO?", a: "No. Technical SEO, useful content and authority remain the foundation; GEO adds attention to how systems retrieve and summarize information." }, { q: "Can you guarantee inclusion in AI answers?", a: "No. AI responses change by query, model, evidence and time. The work improves clarity and eligibility without promising a fixed citation." }, { q: "Should every page add an FAQ?", a: "Only when real questions help the reader. Visible, useful answers matter more than adding schema without substance." }] },
    ar: { title: "AI SEO وAEO وGEO", shortLabel: "بحث AI", description: "نجعل الصفحات المهمة أوضح لمحركات البحث ومحركات الإجابة والأنظمة التوليدية مع الحفاظ على فائدتها للقارئ.", answer: "تحسين الظهور في بحث AI ليس طريقًا مختصرًا حول SEO. هو جمع بين بنية معلومات قوية وإجابات مباشرة ودليل وكيانات وبيانات منظمة ووجهة نظر واضحة.", pillars: [{ title: "بنية جاهزة للإجابة", body: "نرتب الصفحة حول الإجابات والتعريفات والخطوات والمقارنات والأسئلة الظاهرة." }, { title: "وضوح الكيان والدليل", body: "نوضح الموضوع والخبرة والمصادر والحدود بدون ادعاءات مبالغ فيها." }, { title: "قياس وتكرار", body: "نقيس مجموعات الاستعلامات والزيارات المؤهلة والتحويلات، لا لقطة واحدة من AI." }], process: [{ title: "نرسم مساحة الإجابة", body: "نحدد الأسئلة والكيانات والصفحات التي يجب أن تمثل المشروع." }, { title: "نحسن المصدر", body: "نراجع البنية والدليل والروابط الداخلية والـSchema عندما تكون غير واضحة." }, { title: "نختبر الاسترجاع", body: "نراجع طريقة ظهور الإجابات المهمة في البحث والواجهات التوليدية." }, { title: "نحافظ على حداثة المصدر", body: "نحدث الحقائق والأمثلة وFAQ عندما يتغير العرض أو السوق." }], faq: [{ q: "هل GEO بديل عن SEO؟", a: "لا. SEO التقني والمحتوى المفيد والسلطة أساس، وGEO يضيف اهتمامًا بطريقة استرجاع الأنظمة للمعلومة وتلخيصها." }, { q: "هل تضمن الظهور في إجابات AI؟", a: "لا. الإجابات تتغير حسب الاستعلام والنموذج والدليل والوقت. نرفع الوضوح والأهلية بدون وعد باقتباس ثابت." }, { q: "هل كل صفحة تحتاج FAQ؟", a: "فقط عندما تساعد أسئلة حقيقية القارئ. الإجابات الظاهرة المفيدة أهم من إضافة Schema بلا مضمون." }] },
  },
  {
    slug: "ecommerce-seo-growth",
    schemaType: "ProfessionalService",
    category: { en: "E-commerce", ar: "التجارة الإلكترونية" },
    evidence: evidence("+35%", "sales signal in the documented e-commerce showcase", "إشارة نمو مبيعات في نتائج التجارة الإلكترونية الموثقة", "The showcase combines SEO, content and conversion work across different properties and periods; it is not a universal forecast.", "النتيجة من لقطات جمعت SEO والمحتوى والتحويل لمواقع وفترات مختلفة، وليست توقعًا عامًا."),
    en: { title: "E-commerce SEO & Growth", shortLabel: "E-commerce", description: "Organic growth for online stores through category architecture, product pages, technical SEO, conversion paths and measurement.", answer: "E-commerce SEO has to help both discovery and buying decisions. The program connects category demand, product information, filters, schema, internal links and conversion evidence instead of optimizing isolated product titles.", pillars: [{ title: "Store architecture", body: "Design categories, collections, filters and internal paths around demand and crawlability." }, { title: "Product and category depth", body: "Improve the information needed to compare, trust and choose without manufacturing thin copy." }, { title: "Organic conversion", body: "Connect search landing pages to useful next steps, measurement and commercial outcomes." }], process: [{ title: "Review the catalog", body: "Understand products, margins, inventory logic, templates and customer questions." }, { title: "Map demand to templates", body: "Separate category, product, guide and comparison intent." }, { title: "Fix the experience", body: "Improve technical signals, content, schema, mobile UX and internal links." }, { title: "Measure the journey", body: "Track qualified organic sessions, product engagement, assisted paths and sales signals." }], faq: [{ q: "Can you work with a large catalog?", a: "Yes, but the first step is deciding which templates and product groups deserve priority instead of treating every SKU equally." }, { q: "Does product schema guarantee rich results?", a: "No. Structured data helps machines understand eligible information, but display and ranking remain controlled by search systems." }, { q: "Can e-commerce SEO target the US and Europe?", a: "Yes, with market-specific demand, product availability, language, currency and technical architecture where needed." }] },
    ar: { title: "SEO ونمو التجارة الإلكترونية", shortLabel: "متاجر", description: "نمو عضوي للمتاجر عبر بنية التصنيفات وصفحات المنتجات وSEO التقني ومسارات التحويل والقياس.", answer: "SEO للمتاجر يجب أن يساعد في الاكتشاف وقرار الشراء معًا. نربط طلب التصنيفات ومعلومات المنتج والفلاتر والـSchema والروابط الداخلية بدل تحسين عنوان منتج منفرد.", pillars: [{ title: "بنية المتجر", body: "نرتب التصنيفات والمجموعات والفلاتر والمسارات حسب الطلب وقابلية الزحف." }, { title: "عمق المنتج والتصنيف", body: "نضيف المعلومات التي تساعد المقارنة والثقة والاختيار بدون صناعة نص ضعيف." }, { title: "تحويل عضوي", body: "نربط صفحات الهبوط العضوية بالخطوة التالية والقياس والنتيجة التجارية." }], process: [{ title: "نفهم الكتالوج", body: "نراجع المنتجات والهامش والقوالب والمخزون وأسئلة العملاء." }, { title: "نربط الطلب بالقوالب", body: "نفصل نية التصنيف والمنتج والدليل والمقارنة." }, { title: "نصلح التجربة", body: "نحسن الإشارات التقنية والمحتوى والـSchema والموبايل والروابط الداخلية." }, { title: "نقيس الرحلة", body: "نتابع الزيارات المؤهلة وتفاعل المنتج والمسارات المساعدة وإشارات البيع." }], faq: [{ q: "هل يمكن التعامل مع كتالوج كبير؟", a: "نعم، لكن نبدأ بتحديد القوالب ومجموعات المنتجات ذات الأولوية بدل معاملة كل SKU بالطريقة نفسها." }, { q: "هل Product Schema يضمن ظهورًا غنيًا؟", a: "لا. يساعد الأنظمة على فهم البيانات المؤهلة، لكن العرض والترتيب يقررهما نظام البحث." }, { q: "هل يصلح استهداف أمريكا وأوروبا؟", a: "نعم مع بحث سوقي وتوافر المنتج واللغة والعملة وبنية تقنية مناسبة عند الحاجة." }] },
  },
  {
    slug: "growth-marketing-demand-generation",
    schemaType: "ConsultingService",
    category: { en: "Growth Marketing", ar: "Growth Marketing" },
    evidence: evidence("+35%", "sales signal shown in the existing growth showcase", "إشارة نمو مبيعات في نتائج النمو الحالية", "Shown across project evidence that combines SEO, content and conversion; not attributed to one channel alone.", "معروضة ضمن نتائج جمعت SEO والمحتوى والتحويل، وليست منسوبة لقناة واحدة فقط."),
    en: { title: "Growth Marketing for Services & B2B", shortLabel: "Growth", description: "Search-led demand generation, funnel strategy, CRM and sales-aligned content for service businesses and B2B teams.", answer: "Growth Marketing turns attention into a repeatable path toward a qualified opportunity. The work connects acquisition, positioning, landing pages, qualification, lifecycle and feedback from sales.", pillars: [{ title: "Demand generation", body: "Find the topics, offers and channels that attract a buyer with a real problem to solve." }, { title: "Funnel and qualification", body: "Design the next step, forms, lead criteria and handoff so volume does not hide poor fit." }, { title: "Sales alignment", body: "Use objections, pipeline feedback and customer language to improve content and campaigns." }], process: [{ title: "Define the opportunity", body: "Clarify ideal accounts, offer, buying committee, cycle and revenue signal." }, { title: "Build the path", body: "Connect search, content, landing pages, forms, CRM and follow-up." }, { title: "Instrument the journey", body: "Track source, qualification, response and assisted conversion." }, { title: "Improve the constraint", body: "Use data and sales feedback to improve the weakest step first." }], faq: [{ q: "Is Growth Marketing just paid advertising?", a: "No. It can include SEO, content, lifecycle, CRM, conversion and campaigns as long as they support a measurable growth path." }, { q: "Can this work for a service business?", a: "Yes. The strategy is useful when expertise, qualification and trust matter as much as traffic volume." }, { q: "Do you promise a specific number of leads?", a: "No. Lead volume and quality depend on offer, market, budget, capacity and execution; the system makes those drivers visible." }] },
    ar: { title: "Growth Marketing لشركات الخدمات وB2B", shortLabel: "نمو", description: "توليد طلب يبدأ من البحث، واستراتيجية Funnel وCRM ومحتوى متوافق مع المبيعات لشركات الخدمات وفرق B2B.", answer: "Growth Marketing يحوّل الانتباه إلى طريق متكرر نحو فرصة مؤهلة. نربط الاكتساب والتموضع وصفحات الهبوط والتأهيل ودورة حياة العميل وملاحظات المبيعات.", pillars: [{ title: "توليد الطلب", body: "نحدد الموضوعات والعروض والقنوات التي تجذب شخصًا لديه مشكلة حقيقية." }, { title: "Funnel وتأهيل", body: "نصمم الخطوة التالية ومعايير العميل وتسليم الـLead حتى لا يخفي العدد ضعف الملاءمة." }, { title: "اتساق مع المبيعات", body: "نستخدم الاعتراضات وملاحظات الـPipeline ولغة العميل لتحسين المحتوى والحملات." }], process: [{ title: "نحدد الفرصة", body: "نفهم الحساب المثالي والعرض ولجنة الشراء والدورة وإشارة الإيراد." }, { title: "نبني المسار", body: "نربط البحث والمحتوى وصفحات الهبوط والنماذج والـCRM والمتابعة." }, { title: "نقيس الرحلة", body: "نتابع المصدر والتأهيل والاستجابة والتحويلات المساعدة." }, { title: "نحسن عنق الزجاجة", body: "نستخدم البيانات وملاحظات المبيعات لتحسين أضعف خطوة أولًا." }], faq: [{ q: "هل Growth Marketing يعني إعلانات مدفوعة فقط؟", a: "لا. يمكن أن يشمل SEO والمحتوى ودورة الحياة وCRM والتحويل والحملات طالما تخدم طريق نمو قابلًا للقياس." }, { q: "هل يناسب شركات الخدمات؟", a: "نعم، خصوصًا عندما تكون الخبرة والتأهيل والثقة مهمة مثل حجم الترافيك." }, { q: "هل تضمن عددًا معينًا من العملاء؟", a: "لا. العدد والجودة يعتمدان على العرض والسوق والميزانية والقدرة والتنفيذ، والنظام يجعل العوامل واضحة." }] },
  },
  {
    slug: "off-page-seo-digital-pr",
    schemaType: "ProfessionalService",
    category: { en: "Authority building", ar: "بناء السلطة" },
    evidence: evidence("50+", "projects supported by the documented SEO profile", "مشروعًا ضمن الملف المهني لخدمات SEO", "This is a profile-level delivery count; no link or authority metric is assigned to a single project without evidence.", "عدد على مستوى الملف المهني؛ لا ننسب رقم روابط أو سلطة لمشروع منفرد بدون دليل."),
    en: { title: "Off-Page SEO & Digital PR", shortLabel: "Authority", description: "Relevant authority building through useful assets, outreach and digital PR—not indiscriminate link buying.", answer: "Off-page SEO works when a brand earns attention and references for something worth citing. The process starts with relevance and a credible asset, then builds relationships and measures quality instead of chasing link counts.", pillars: [{ title: "Relevance first", body: "Choose topics, publications and communities that make sense for the business and audience." }, { title: "Link-worthy assets", body: "Create data, tools, guides, expertise or stories that give outreach a legitimate reason." }, { title: "Quality controls", body: "Review topical fit, trust, placement and risk instead of accepting every backlink opportunity." }], process: [{ title: "Audit the profile", body: "Understand existing links, brand mentions, risks and the authority gap." }, { title: "Build the asset", body: "Choose a useful page or story that can support earned attention." }, { title: "Run relevant outreach", body: "Contact people and publications with a clear reason and respectful context." }, { title: "Review the signal", body: "Measure quality, discovery, referrals and assisted demand—not vanity counts alone." }], faq: [{ q: "Do you sell backlinks?", a: "The approach is relevance-led outreach and digital PR, not a promise of bulk links or random placements." }, { q: "Can Digital PR help a new brand?", a: "Yes, when the brand has a clear point of view or useful asset that gives others a reason to mention it." }, { q: "Is a high domain metric enough?", a: "No. Relevance, trust, placement, editorial context and risk matter more than one third-party score." }] },
    ar: { title: "Off-Page SEO وDigital PR", shortLabel: "سلطة", description: "بناء سلطة مرتبط بالموضوع عبر الأصول المفيدة والتواصل وDigital PR، وليس شراء روابط عشوائيًا.", answer: "ينجح Off-Page SEO عندما تكسب العلامة اهتمامًا وإشارات لأنها تقدم شيئًا يستحق الاقتباس. البداية من الملاءمة والأصل القوي، ثم علاقة وتقييم جودة، لا عدّ الروابط فقط.", pillars: [{ title: "الملاءمة أولًا", body: "نختار موضوعات ومواقع ومجتمعات لها علاقة بالنشاط والجمهور." }, { title: "أصول تستحق الربط", body: "نبني بيانات أو أدوات أو أدلة أو خبرة أو قصة تعطي التواصل سببًا مشروعًا." }, { title: "ضبط الجودة", body: "نراجع الصلة والثقة ومكان الرابط والمخاطر بدل قبول أي فرصة." }], process: [{ title: "نفحص الملف", body: "نفهم الروابط الحالية وBrand Mentions والمخاطر وفجوة السلطة." }, { title: "نبني الأصل", body: "نختار صفحة أو قصة مفيدة تستحق جذب الانتباه." }, { title: "نتواصل بملاءمة", body: "نتواصل مع أشخاص ومواقع بسبب واضح وسياق محترم." }, { title: "نراجع الإشارة", body: "نقيس الجودة والاكتشاف والإحالات والطلب المساعد، وليس العدد فقط." }], faq: [{ q: "هل تبيعون Backlinks؟", a: "المنهج هو Outreach وDigital PR مرتبطان بالموضوع، وليس وعدًا بروابط كثيرة أو placements عشوائية." }, { q: "هل يناسب Digital PR براند جديد؟", a: "نعم عندما يكون لديه رأي واضح أو أصل مفيد يعطي الآخرين سببًا حقيقيًا للذكر." }, { q: "هل ارتفاع Domain Authority كافٍ؟", a: "لا. الصلة والثقة والمكان والسياق التحريري والمخاطر أهم من رقم صادر عن أداة خارجية." }] },
  },
  {
    slug: "local-mobile-seo",
    schemaType: "ProfessionalService",
    category: { en: "Local SEO", ar: "SEO محلي" },
    evidence: evidence("+25%", "foot-traffic signal in the documented local restaurant case", "إشارة زيادة زيارات في حالة المطعم المحلية الموثقة", "Documented for a local restaurant case using Google Business Profile and local SEO; it is not a promise for every location.", "موثق لحالة مطعم محلية باستخدام Google Business Profile وLocal SEO، وليس وعدًا لكل نشاط."),
    en: { title: "Local & Mobile SEO", shortLabel: "Local", description: "Local search and mobile experience improvements for businesses whose customers genuinely search by place, service area or proximity.", answer: "Local SEO combines accurate business information, relevant local pages, reviews and a useful mobile experience. It should reflect where the business can actually serve customers, not create empty city pages.", pillars: [{ title: "Local relevance", body: "Align the profile, services, locations, categories and on-page evidence with the real offer." }, { title: "Mobile experience", body: "Make it easy to call, request directions, understand the service and take the next step on a phone." }, { title: "Trust and measurement", body: "Track discovery, calls, direction requests, forms and qualified visits instead of map position alone." }], process: [{ title: "Confirm the service area", body: "Separate real locations, service areas and markets that should not be represented." }, { title: "Clean the signals", body: "Review business data, profiles, local pages, links, schema and mobile UX." }, { title: "Improve the local path", body: "Make the offer, proof, contact route and next step clear." }, { title: "Measure actions", body: "Connect local visibility to calls, visits, requests and qualified enquiries." }], faq: [{ q: "Do you create a page for every city?", a: "Only when the business can provide unique, useful information for that city and genuinely serves it." }, { q: "Does Local SEO work without a physical office?", a: "Service-area businesses can be eligible in appropriate situations, but the page and profile must represent the real operating model." }, { q: "Can mobile SEO be separated from local SEO?", a: "Yes, but they often overlap when a local customer needs a fast, clear mobile next step." }] },
    ar: { title: "Local وMobile SEO", shortLabel: "محلي", description: "تحسين البحث المحلي وتجربة الموبايل للشركات التي يبحث عملاؤها فعلًا حسب المكان أو منطقة الخدمة أو القرب.", answer: "يجمع Local SEO بين بيانات النشاط الصحيحة والصفحات المحلية ذات الصلة والتقييمات وتجربة موبايل مفيدة. يجب أن يعكس المكان الذي يمكن للنشاط خدمته فعليًا، لا صفحات مدن فارغة.", pillars: [{ title: "ملاءمة محلية", body: "نوحّد الملف والخدمات والمواقع والتصنيفات والدليل الموجود في الصفحة مع العرض الحقيقي." }, { title: "تجربة الموبايل", body: "نجعل الاتصال وطلب الاتجاهات وفهم الخدمة والخطوة التالية سهلًا على الهاتف." }, { title: "ثقة وقياس", body: "نتابع الاكتشاف والمكالمات والاتجاهات والنماذج والزيارات المؤهلة بدل المركز فقط." }], process: [{ title: "نؤكد منطقة الخدمة", body: "نفصل المواقع الحقيقية ومناطق الخدمة والأسواق التي لا يجب تمثيلها." }, { title: "ننظف الإشارات", body: "نراجع بيانات النشاط والملفات والصفحات المحلية والروابط والـSchema والموبايل." }, { title: "نحسن المسار المحلي", body: "نوضح العرض والدليل وطريقة التواصل والخطوة التالية." }, { title: "نقيس الأفعال", body: "نربط الظهور المحلي بالمكالمات والزيارات والطلبات والاستفسارات المؤهلة." }], faq: [{ q: "هل تنشئون صفحة لكل مدينة؟", a: "فقط عندما يستطيع النشاط تقديم معلومات مفيدة ومختلفة للمدينة ويخدمها فعلًا." }, { q: "هل يعمل Local SEO بدون مكتب؟", a: "قد تنطبق القواعد على نشاط منطقة خدمة في حالات مناسبة، لكن الصفحة والملف يجب أن يعكسا نموذج العمل الحقيقي." }, { q: "هل Mobile SEO منفصل عن Local SEO؟", a: "نعم يمكن فصلهما، لكنهما يتداخلان عندما يحتاج العميل المحلي خطوة موبايل سريعة وواضحة." }] },
  },
  {
    slug: "analytics-measurement",
    schemaType: "ConsultingService",
    category: { en: "Measurement", ar: "القياس" },
    evidence: evidence("8 months", "documented measurement window in a traffic-growth project", "فترة قياس موثقة في مشروع نمو ترافيك", "The existing profile documents a 45% traffic increase within eight months for a group of websites; it is not a forecast for a new property.", "الملف يوثق زيادة 45% في الترافيك خلال 8 أشهر لمجموعة مواقع، وليست توقعًا لموقع جديد."),
    en: { title: "Analytics, GA4 & Search Console", shortLabel: "Measurement", description: "Measurement systems that show which pages attract qualified demand, what users do next and where SEO should improve.", answer: "Analytics is useful when it helps a team make a decision. The work connects Search Console, GA4, events, landing pages, conversions and lead quality without pretending that one ranking or traffic number explains growth.", pillars: [{ title: "Clean foundations", body: "Review properties, events, conversions, UTM logic, filters and consent-aware measurement." }, { title: "Decision dashboards", body: "Build views for pages, queries, markets, devices and conversion paths that answer real questions." }, { title: "Commercial context", body: "Connect organic activity to enquiries, qualified leads, revenue signals and assisted journeys." }], process: [{ title: "Define the decision", body: "Start with the decisions the owner, marketer or sales team needs to make." }, { title: "Audit the data", body: "Check tracking, attribution, events, page groups and data quality." }, { title: "Build the view", body: "Create dashboards and reporting notes that explain what changed and why it matters." }, { title: "Create the loop", body: "Feed evidence back into content, technical and growth priorities." }], faq: [{ q: "Do you only report rankings?", a: "No. Rankings can be a diagnostic signal, but reports should also show qualified visibility, behavior, leads and business fit." }, { q: "Can reports separate US and Europe?", a: "Yes. Country, language, page and device dimensions can be separated when the tracking and site architecture support it." }, { q: "Can GA4 fix a weak business model?", a: "No. Measurement reveals the path and its gaps; it cannot make an offer or market fit stronger by itself." }] },
    ar: { title: "Analytics وGA4 وSearch Console", shortLabel: "قياس", description: "أنظمة قياس توضح أي الصفحات تجذب الطلب المؤهل، وما الذي يحدث بعدها، وأين يجب تحسين SEO.", answer: "التحليلات مفيدة عندما تساعد الفريق على اتخاذ قرار. نربط Search Console وGA4 والأحداث والصفحات والتحويلات وجودة الـLead بدون اختزال النمو في ترتيب أو رقم ترافيك واحد.", pillars: [{ title: "أساس نظيف", body: "نراجع الـproperties والأحداث والتحويلات وUTM والفلاتر والقياس المتوافق مع الخصوصية." }, { title: "لوحات قرار", body: "نبني مشاهد للصفحات والاستعلامات والأسواق والأجهزة ومسارات التحويل." }, { title: "سياق تجاري", body: "نربط النشاط العضوي بالاستفسارات والـLeads المؤهلة وإشارات الإيراد والرحلات المساعدة." }], process: [{ title: "نحدد القرار", body: "نبدأ بالقرارات التي يحتاجها صاحب المشروع أو التسويق أو المبيعات." }, { title: "نراجع البيانات", body: "نفحص التتبع والإسناد والأحداث ومجموعات الصفحات وجودة البيانات." }, { title: "نبني الرؤية", body: "ننظم Dashboard وملاحظات تقرير تشرح ما تغير ولماذا يهم." }, { title: "نصنع الحلقة", body: "نعيد الدليل إلى أولويات المحتوى والتقني والنمو." }], faq: [{ q: "هل تقتصر التقارير على الترتيب؟", a: "لا. الترتيب إشارة تشخيصية، والتقرير يجب أن يعرض الظهور المؤهل والسلوك والعملاء وملاءمة النشاط." }, { q: "هل يمكن فصل أمريكا وأوروبا؟", a: "نعم، يمكن فصل الدولة واللغة والصفحة والجهاز عندما يدعم التتبع وبنية الموقع ذلك." }, { q: "هل GA4 يصلح نموذج عمل ضعيف؟", a: "لا. القياس يكشف المسار وفجواته، لكنه لا يصنع ملاءمة العرض والسوق وحده." }] },
  },
  {
    slug: "cro-marketing-automation",
    schemaType: "ConsultingService",
    category: { en: "Conversion and operations", ar: "التحويل والعمليات" },
    evidence: evidence("+35%", "sales signal in an e-commerce conversion context", "إشارة نمو مبيعات في سياق تحويل متجر", "Documented in the wider e-commerce showcase where SEO, content and conversion work are combined; not a CRO-only claim.", "موثق ضمن نتائج تجارة إلكترونية جمعت SEO والمحتوى والتحويل، وليس ادعاءً لتحسين التحويل وحده."),
    en: { title: "CRO & Marketing Automation", shortLabel: "Operations", description: "Improve the next step after discovery, qualify demand and automate repeatable marketing operations with a clear purpose.", answer: "CRO and automation should remove friction from a proven journey, not add tools for their own sake. The work looks at page clarity, calls to action, forms, routing, CRM and follow-up.", pillars: [{ title: "Message and friction", body: "Clarify the promise, proof, objections and next action on high-intent pages." }, { title: "Lead operations", body: "Improve forms, qualification, routing, notifications and handoffs so good demand is not lost." }, { title: "Useful automation", body: "Use n8n and connected tools when they reduce repetitive work and preserve data quality." }], process: [{ title: "Find the drop-off", body: "Review landing pages, behavior, forms, response time and lead quality." }, { title: "Design the next step", body: "Choose one clear action and the information needed to make it useful." }, { title: "Connect the tools", body: "Map CRM fields, routing, notifications and follow-up with ownership." }, { title: "Test and learn", body: "Measure completion and qualified outcomes before scaling automation." }], faq: [{ q: "Is CRO just changing button colors?", a: "No. The important work is message, relevance, trust, friction, form design and the next step." }, { q: "Do you build every automation?", a: "Only when automation solves a defined operational problem and the team can maintain it." }, { q: "Can CRO support SEO traffic?", a: "Yes. It helps a relevant visitor take the next useful step after landing on a search page." }] },
    ar: { title: "CRO وMarketing Automation", shortLabel: "عمليات", description: "تحسين الخطوة التالية بعد الظهور، وتأهيل الطلب، وأتمتة عمليات التسويق المتكررة بهدف واضح.", answer: "يجب أن يزيل CRO والأتمتة الاحتكاك من رحلة مثبتة، لا إضافة أدوات لمجرد وجودها. نراجع وضوح الصفحة والدعوة للنقر والنماذج والتوجيه والـCRM والمتابعة.", pillars: [{ title: "الرسالة والاحتكاك", body: "نوضح الوعد والدليل والاعتراض والخطوة التالية في الصفحات عالية النية." }, { title: "عمليات الـLead", body: "نحسن النماذج والتأهيل والتوجيه والتنبيهات والتسليم حتى لا يضيع الطلب الجيد." }, { title: "أتمتة مفيدة", body: "نستخدم n8n والأدوات المتصلة عندما تقلل التكرار وتحافظ على جودة البيانات." }], process: [{ title: "نحدد التسرب", body: "نراجع الصفحات والسلوك والنماذج وسرعة الرد وجودة العملاء." }, { title: "نصمم الخطوة", body: "نختار إجراء واضحًا والمعلومات اللازمة ليكون مفيدًا." }, { title: "نوصل الأدوات", body: "نرسم حقول CRM والتوجيه والتنبيهات والمتابعة والمسؤوليات." }, { title: "نختبر ونتعلم", body: "نقيس الإكمال والنتائج المؤهلة قبل توسيع الأتمتة." }], faq: [{ q: "هل CRO يعني تغيير لون الزر؟", a: "لا. الأهم هو الرسالة والملاءمة والثقة والاحتكاك وتصميم النموذج والخطوة التالية." }, { q: "هل تبنون كل أتمتة؟", a: "فقط عندما تحل مشكلة تشغيلية محددة ويمكن للفريق صيانتها." }, { q: "هل يساعد CRO ترافيك SEO؟", a: "نعم، لأنه يساعد الزائر المناسب على أخذ الخطوة المفيدة بعد دخوله من البحث." }] },
  },
  {
    slug: "marketing-consulting",
    schemaType: "ConsultingService",
    category: { en: "Marketing consulting", ar: "استشارات تسويقية" },
    evidence: evidence("50+", "projects across e-commerce, SaaS and digital products", "مشروعًا في التجارة الإلكترونية وSaaS والمنتجات الرقمية", "A documented profile-level experience signal; project outcomes and service attribution remain separated.", "إشارة خبرة موثقة على مستوى الملف المهني؛ نفصل نتائج كل مشروع ونسبة كل خدمة."),
    en: { title: "Marketing Consulting", shortLabel: "Consulting", description: "Practical marketing consulting for brands that need a clearer position, sharper priorities and a stronger connection between marketing and revenue.", answer: "Marketing consulting turns scattered activities into a decision system. It can cover positioning, audience, channel mix, offer, content, funnel, CRM, measurement and the operating rhythm required to execute.", pillars: [{ title: "Position and offer", body: "Clarify why the right customer should care, what to say and which offer deserves attention first." }, { title: "Channel and funnel", body: "Choose the role of SEO, content, paid, email, CRM and sales rather than treating channels as isolated tasks." }, { title: "Operating clarity", body: "Define priorities, owners, measurement and review cycles so strategy can survive contact with the team." }], process: [{ title: "Listen and diagnose", body: "Understand the market, customer, offer, current channels and commercial friction." }, { title: "Make the choices", body: "Prioritize audience, message, channel and conversion decisions with explicit trade-offs." }, { title: "Build the system", body: "Create the roadmap, content and funnel structure, measurement and ownership model." }, { title: "Review the evidence", body: "Use customer and performance feedback to refine the next strategic decision." }], faq: [{ q: "Is marketing consulting the same as an agency retainer?", a: "Not necessarily. Consulting can focus on diagnosis, decisions, roadmap and enablement; execution scope is agreed around the need." }, { q: "Can marketing consulting include SEO?", a: "Yes. SEO can be one part of a broader acquisition and growth system when search demand fits the offer." }, { q: "Do you work with international teams?", a: "Yes, through a remote-first model with clear scope, documentation and market-specific decisions where necessary." }] },
    ar: { title: "الاستشارات التسويقية", shortLabel: "استشارات", description: "استشارات تسويقية عملية للبراندات التي تحتاج تموضعًا أوضح وأولويات أدق وربطًا أقوى بين التسويق والإيرادات.", answer: "تحوّل الاستشارات التسويقية الأنشطة المتفرقة إلى نظام قرارات. يمكن أن تشمل التموضع والجمهور والمزيج التسويقي والعرض والمحتوى والـFunnel والـCRM والقياس وإيقاع التنفيذ.", pillars: [{ title: "التموضع والعرض", body: "نوضح لماذا يهتم العميل المناسب، وماذا نقول، وأي عرض يستحق التركيز أولًا." }, { title: "القنوات والـFunnel", body: "نحدد دور SEO والمحتوى والإعلانات والإيميل والـCRM والمبيعات بدل عزل كل قناة." }, { title: "وضوح التشغيل", body: "نحدد الأولويات والمسؤوليات والقياس ودورات المراجعة حتى تعيش الاستراتيجية داخل الفريق." }], process: [{ title: "نستمع ونشخّص", body: "نفهم السوق والعميل والعرض والقنوات الحالية والاحتكاك التجاري." }, { title: "نتخذ الاختيارات", body: "نرتب الجمهور والرسالة والقناة والتحويل مع توضيح التنازلات." }, { title: "نبني النظام", body: "ننشئ خارطة التنفيذ وهيكل المحتوى والـFunnel والقياس والمسؤوليات." }, { title: "نراجع الدليل", body: "نستخدم ملاحظات العملاء والأداء لتعديل القرار الاستراتيجي التالي." }], faq: [{ q: "هل الاستشارات التسويقية مثل Retainer وكالة؟", a: "ليس بالضرورة. قد تركز الاستشارة على التشخيص والقرارات والخارطة وتمكين الفريق، ويُتفق على التنفيذ حسب الحاجة." }, { q: "هل تشمل الاستشارات SEO؟", a: "نعم، يمكن أن يكون SEO جزءًا من منظومة اكتساب ونمو أوسع عندما يناسب الطلب العرض." }, { q: "هل تعملون مع فرق دولية؟", a: "نعم بنموذج Remote-first ونطاق موثق وقرارات خاصة بالسوق عند الحاجة." }] },
  },
];

export const SERVICE_DETAIL_SLUGS = SERVICE_DETAILS.map((service) => service.slug);
export function getServiceDetail(slug: string) { return SERVICE_DETAILS.find((service) => service.slug === slug); }
