import type { ComponentType } from "react";

type A = { intro:string; why:string; scope:string[]; choose:string[]; market:string; cta:string; ar:boolean };
function Page({a}:{a:A}) { return <>
  <p>{a.intro}</p>
  <h2>{a.ar ? "ليه الكلمة دي مهمة للمشروع؟" : "Why this search matters to a business"}</h2><p>{a.why}</p>
  <h2>{a.ar ? "نطاق الشغل اللي لازم تتوقعه" : "The scope you should expect"}</h2><ul>{a.scope.map(x=><li key={x}>{x}</li>)}</ul>
  <h2>{a.ar ? "إزاي تختار الشخص الصح؟" : "How to choose the right specialist"}</h2><ul>{a.choose.map(x=><li key={x}>{x}</li>)}</ul>
  <h2>{a.ar ? "السوق واللغة" : "Market and language fit"}</h2><p>{a.market}</p>
  <h2>{a.ar ? "الخطوة الجاية" : "Next step"}</h2><p>{a.cta}</p>
  <p><a href={a.ar?"/ar/seo-expert":"/seo-expert"}>{a.ar?"اعرف أكتر عن خدمات عمرو البصيلي":"See Amr Elbusaily's SEO services"}</a>{" · "}<a href={a.ar?"/ar/contact":"/contact"}>{a.ar?"احجز استشارة مجانية":"Book a free consultation"}</a></p>
</> }
const enScope=["A technical and indexation review ranked by commercial impact","A buyer-intent keyword map connected to service and landing pages","Content briefs, internal links and implementation priorities","Lead, call and revenue measurement instead of traffic-only reporting"];
const enChoose=["Ask for a written 90-day plan and the reasoning behind it","Review evidence with dates, context and the work that produced the result","Confirm who executes the work and how often priorities are reviewed","Avoid ranking guarantees, bulk backlinks and article-count packages"];
const arScope=["مراجعة تقنية وفهرسة مرتبة حسب الأثر التجاري","خريطة كلمات نية شراء مرتبطة بصفحات الخدمات والهبوط","بريفات محتوى وروابط داخلية وأولويات تنفيذ","قياس العملاء والمكالمات والإيراد بدل الزيارات فقط"];
const arChoose=["اطلب خطة 90 يوم مكتوبة وسبب كل أولوية","راجع أدلة عليها تاريخ وسياق والشغل اللي عمل النتيجة","اتأكد مين هينفذ وإمتى الأولويات هتتراجع","ابعد عن ضمان الترتيب وباقات الروابط وعدد المقالات"];
const d:Record<string,A>={
"hire-seo-expert-en":{ar:false,intro:"Hiring an SEO expert should reduce uncertainty, not add another vague monthly expense. The right specialist connects technical fixes, search intent, content and conversion tracking to qualified leads and sales.",why:"This is a high-intent decision. Companies searching for an expert usually have an offer, a website and an acquisition problem. A useful engagement starts with business priorities, not a generic checklist.",scope:enScope,choose:enChoose,market:"If you sell across Egypt or the Gulf, the plan must separate Arabic and English demand, country intent and local proof. Literal translation does not create a bilingual search strategy.",cta:"Send Amr Elbusaily your website, target market and main commercial goal. The first consultation is free and gives you an honest view of the biggest growth gap."},
"hire-seo-expert-ar":{ar:true,intro:"التعاقد مع خبير سيو لازم يقلل الحيرة، مش يضيف مصروف شهري غامض. الخبير الصح بيربط السيو التقني ونية البحث والمحتوى وقياس التحويل بعملاء مؤهلين ومبيعات.",why:"دي لحظة قرار بنية شراء واضحة. الشركة اللي بتدور على خبير غالبًا عندها خدمة وموقع ومشكلة في جذب العملاء. الشغل المفيد يبدأ بأولويات البزنس مش قائمة فحص عامة.",scope:arScope,choose:arChoose,market:"لو بتبيع في مصر أو الخليج، الخطة لازم تفصل الطلب العربي والإنجليزي ونية كل دولة وأدلة الثقة المحلية. الترجمة الحرفية مش استراتيجية بحث ثنائية اللغة.",cta:"ابعت لعمرو البصيلي موقعك والسوق والهدف التجاري الأساسي. الاستشارة الأولى مجانية وهتاخد رأي صريح في أكبر فجوة نمو."},
"freelance-seo-specialist-en":{ar:false,intro:"A freelance SEO specialist can give a growing company senior attention without the overhead of a large agency. The value is direct ownership of research, implementation priorities, measurement and communication.",why:"A freelancer fits when you want direct access to the person analysing the site and making recommendations. Compare operating models, not job titles: accountability and execution quality matter more than team size.",scope:enScope,choose:enChoose,market:"Remote SEO works naturally across Egypt, Saudi Arabia, the UAE and the wider Gulf. What matters is local search understanding, a reliable review rhythm and access to the people who know the offer.",cta:"If you need a freelance SEO specialist who works directly on the account, share your site and market with Amr for a free first review."},
"freelance-seo-specialist-ar":{ar:true,intro:"متخصص سيو فريلانسر يقدر يدي المشروع اهتمام خبير من غير تكلفة وتشابك وكالة كبيرة. القيمة في المسؤولية المباشرة عن البحث والأولويات والقياس والتواصل.",why:"الفريلانسر مناسب لما تحب تتعامل مع الشخص اللي بيحلل وبيقرر بنفسه. قارن طريقة التشغيل مش المسمى؛ المسؤولية وجودة التنفيذ أهم من حجم الفريق.",scope:arScope,choose:arChoose,market:"شغل السيو عن بُعد مناسب لمصر والسعودية والإمارات والخليج. المهم فهم البحث المحلي ونظام مراجعة ثابت والوصول للناس اللي فاهمة الخدمة.",cta:"لو محتاج متخصص سيو فريلانسر يمسك الحساب بنفسه، ابعت موقعك والسوق لعمرو لمراجعة أولى مجانية."},
"arabic-seo-expert-en":{ar:false,intro:"An Arabic SEO expert does more than translate English keywords. Arabic search demand changes by country, dialect, device and buying context, so winning requires native research and clean bilingual architecture.",why:"The same service can be searched in Modern Standard Arabic, local dialect, Arabic-English hybrids and English. Group those variants by intent instead of cloning a page for every spelling.",scope:enScope,choose:enChoose,market:"Arabic and English pages need stable URLs, accurate hreflang, self-referencing canonicals, natural copy and navigation that does not mix languages. Each market also needs its own proof and offer.",cta:"Amr builds Arabic-English SEO programs for businesses targeting Egypt and the Gulf. Request a free review of your language structure and commercial keyword coverage."},
"arabic-seo-expert-ar":{ar:true,intro:"خبير السيو العربي مش مجرد مترجم كلمات إنجليزية. الطلب بيتغير حسب البلد واللهجة والجهاز وسياق الشراء، فالنجاح محتاج بحث طبيعي وبنية لغات واضحة.",why:"نفس الخدمة ممكن الناس تدور عليها بالفصحى أو اللهجة أو خليط عربي وإنجليزي. اجمع الصيغ حسب نية المستخدم بدل ما تنسخ صفحة لكل طريقة كتابة.",scope:arScope,choose:arChoose,market:"الصفحات العربية والإنجليزية محتاجة روابط ثابتة وhreflang وcanonical صحيح ومحتوى طبيعي وتنقل ما يخلطش اللغات. وكل سوق محتاج أدلة وعرض خاصين بيه.",cta:"عمرو بيبني برامج سيو عربي وإنجليزي لمصر والخليج. اطلب مراجعة مجانية لبنية اللغات وتغطية الكلمات التجارية."},
"seo-consultant-egypt-en":{ar:false,intro:"An SEO consultant in Egypt should understand search mechanics and the commercial reality of Egyptian businesses: mixed Arabic-English journeys, mobile-first users and budgets that need disciplined priorities.",why:"The first deliverable should be a decision plan, not a long error export. It must show which issues affect revenue pages and where limited development and content resources will produce the best return.",scope:enScope,choose:enChoose,market:"Local businesses need Google Business Profile, genuine reviews and service-area pages. National businesses need category and service clusters supported by clear expertise and conversion paths.",cta:"Amr is based in Egypt and works directly with local and Gulf businesses. Send your site for a free first review focused on qualified enquiries."},
"seo-consultant-egypt-ar":{ar:true,intro:"مستشار السيو في مصر لازم يفهم ميكانيكا البحث وواقع المشاريع المصرية: رحلة عميل عربي وإنجليزي، استخدام موبايل، وميزانية محتاجة ترتيب أولويات.",why:"أول تسليم لازم يكون خطة قرارات مش تصدير أخطاء طويل. توضح المشاكل اللي بتأثر على صفحات الإيراد وفين التطوير والمحتوى هيعملوا أفضل عائد.",scope:arScope,choose:arChoose,market:"المشاريع المحلية محتاجة Google Business Profile وتقييمات حقيقية وصفحات مناطق خدمة. المشروع القومي محتاج مجموعات فئات وخدمات وأدلة خبرة ومسار تحويل واضح.",cta:"عمرو موجود في مصر وبيشتغل مباشرة مع مشاريع محلية وخليجية. ابعت موقعك لمراجعة أولى مجانية هدفها استفسارات مؤهلة."},
"seo-consultant-gulf-en":{ar:false,intro:"A Gulf SEO consultant needs to plan for a region without treating it as one market. Saudi Arabia, the UAE, Kuwait, Qatar, Bahrain and Oman differ in demand, competition and language mix.",why:"Buyer-intent searches include service, category, price, comparison and provider terms. Informational content should support those commercial pages, not replace them.",scope:enScope,choose:enChoose,market:"Saudi Arabia can support deep Arabic clusters, Dubai often needs strong English alongside Arabic, and smaller Gulf markets reward sharper local prioritisation. Never clone city text between countries.",cta:"Amr works remotely with Gulf businesses on technical SEO, bilingual content and buyer-intent pages. Request a free market review and 90-day priorities."},
"seo-consultant-gulf-ar":{ar:true,intro:"مستشار السيو للخليج لازم يخطط للمنطقة من غير ما يعاملها كسوق واحد. السعودية والإمارات والكويت وقطر والبحرين وعُمان مختلفين في الطلب والمنافسة واللغات.",why:"كلمات نية الشراء تشمل الخدمة والفئة والسعر والمقارنة والبحث عن مقدم خدمة. المحتوى المعلوماتي يدعم الصفحات التجارية لكنه ما يحلش مكانها.",scope:arScope,choose:arChoose,market:"السعودية تسمح بمجموعات عربية عميقة، ودبي محتاجة إنجليزي قوي جنب العربي، والأسواق الأصغر تكافئ الأولوية المحلية الدقيقة. ما تنسخش نص المدن بين الدول.",cta:"عمرو بيشتغل مع مشاريع خليجية في السيو التقني والمحتوى الثنائي وصفحات نية الشراء. اطلب مراجعة سوق مجانية وخطة 90 يوم."},
"saas-seo-consultant-en":{ar:false,intro:"A SaaS SEO consultant should connect product positioning, problem-aware search demand and conversion paths to pipeline. Publishing a high volume of generic software articles is not a SaaS growth strategy.",why:"SaaS buyers research problems, alternatives, integrations, pricing and implementation before booking a demo. The keyword map must cover that journey while giving commercial pages enough authority to rank.",scope:enScope,choose:enChoose,market:"For regional SaaS products, separate Arabic and English demand and decide which markets deserve localized pricing, proof and use cases. Track demos and qualified pipeline, not sign-ups or traffic alone.",cta:"Amr helps SaaS and digital-product teams build buyer-intent search systems. Share your product, ICP and target market for a free first review."},
"saas-seo-consultant-ar":{ar:true,intro:"مستشار سيو SaaS لازم يربط تموضع المنتج وطلب البحث ومسارات التحويل بالـpipeline. نشر عدد كبير من مقالات السوفت وير العامة مش استراتيجية نمو.",why:"مشتري SaaS بيدور على المشكلة والبدائل والتكاملات والسعر والتنفيذ قبل حجز الديمو. خريطة الكلمات لازم تغطي الرحلة وتدي صفحات البيع قوة كفاية.",scope:arScope,choose:arChoose,market:"للمنتجات الإقليمية افصل الطلب العربي والإنجليزي وحدد الأسواق اللي تستحق تسعير وأدلة وحالات استخدام محلية. قيس الديموهات والفرص المؤهلة، مش الزيارات فقط.",cta:"عمرو بيساعد فرق SaaS والمنتجات الرقمية تبني منظومة بحث بنية شراء. ابعت المنتج والجمهور والسوق لمراجعة أولى مجانية."},
"ecommerce-seo-expert-hire-en":{ar:false,intro:"Hiring an e-commerce SEO expert means improving discoverability without losing sight of margin, stock, category priorities and conversion. Store SEO succeeds when technical work and merchandising decisions support each other.",why:"E-commerce demand is distributed across categories, products, brands, comparisons and buying guides. The job is to route each query to the most useful commercial destination and reduce duplicated or thin pages.",scope:enScope,choose:enChoose,market:"For Egypt and Gulf stores, the plan may also need Arabic-English category architecture, Salla or Zid constraints, local delivery terms and mobile checkout behaviour.",cta:"Send Amr your store, platform and top categories for a free first review focused on revenue pages and realistic organic opportunities."},
"ecommerce-seo-expert-hire-ar":{ar:true,intro:"التعاقد مع خبير سيو متاجر يعني تحسين الاكتشاف من غير نسيان الهامش والمخزون وأولوية الفئات والتحويل. سيو المتجر ينجح لما التقنية والـmerchandising يشتغلوا مع بعض.",why:"طلب التجارة الإلكترونية متوزع على الفئات والمنتجات والبراندات والمقارنات وأدلة الشراء. المهمة توصل كل بحث لأفضل وجهة تجارية وتقلل الصفحات الضعيفة أو المكررة.",scope:arScope,choose:arChoose,market:"لمتاجر مصر والخليج، الخطة ممكن تحتاج بنية فئات عربي وإنجليزي وقيود سلة أو زد وشروط توصيل محلية وسلوك شراء من الموبايل.",cta:"ابعت لعمرو متجرك والمنصة وأهم الفئات لمراجعة أولى مجانية تركّز على صفحات الإيراد والفرص الواقعية."},
"small-business-seo-expert-en":{ar:false,intro:"A small-business SEO expert should protect limited time and budget by choosing the few actions most likely to generate qualified calls and enquiries. More deliverables do not automatically mean more growth.",why:"Small businesses often win through a narrow service area, clear expertise and strong local proof. Technical basics, service pages, reviews and conversion tracking usually matter before a large content calendar.",scope:enScope,choose:enChoose,market:"The right plan depends on whether the business serves one neighbourhood, all of Egypt or Gulf clients remotely. Local intent and market proof should shape every landing page.",cta:"Amr offers a free first review for small businesses that want a focused SEO plan without a bloated retainer."},
"small-business-seo-expert-ar":{ar:true,intro:"خبير سيو للمشاريع الصغيرة لازم يحافظ على الوقت والميزانية باختيار أقل عدد من الخطوات اللي ممكن تجيب مكالمات واستفسارات مؤهلة. كثرة التسليمات مش معناها نمو.",why:"المشروع الصغير غالبًا يكسب من نطاق خدمة واضح وخبرة وأدلة محلية قوية. الأساس التقني وصفحات الخدمات والتقييمات وقياس التحويل أهم عادة من جدول محتوى ضخم.",scope:arScope,choose:arChoose,market:"الخطة تختلف لو المشروع بيخدم منطقة واحدة أو مصر كلها أو عملاء خليج عن بُعد. النية المحلية وأدلة السوق لازم تشكل كل صفحة هبوط.",cta:"عمرو بيقدم مراجعة أولى مجانية للمشاريع الصغيرة اللي محتاجة خطة سيو مركزة من غير اشتراك مبالغ فيه."},
"local-seo-consultant-hire-en":{ar:false,intro:"A local SEO consultant helps service businesses become visible when nearby customers are ready to call, visit or request a quote. The work spans Google Business Profile, the website and the trust signals that connect them.",why:"Local search is commercial. Accuracy, reviews, location relevance, service pages and a smooth contact path often decide whether visibility turns into revenue.",scope:enScope,choose:enChoose,market:"Local strategy must match the real service area. Cairo, Riyadh, Dubai and smaller Gulf cities have different competition, language and directory signals, so cloned city pages are not enough.",cta:"Share your service area, website and Google Business Profile with Amr for a free local visibility review."},
"local-seo-consultant-hire-ar":{ar:true,intro:"مستشار السيو المحلي بيساعد مشاريع الخدمات تظهر لما العميل القريب يكون جاهز يتصل أو يزور أو يطلب سعر. الشغل بيجمع Google Business Profile والموقع وإشارات الثقة.",why:"البحث المحلي تجاري. دقة البيانات والتقييمات وعلاقة المكان بالخدمة وصفحات الخدمات وسهولة التواصل هي اللي بتحول الظهور لإيراد.",scope:arScope,choose:arChoose,market:"الخطة المحلية لازم تطابق نطاق الخدمة الحقيقي. القاهرة والرياض ودبي والمدن الخليجية الأصغر مختلفة في المنافسة واللغة والدلائل، ونسخ صفحات المدن مش كفاية.",cta:"ابعت لعمرو نطاق الخدمة والموقع وGoogle Business Profile لمراجعة ظهور محلي مجانية."},
"technical-seo-consultant-hire-en":{ar:false,intro:"Hiring a technical SEO consultant is most valuable when crawling, rendering, indexation, performance or a migration threatens important search traffic. The output should be an implementable priority plan, not a spreadsheet of warnings.",why:"Technical issues matter in proportion to the pages and demand they block. A consultant should reproduce the problem, explain commercial impact, define acceptance criteria and work with developers through validation.",scope:enScope,choose:enChoose,market:"JavaScript frameworks, multilingual routing and large catalogues create different risks. The audit method should match the stack, release process and markets instead of applying one generic scorecard.",cta:"Amr provides technical SEO reviews tied to commercial pages and implementation priorities. Send your site and current concern for a free initial assessment."},
"technical-seo-consultant-hire-ar":{ar:true,intro:"التعاقد مع مستشار سيو تقني يكون أهم لما الزحف أو الرندر أو الفهرسة أو السرعة أو نقل الموقع يهدد الزيارات المهمة. الناتج لازم خطة قابلة للتنفيذ، مش شيت تحذيرات.",why:"المشكلة التقنية أهم بقدر الصفحات والطلب اللي بتعطله. المستشار لازم يعيد المشكلة ويشرح أثرها التجاري ويحدد معيار القبول ويتابع مع المطورين لحد التحقق.",scope:arScope,choose:arChoose,market:"مواقع JavaScript والمسارات متعددة اللغات والكتالوجات الكبيرة ليها مخاطر مختلفة. طريقة الأوديت لازم تناسب التقنية والإصدارات والأسواق، مش scorecard واحد.",cta:"عمرو بيقدم مراجعات سيو تقنية مرتبطة بصفحات البيع وأولويات التنفيذ. ابعت الموقع والمشكلة الحالية لتقييم أولي مجاني."}
};
export const buyerIntentSeoArticles:Record<string,ComponentType>=Object.fromEntries(Object.entries(d).map(([k,a])=>[k,()=> <Page a={a}/>]));
