import type { SeoLanguage } from "@/components/SeoAuthorityPage";

type BuyerMarket = "expert" | "saudi" | "uae";
const sources = [
  { label: "Google: choosing an SEO", href: "https://developers.google.com/search/docs/fundamentals/do-i-need-seo" },
  { label: "Google: people-first content", href: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content" },
  { label: "Google: language and regional versions", href: "https://developers.google.com/search/docs/specialty/international/managing-multi-regional-sites" },
  { label: "Google Business Profile eligibility", href: "https://support.google.com/business/answer/13763036?hl=en" },
];
const guides = {
  expert: {
    ar: [
      { title: "كيف تختار أفضل متخصص سيو لمشروعك؟", body: "الأفضل ليس لقبًا يثبته مقدم الخدمة لنفسه؛ هو اختيار يناسب مشكلتك ومواردك. قبل مقارنة العروض، اكتب هدفًا واحدًا: زيادة طلبات التسعير لخدمة محددة، أو تحسين اكتشاف فئة منتجات، أو إصلاح صفحات لا تُفهرس. اسأل المتخصص كيف سيفصل بين المشكلة التقنية ومشكلة المحتوى والطلب. اطلب نموذج مخرج يشرح المشكلة والدليل والإصلاح وطريقة التحقق، وليس قائمة كلمات بلا صفحات. واسأل من سينفذ التغييرات: هو أم مطورك أم فريق المحتوى. العرض الذي لا يحدد مسؤول التنفيذ قد يتركك مع تقرير صحيح لا يتحول إلى عمل." },
      { title: "مثال من هذا الموقع: عنوان صحيح ومحتوى خدمة خاطئ", body: "في مراجعة هذا البورتفوليو بتاريخ 7 أكتوبر 2026، كانت صفحات تفاصيل الخدمات العربية تحمل عناوين مختلفة لكن تعرض جسم صفحة الخدمات العامة. المشكلة لم تكن نقص مقال جديد: مسار الخدمات الأب كان يعرض صفحة عامة بدل تمرير العرض إلى المسار الفرعي. الإصلاح جعل الصفحات الثلاث عشرة تعرض محتواها الخاص. تحققنا من الاستجابة ومن الصفحة بعد تشغيل JavaScript، بما فيها صفحة الأوديت التقني والصفحات غير الموجودة. هذا مثال تنفيذي يمكن مراجعته، لا دراسة حالة عن زيادة الترافيك؛ لم نقس أثره على ترتيب جوجل أو المبيعات." },
      { title: "ما الذي يجب أن يحتويه عرض العمل؟", body: "اطلب نطاقًا واضحًا: الصفحات المستهدفة، الاستعلامات التي تخدمها، البيانات المطلوبة، عدد المراجعات، وما لا يشمله السعر. في بداية التشخيص يكفي وصول قراءة إلى Search Console والتحليلات عند توفرهما؛ صلاحيات النشر مرحلة منفصلة. لكل مهمة يجب أن تعرف الدليل، الأولوية، المسؤول، وتحقق ما بعد التنفيذ. وللمحتوى يجب أن يحدد الملخص سؤال القارئ والمثال والمصادر والصفحة المرتبطة، لا عدد الكلمات وحده. جوجل لا يفرض طولًا سحريًا للمقال، ولا يوجد عدد صفحات يومي يضمن سلامة الموقع. الجودة تقاس بما يستطيع القارئ فهمه أو عمله بعد القراءة." },
      { title: "كيف تقرأ النتيجة دون مبالغة؟", body: "افصل بين أربع طبقات: تنفيذ الإصلاح، ظهوره في الزحف والفهرسة، تغير الاستعلامات والنقرات، ثم الطلبات المؤهلة. تحسن الظهور وحده لا يثبت زيادة المبيعات. سجل تاريخ الإطلاق والصفحة والفترة وقارن ظروفًا متقاربة، مع الإشارة لتغير الأسعار والإعلانات والموسمية. لا تجمع لقطات مواقع مختلفة في نتيجة واحدة. إذا لم تتوفر بيانات التحويل قل ذلك صراحة. اتفق على موعد مراجعة مناسب لنوع التغيير بدل ضمان موعد ثابت للنتيجة. وقد تكون الخطوة الصحيحة إصلاح المنتج أو تجربة الشراء قبل إنتاج محتوى جديد." },
    ],
    en: [
      { title: "Choose the specialist for the problem, not the label", body: "Define one outcome before comparing offers: qualified service inquiries, discovery of a product category, or resolving an indexing problem. Ask for a sample deliverable that joins evidence, a recommended change, its owner and a validation step. A keyword list without destination pages is not a strategy. Clarify who will implement the work and which development or editorial resources are needed. The best fit may be a specialist, an agency or your existing team, depending on the workload." },
      { title: "A reviewable example from this portfolio", body: "On 7 October 2026, Arabic service detail routes on this site had distinct titles but displayed the generic services body. The parent route rendered the index instead of an Outlet. Fixing that route restored the individual bodies across all 13 details. Verification covered server HTML, the hydrated browser page and unknown-route handling. This is a documented implementation example, not a claim of traffic or revenue growth: its search impact has not been measured." },
      { title: "Specify the work and the measurement", body: "A scoped offer should name the pages, evidence required, deliverables, implementation owner and review dates. Start an audit with read-only Search Console access where available; publishing access is a separate step. Content briefs should define the reader's question, examples, sources and useful next page rather than a fixed word count. Track implementation, indexing, relevant queries and qualified conversions separately. Record the property, period and launch date, and disclose missing conversion data rather than inferring sales from impressions." },
    ],
  },
  saudi: {
    ar: [
      { title: "نطاق المتجر السعودي يختلف عن نطاق شركة الخدمات", body: "لمتجر يستهدف السعودية، نبدأ من فئات المنتجات التي يمكن بيعها بالفعل: التوفر، الشحن، السعر، ووصف يجيب عن أسئلة المشتري. وجود كلمات الرياض وجدة في كل عنوان لا يصنع استراتيجية. أما شركة الخدمات التي تستقبل العملاء أو تزورهم، فيمكن أن تحتاج صفحات خدمة ومناطق تغطيها فعليًا مع أدلة النشاط. لا ننشئ صفحة لكل مدينة لمجرد تغيير الاسم. لو نفس الفريق يقدم نفس الخدمة عن بُعد بلا فرق مفيد، قد تكون صفحة خدمة واحدة مع وصف تغطية واضح أفضل من عشرات الصفحات المتشابهة." },
      { title: "مثال توضيحي: فئة عبايات مع منتجات متقاربة", body: "هذا مثال افتراضي وليس نتيجة عميل: متجر لديه فئة عبايات وعشرات المنتجات بأوصاف مورد متطابقة. قبل إضافة مقالات، نفحص هل الفئة قابلة للفهرسة، وهل روابط المقاسات والألوان تخلق نسخًا متكررة، وما الصفحة التي يجب أن تملك البحث العام. ثم نضيف معلومات حقيقية عن الخامة والمقاس والعناية والتوفر من صاحب المتجر، لا صفات نخترعها. السؤال العملي ليس كيف نكرر كلمة عبايات أكثر؛ بل كيف تساعد صفحة الفئة على الاختيار وتربط بمنتجات مناسبة. التحقق يشمل عنوان الصفحة وcanonical والروابط والنسخة المعروضة بعد التنفيذ." },
      { title: "حدود التنفيذ على سلة وزد", body: "لا أفترض أن كل باقة أو قالب يتيح نفس التحكم. قبل عرض سعر التنفيذ نحدد ما يمكن تعديله من لوحة المتجر، وما يحتاج مطور القالب، وما لا تتيحه المنصة. قائمة الأولويات تفصل تعديل العنوان والوصف والمحتوى عن تغيير التوجيهات أو canonical أو الأداء. لا نعد بإصلاح لا نستطيع تطبيقه على إعدادك الفعلي. ونفصل SEO عن ربط Merchant Center أو تشغيل الإعلانات: كل عمل له وصوله ونطاقه وموافقته. ملف النشاط التجاري أيضًا ليس متاحًا لكل متجر؛ النشاط الذي يعمل أونلاين فقط بلا تواصل حضوري مع العملاء لا يستوفي أهلية Google Business Profile." },
      { title: "أول دورة عمل وتقارير يمكن مراجعتها", body: "نبدأ بعنوان الموقع والمنصة والأسواق والمنتجات المهمة والبيانات المتاحة. التشخيص يخرج بقائمة صغيرة مرتبة حسب أثر المشكلة ومجهود الحل، ثم نختار مجموعة صفحات تجريبية ونراجع التنفيذ قبل التوسع. التقرير يوضح ما تغير بالفعل وما لم يتغير، مع نقرات واستعلامات Search Console إن توفرت، والطلبات والإيراد من بيانات المتجر إن كان القياس سليمًا. لا ننسب كل طلب إلى SEO ولا نضمن ترتيبًا أولًا. الموعد الذي نتفق عليه هو موعد تسليم ومراجعة العمل؛ استجابة البحث تختلف حسب الموقع والمنافسة ونوع التغيير." },
    ],
    en: [
      { title: "Saudi retail and local services need different scopes", body: "For a Saudi-facing store, start with sellable categories, availability, delivery coverage and useful product facts. Adding Riyadh or Jeddah to every title is not a strategy. A service business may need location pages when its real coverage and customer evidence justify them. Do not create city variants that only change a place name. An online-only business without in-person customer contact is not eligible for a Google Business Profile." },
      { title: "Illustrative store example, not a client result", body: "Imagine an abaya store with a category and many products sharing supplier descriptions. Check category indexing, variant URLs and the page that should serve the broad category query before adding articles. Use verified fabric, fit, care and availability facts from the merchant. Validate the title, canonical, links and rendered page after implementation. This is an example of the method, not a claim about a named customer or a sales increase." },
      { title: "Platform limits and reporting are explicit", body: "Salla and Zid changes depend on the actual plan, theme and exposed settings. Separate dashboard edits from work requiring a theme developer, and identify changes the platform does not permit. Merchant Center and advertising are separate scopes with separate access. Begin with a small reviewed page set, then expand only after validation. Reports distinguish completed work, search evidence and orders from the store's own measurement. Delivery dates are commitments to work, not guaranteed dates for rankings." },
    ],
  },
  uae: {
    ar: [
      { title: "استراتيجية الإمارات تبدأ باللغة والخدمة والتغطية", body: "وجود نسخة عربية وإنجليزية لا يعني أن نفس الكلمات أو الصفحات تناسب الجمهورين. نراجع لغة العملاء الفعلية وأسئلة المبيعات والخدمات التي يمكن تقديمها في دبي أو أبوظبي أو الإمارات الأخرى. بعض الكلمات لها صياغة عربية واضحة، وبعضها يُستخدم بالإنجليزية حتى داخل محادثة عربية. نحدد صفحة مناسبة لكل نية قبل الترجمة. ولا ننشئ صفحة لكل إمارة إذا كانت الخدمة والمعلومات نفسها؛ يجب أن يجد القارئ فرقًا مفيدًا مثل نطاق التغطية أو إجراءات الخدمة أو أمثلة يمكن إثباتها. لا ندعي وجود مكتب محلي لمجرد استهداف السوق." },
      { title: "مثال توضيحي: خدمة صيانة بجمهورين", body: "هذا مثال افتراضي وليس عميلًا موثقًا: شركة صيانة تخدم مناطق محددة، ولديها صفحات عربية وإنجليزية. نفصل سؤال الخدمة العاجلة عن سؤال الصيانة الدورية، ثم نكتب معلومات التغطية والتواصل والمواعيد وفق ما تقرره الشركة. النسخة الإنجليزية تحتاج صياغة يفهمها جمهورها، لا ترجمة آلية لكل كلمة. نراجع الروابط بين النسخ، وأن كل لغة تشير إلى نفسها وإلى نظيرتها في hreflang، وأن canonical لا يرسل الصفحة العربية إلى الإنجليزية بلا سبب. صفحات الخدمة المؤهلة يجب أن تساعد العميل على معرفة هل تُخدم منطقته قبل أن يرسل الطلب." },
      { title: "متى يدخل SEO المحلي في النطاق؟", body: "Google Business Profile يخدم الأنشطة المؤهلة التي تقابل العملاء حضوريًا في أوقات العمل، مع قواعد إضافية لنوع النشاط. المتجر أو شركة البرمجيات التي تعمل أونلاين فقط لا تصبح مؤهلة بمجرد بيعها في الإمارات. إذا كان لديك فرع حقيقي، نراجع بياناته وساعات عمله وتصنيفه وصلاحية تمثيل النشاط قبل اقتراح التعديل. وإذا كانت الخدمة تُقدم في موقع العميل، نراجع قواعد نشاط منطقة الخدمة بدل اختراع عنوان مكتب. لا نقترح شراء مراجعات أو نسخ صفحات مناطق. المواقع المالية والطبية تحتاج مراجعة المتخصص المسؤول عن دقة ادعاءات الخدمة، لا اجتهاد كاتب SEO." },
      { title: "كيف نقيس العمل باللغتين؟", body: "نبدأ بخط أساس للصفحات والاستعلامات واللغة عندما تسمح البيانات، ثم نراجع مسار الطلب من الصفحة إلى النموذج أو المكالمة أو CRM. تقسيم التقرير حسب اللغة مفيد إذا كانت العينات كافية، لكنه لا يثبت جنسية كل زائر أو مكانه بدقة. نسجل التغييرات وتواريخها، ونوضح أثر الإعلانات أو الموسمية إذا تداخلت مع المقارنة. في المرحلة الأولى يكون التسليم خريطة صفحات وأولويات تقنية وملخصات محتوى ومسؤول تنفيذ لكل مهمة. لا نعد بأن كل صفحة ستتصدر، ولا بأن تكلفة المستقل أقل دائمًا من الوكالة؛ الاختيار يتبع النطاق والقدرة على التنفيذ." },
    ],
    en: [
      { title: "Language, service and real coverage come first", body: "Arabic and English buyers may phrase the same need differently. Review customer language, sales questions and actual coverage before translating a page. Each page should own an intent. Emirate-specific pages need useful differences such as supported areas or service requirements, not a swapped place name. Serving the UAE remotely does not establish a local office, and the site should not imply one." },
      { title: "An illustrative bilingual maintenance business", body: "A maintenance company serving defined areas might separate urgent repairs from planned servicing. Its Arabic and English pages need accurate coverage, contact and appointment information from the business. Check reciprocal hreflang links and appropriate canonicals rather than pointing every Arabic page to English. This hypothetical example demonstrates a review method; it is not a named client engagement or an attributed growth result." },
      { title: "Local eligibility and language-aware measurement", body: "Business Profile eligibility depends on real in-person customer contact and the applicable business rules. Online-only businesses do not qualify just because they sell in the UAE. Do not invent an office address, buy reviews or generate duplicate area pages. Measure relevant pages and queries, then qualified calls or CRM outcomes where data exists. A language segment is not proof of a visitor's nationality. Report delivery, implementation and search impact separately, with comparison dates and limitations." },
    ],
  },
};

export function SeoBuyerGuide({ lang, market }: { lang: SeoLanguage; market: BuyerMarket }) {
  const ar = lang === "ar";
  return (
    <section className="border-y border-border bg-surface/30" aria-label={ar ? "دليل قرار التعاقد" : "Engagement decision guide"}>
      <div className="mx-auto max-w-6xl px-6 py-20">
        <p className="font-mono text-xs text-primary">{ar ? "مراجعة المحتوى: 7 أكتوبر 2026 · عمرو البصيلي" : "Content reviewed: 7 October 2026 · Amr Elbusaily"}</p>
        <div className="mt-8 grid gap-8 md:grid-cols-2">
          {guides[market][lang].map(item => <article key={item.title}><h2 className="text-2xl font-semibold">{item.title}</h2><p className="mt-4 leading-8 text-muted-foreground">{item.body}</p></article>)}
        </div>
        <div className="mt-10 border-t border-border pt-6">
          <h2 className="text-xl font-semibold">{ar ? "المراجع الرسمية وحدود النصيحة" : "Official sources and limits"}</h2>
          <p className="mt-3 leading-7 text-muted-foreground">{ar ? "المصادر التالية تشرح اختيار مقدم الخدمة والمحتوى المفيد وبنية اللغات وأهلية النشاط المحلي. لا تمثل اعتمادًا من جوجل لهذا الموقع أو ضمانًا للترتيب. الأسئلة الشائعة مفيدة للقارئ، لكن نتائج FAQ الغنية لم تعد تظهر في بحث جوجل." : "These sources cover choosing an SEO, useful content, language versions and local-business eligibility. They do not mean Google endorses this site or guarantees a ranking. FAQs can help readers, but Google no longer shows FAQ rich results."}</p>
          <ul className="mt-4 space-y-2 text-sm text-primary">{sources.map(source => <li key={source.href}><a href={source.href} className="underline underline-offset-4">{source.label}</a></li>)}<li><a href="https://developers.google.com/search/updates" className="underline underline-offset-4">Google Search documentation updates</a></li></ul>
          <a href={ar ? "/ar#results" : "/#results"} className="mt-5 inline-block text-sm text-primary underline underline-offset-4">{ar ? "راجع لقطات العمل مع حدودها وسياقها" : "Read the supplied work snapshots with their context and limits"}</a>
        </div>
      </div>
    </section>
  );
}
