/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArRouteImport } from './routes/ar'
import { Route as FreeConsultationRouteImport } from './routes/free-consultation'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ArIndexRouteImport } from './routes/ar.index'
import { Route as ArFreeConsultationRouteImport } from './routes/ar.free-consultation'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeConsultationRoute = FreeConsultationRouteImport.update({
  id: '/free-consultation',
  path: '/free-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ArIndexRoute = ArIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArRoute,
} as any)
const ArFreeConsultationRoute = ArFreeConsultationRouteImport.update({
  id: '/free-consultation',
  path: '/free-consultation',
  getParentRoute: () => ArRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ar': typeof ArRouteWithChildren
  '/free-consultation': typeof FreeConsultationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/free-consultation': typeof ArFreeConsultationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ar/': typeof ArIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/free-consultation': typeof FreeConsultationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/free-consultation': typeof ArFreeConsultationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ar': typeof ArIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ar': typeof ArRouteWithChildren
  '/free-consultation': typeof FreeConsultationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/free-consultation': typeof ArFreeConsultationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ar/': typeof ArIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ar'
    | '/free-consultation'
    | '/sitemap.xml'
    | '/ar/free-consultation'
    | '/blog/$slug'
    | '/ar/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/free-consultation'
    | '/sitemap.xml'
    | '/ar/free-consultation'
    | '/blog/$slug'
    | '/ar'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/ar'
    | '/free-consultation'
    | '/sitemap.xml'
    | '/ar/free-consultation'
    | '/blog/$slug'
    | '/ar/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArRoute: typeof ArRouteWithChildren
  FreeConsultationRoute: typeof FreeConsultationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-consultation': {
      id: '/free-consultation'
      path: '/free-consultation'
      fullPath: '/free-consultation'
      preLoaderRoute: typeof FreeConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/': {
      id: '/ar/'
      path: '/'
      fullPath: '/ar/'
      preLoaderRoute: typeof ArIndexRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/free-consultation': {
      id: '/ar/free-consultation'
      path: '/free-consultation'
      fullPath: '/ar/free-consultation'
      preLoaderRoute: typeof ArFreeConsultationRouteImport
      parentRoute: typeof ArRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArRouteChildren {
  ArFreeConsultationRoute: typeof ArFreeConsultationRoute
  ArIndexRoute: typeof ArIndexRoute
}

const ArRouteChildren: ArRouteChildren = {
  ArFreeConsultationRoute: ArFreeConsultationRoute,
  ArIndexRoute: ArIndexRoute,
}

const ArRouteWithChildren = ArRoute._addFileChildren(ArRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArRoute: ArRouteWithChildren,
  FreeConsultationRoute: FreeConsultationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
