/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArRouteImport } from './routes/ar'
import { Route as FreeConsultationRouteImport } from './routes/free-consultation'
import { Route as GrowthMarketingRouteImport } from './routes/growth-marketing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ArIndexRouteImport } from './routes/ar.index'
import { Route as ArFreeConsultationRouteImport } from './routes/ar.free-consultation'
import { Route as ArGrowthMarketingRouteImport } from './routes/ar.growth-marketing'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogContentPlanRouteImport } from './routes/blog.content-plan'
import { Route as CourseIndexRouteImport } from './routes/course.index'
import { Route as CourseLessonIdRouteImport } from './routes/course.$lessonId'
import { Route as ArCourseIndexRouteImport } from './routes/ar.course.index'
import { Route as ArCourseLessonIdRouteImport } from './routes/ar.course.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeConsultationRoute = FreeConsultationRouteImport.update({
  id: '/free-consultation',
  path: '/free-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthMarketingRoute = GrowthMarketingRouteImport.update({
  id: '/growth-marketing',
  path: '/growth-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ArIndexRoute = ArIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArRoute,
} as any)
const ArFreeConsultationRoute = ArFreeConsultationRouteImport.update({
  id: '/free-consultation',
  path: '/free-consultation',
  getParentRoute: () => ArRoute,
} as any)
const ArGrowthMarketingRoute = ArGrowthMarketingRouteImport.update({
  id: '/growth-marketing',
  path: '/growth-marketing',
  getParentRoute: () => ArRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogContentPlanRoute = BlogContentPlanRouteImport.update({
  id: '/blog/content-plan',
  path: '/blog/content-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseLessonIdRoute = CourseLessonIdRouteImport.update({
  id: '/course/$lessonId',
  path: '/course/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArCourseIndexRoute = ArCourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => ArRoute,
} as any)
const ArCourseLessonIdRoute = ArCourseLessonIdRouteImport.update({
  id: '/course/$lessonId',
  path: '/course/$lessonId',
  getParentRoute: () => ArRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ar': typeof ArRouteWithChildren
  '/free-consultation': typeof FreeConsultationRoute
  '/growth-marketing': typeof GrowthMarketingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/free-consultation': typeof ArFreeConsultationRoute
  '/ar/growth-marketing': typeof ArGrowthMarketingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/content-plan': typeof BlogContentPlanRoute
  '/course/$lessonId': typeof CourseLessonIdRoute
  '/ar/': typeof ArIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/course/': typeof CourseIndexRoute
  '/ar/course/$lessonId': typeof ArCourseLessonIdRoute
  '/ar/course/': typeof ArCourseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/free-consultation': typeof FreeConsultationRoute
  '/growth-marketing': typeof GrowthMarketingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/free-consultation': typeof ArFreeConsultationRoute
  '/ar/growth-marketing': typeof ArGrowthMarketingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/content-plan': typeof BlogContentPlanRoute
  '/course/$lessonId': typeof CourseLessonIdRoute
  '/ar': typeof ArIndexRoute
  '/blog': typeof BlogIndexRoute
  '/course': typeof CourseIndexRoute
  '/ar/course/$lessonId': typeof ArCourseLessonIdRoute
  '/ar/course': typeof ArCourseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ar': typeof ArRouteWithChildren
  '/free-consultation': typeof FreeConsultationRoute
  '/growth-marketing': typeof GrowthMarketingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/free-consultation': typeof ArFreeConsultationRoute
  '/ar/growth-marketing': typeof ArGrowthMarketingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/content-plan': typeof BlogContentPlanRoute
  '/course/$lessonId': typeof CourseLessonIdRoute
  '/ar/': typeof ArIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/course/': typeof CourseIndexRoute
  '/ar/course/$lessonId': typeof ArCourseLessonIdRoute
  '/ar/course/': typeof ArCourseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ar'
    | '/free-consultation'
    | '/growth-marketing'
    | '/sitemap.xml'
    | '/ar/free-consultation'
    | '/ar/growth-marketing'
    | '/blog/$slug'
    | '/blog/content-plan'
    | '/course/$lessonId'
    | '/ar/'
    | '/blog/'
    | '/course/'
    | '/ar/course/$lessonId'
    | '/ar/course/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/free-consultation'
    | '/growth-marketing'
    | '/sitemap.xml'
    | '/ar/free-consultation'
    | '/ar/growth-marketing'
    | '/blog/$slug'
    | '/blog/content-plan'
    | '/course/$lessonId'
    | '/ar'
    | '/blog'
    | '/course'
    | '/ar/course/$lessonId'
    | '/ar/course'
  id:
    | '__root__'
    | '/'
    | '/ar'
    | '/free-consultation'
    | '/growth-marketing'
    | '/sitemap.xml'
    | '/ar/free-consultation'
    | '/ar/growth-marketing'
    | '/blog/$slug'
    | '/blog/content-plan'
    | '/course/$lessonId'
    | '/ar/'
    | '/blog/'
    | '/course/'
    | '/ar/course/$lessonId'
    | '/ar/course/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArRoute: typeof ArRouteWithChildren
  FreeConsultationRoute: typeof FreeConsultationRoute
  GrowthMarketingRoute: typeof GrowthMarketingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogContentPlanRoute: typeof BlogContentPlanRoute
  CourseLessonIdRoute: typeof CourseLessonIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CourseIndexRoute: typeof CourseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-consultation': {
      id: '/free-consultation'
      path: '/free-consultation'
      fullPath: '/free-consultation'
      preLoaderRoute: typeof FreeConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-marketing': {
      id: '/growth-marketing'
      path: '/growth-marketing'
      fullPath: '/growth-marketing'
      preLoaderRoute: typeof GrowthMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/': {
      id: '/ar/'
      path: '/'
      fullPath: '/ar/'
      preLoaderRoute: typeof ArIndexRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/free-consultation': {
      id: '/ar/free-consultation'
      path: '/free-consultation'
      fullPath: '/ar/free-consultation'
      preLoaderRoute: typeof ArFreeConsultationRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/growth-marketing': {
      id: '/ar/growth-marketing'
      path: '/growth-marketing'
      fullPath: '/ar/growth-marketing'
      preLoaderRoute: typeof ArGrowthMarketingRouteImport
      parentRoute: typeof ArRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/content-plan': {
      id: '/blog/content-plan'
      path: '/blog/content-plan'
      fullPath: '/blog/content-plan'
      preLoaderRoute: typeof BlogContentPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/': {
      id: '/course/'
      path: '/course'
      fullPath: '/course/'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$lessonId': {
      id: '/course/$lessonId'
      path: '/course/$lessonId'
      fullPath: '/course/$lessonId'
      preLoaderRoute: typeof CourseLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/course/': {
      id: '/ar/course/'
      path: '/course'
      fullPath: '/ar/course/'
      preLoaderRoute: typeof ArCourseIndexRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/course/$lessonId': {
      id: '/ar/course/$lessonId'
      path: '/course/$lessonId'
      fullPath: '/ar/course/$lessonId'
      preLoaderRoute: typeof ArCourseLessonIdRouteImport
      parentRoute: typeof ArRoute
    }
  }
}

interface ArRouteChildren {
  ArFreeConsultationRoute: typeof ArFreeConsultationRoute
  ArGrowthMarketingRoute: typeof ArGrowthMarketingRoute
  ArIndexRoute: typeof ArIndexRoute
  ArCourseLessonIdRoute: typeof ArCourseLessonIdRoute
  ArCourseIndexRoute: typeof ArCourseIndexRoute
}

const ArRouteChildren: ArRouteChildren = {
  ArFreeConsultationRoute: ArFreeConsultationRoute,
  ArGrowthMarketingRoute: ArGrowthMarketingRoute,
  ArIndexRoute: ArIndexRoute,
  ArCourseLessonIdRoute: ArCourseLessonIdRoute,
  ArCourseIndexRoute: ArCourseIndexRoute,
}

const ArRouteWithChildren = ArRoute._addFileChildren(ArRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArRoute: ArRouteWithChildren,
  FreeConsultationRoute: FreeConsultationRoute,
  GrowthMarketingRoute: GrowthMarketingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogContentPlanRoute: BlogContentPlanRoute,
  CourseLessonIdRoute: CourseLessonIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  CourseIndexRoute: CourseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
